[package]
name = "prns-runtime"
version = "0.2.4"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
description = "Runtime-neutral Personal Reticulum node contracts and reactor kernel"
publish = false

[lib]
path = "src/lib.rs"

[features]
default = []
alloc = ["prns-core/alloc"]
interface-discovery = ["alloc", "prns-core/interface-discovery"]
interface-discovery-archive = ["std", "interface-discovery", "prns-core/interface-discovery-archive"]
external-alloc = ["alloc", "prns-core/external-alloc"]
std = ["alloc", "prns-core/std"]
runtime-metrics = ["alloc", "prns-core/runtime-metrics"]
rns-management = ["alloc", "prns-core/shared-instance-rpc"]

[dependencies]
prns-core = { path = "../../prns-core", default-features = false }
cfg-if = "1.0"

heapless = { version = "0.8", default-features = false }

[dev-dependencies]
prns-core = { path = "../../prns-core", default-features = false, features = ["test-support"] }
futures-executor = "0.3"

[lints]
workspace = true
