#!/usr/bin/env python3
"""Generate/check the app bindings, or build their single shared mobile image."""
import argparse
import importlib.util
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

HERE = Path(__file__).resolve().parent
APPLICATIONS = HERE.parents[1]
CRATE = APPLICATIONS / 'prns/native-composition'
BINDINGS = CRATE / 'bindings'
SHARED_TOOLING = APPLICATIONS.parent / 'tools/uniffi'
sys.path.insert(0, str(SHARED_TOOLING))
import tooling

sdk_spec = importlib.util.spec_from_file_location(
    'prns_sdk_generation', APPLICATIONS.parent / 'prns-react-native/tools/generate.py')
sdk = importlib.util.module_from_spec(sdk_spec)
sdk_spec.loader.exec_module(sdk)

OWNERSHIP = HERE / 'outputs.json'
run = tooling.run
generator = tooling.generator
existing_outputs = tooling.existing_outputs


def environment():
    return tooling.environment(APPLICATIONS / 'target')


def ownership(root=APPLICATIONS, manifest=OWNERSHIP):
    return tooling.ownership(root, manifest)


def synchronize_outputs(files, check, root=APPLICATIONS, manifest=OWNERSHIP):
    return tooling.synchronize_outputs(files, check, root, manifest)


def api_values(source, host_source=''):
    # Records have a generated factory and enums have a generated runtime value.
    # Re-export their paired TypeScript types without exposing execution methods
    # or the serialization-only Host transport records through the Expo SDK.
    transport_records = set(re.findall(r'^pub struct (\w+)', host_source, re.MULTILINE))
    names = sorted(set(re.findall(r'^export (?:const|enum) ([A-Z]\w*)\b', source, re.MULTILINE))
                   - transport_records)
    if not names:
        raise ValueError('generated API contains no record or enum values')
    return ('// Generated by applications/tools/generated-bindings/generate.py. Do not edit.\n'
            '// Public record factories and enums; execution remains behind the Expo facade.\n'
            'export {\n' + ''.join(f'  {name},\n' for name in names) + '} from "./prns_app";\n')


def generated_files(cli, env):
    recipe = tooling.BindingRecipe(
        manifest=APPLICATIONS / 'Cargo.toml', package='prns-app-native',
        library_name='prns_app', crate_dir=CRATE,
        typescript_dir=BINDINGS / 'typescript',
        swift_dir=APPLICATIONS / 'prns/platform/ios/generated',
        kotlin_dir=APPLICATIONS / 'prns/platform/android/src/main/java',
        features=('host-test', 'uniffi-bindgen'),
        extra_bins=('export_contract_fingerprints',),
    )
    files = tooling.generated_files(recipe, cli, env)
    # The SDK owns its generated namespace. This product package keeps only
    # product output and a stable import of the SDK's exact object converter.
    files = {path: content for path, content in files.items()
             if path.name in {'prns_app.ts', 'prns_app-ffi.ts', 'PrnsAppBindings.swift',
                              'PrnsAppBindingsFFI.h', 'PrnsAppBindingsFFI.modulemap', 'prns_app.kt'}}
    files[BINDINGS / 'typescript/prns_host_uniffi.ts'] = (
        '// Generated external namespace import; implementation belongs to the SDK.\n'
        'export * from "personal-rns-expo/bindings/values";\n'
        'export { default } from "personal-rns-expo/bindings/values";\n')
    target = Path(env['CARGO_TARGET_DIR']).resolve()
    fingerprints = json.loads(run(target / 'debug/export_contract_fingerprints', env=env, capture=True))
    files[BINDINGS / 'typescript/binding-contract.generated.ts'] = (
        '// Generated from the Rust app and canonical Host contract identifiers.\n'
        f'export const NATIVE_CONTRACT_FINGERPRINT = {json.dumps(fingerprints["app"])};\n'
        f'export const HOST_CONTRACT_FINGERPRINT = {json.dumps(fingerprints["host"])};\n')
    files[BINDINGS / 'typescript/api-values.generated.ts'] = api_values(
        files[BINDINGS / 'typescript/prns_app.ts'])
    return files


def generate(cli, env, check):
    # Validate owned output before writing. Canonical host generation is a
    # repository-wide prerequisite, never an app-owned schema walker.
    existing_outputs(*ownership())
    files = generated_files(cli, env)
    synchronize_outputs(files, check)
    sdk.generate(sdk.image_provider(BINDINGS / 'host-provider.json'), cli, env, check)


def build(cli, env, args):
    provider = sdk.image_provider(BINDINGS / 'host-provider.json')
    provider['features'] = ['apple' if args.command == 'ios' else 'android', 'uniffi-bindings']
    if args.command == 'ios' and not args.release:
        provider['features'].append('ios-restoration-probe')
    # The SDK package owns exactly one selected framework/library, including
    # when that image also contains this product namespace.
    sdk.build(provider, cli, env, args)


def execute(cli, env, args):
    if args.command == 'generate':
        generate(cli, env, args.check)
    else:
        # Both platforms must pair the current Rust image with current sources.
        # Explicit verification uses generate --check and never rewrites output.
        generate(cli, env, False)
        build(cli, env, args)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cache-dir', type=Path,
                        default=Path(os.environ.get('PRNS_UBRN_CACHE', APPLICATIONS / 'target/ubrn-tooling')))
    commands = parser.add_subparsers(dest='command', required=True)
    gen = commands.add_parser('generate')
    gen.add_argument('--check', action='store_true')
    for name in ('ios', 'android'):
        native = commands.add_parser(name)
        native.add_argument('--release', action='store_true')
        native.add_argument('--targets')
        if name == 'ios':
            native.add_argument('--sim-only', action='store_true')
    args = parser.parse_args()
    try:
        env = environment()
        cache = args.cache_dir.expanduser().resolve()
        cache.mkdir(parents=True, exist_ok=True)
        cli = generator(cache, env)
        execute(cli, env, args)
    except (ValueError, FileNotFoundError, subprocess.CalledProcessError) as error:
        parser.exit(1, f'generated bindings: {error}\n')
