#!/usr/bin/env python3
"""Generate/check the app bindings, or build their single shared mobile image."""
import argparse
import importlib.util
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import tempfile

HERE = Path(__file__).resolve().parent
APPLICATIONS = HERE.parents[1]
CRATE = APPLICATIONS / 'prns/native-composition'
BINDINGS = CRATE / 'bindings'
VENDOR_TOOL = APPLICATIONS / 'tools/ubrn-vendor/vendor.py'
OWNERSHIP = HERE / 'outputs.json'
spec = importlib.util.spec_from_file_location('prns_ubrn_vendor', VENDOR_TOOL)
vendor = importlib.util.module_from_spec(spec)
spec.loader.exec_module(vendor)


def run(*args, cwd=APPLICATIONS, env=None, capture=False):
    result = subprocess.run([str(arg) for arg in args], cwd=cwd, env=env, check=True,
                            stdout=subprocess.PIPE if capture else None, text=True)
    return result.stdout if capture else None


def environment():
    env = dict(os.environ)
    env.setdefault('CARGO_TARGET_DIR', str(APPLICATIONS / 'target'))
    env.setdefault('CARGO_BUILD_JOBS', '4')
    env.setdefault('RUSTUP_TOOLCHAIN', 'stable')
    # RUSTUP_TOOLCHAIN only affects rustup shims. A system Cargo earlier on
    # PATH would otherwise compile with a different Rust than the selected one.
    rustc = run('rustup', 'which', '--toolchain', env['RUSTUP_TOOLCHAIN'], 'rustc',
                env=env, capture=True).strip()
    env['PATH'] = str(Path(rustc).parent) + os.pathsep + env['PATH']
    if sys.platform == 'darwin':
        clang = run('xcrun', '--find', 'clang', capture=True).strip()
        env.update(PATH=str(Path(clang).parent) + os.pathsep + env['PATH'], CC=clang,
                   CXX=run('xcrun', '--find', 'clang++', capture=True).strip(),
                   AR=run('xcrun', '--find', 'ar', capture=True).strip(),
                   RANLIB=run('xcrun', '--find', 'ranlib', capture=True).strip(), LIBRARY_PATH='')
        for key in ('SDKROOT', 'CFLAGS', 'CXXFLAGS', 'CPPFLAGS'):
            env.pop(key, None)
    return env


def generator(cache, env):
    source, _ = vendor.prepare(cache, vendor.inputs())
    cli_env = generator_environment(cache, env)
    run('cargo', 'build', '--locked', '--no-default-features', '-p',
        'uniffi-bindgen-react-native', cwd=source, env=cli_env)
    return cache / 'cli-target/debug/uniffi-bindgen-react-native'


def generator_environment(cache, env):
    # The generator is third-party source built as a root Cargo package, so
    # Cargo's dependency lint cap does not apply. Keep app compiler policy on
    # the app, without changing the pinned upstream package to silence warnings.
    cli_env = dict(env, CARGO_TARGET_DIR=str(cache / 'cli-target'))
    for key in tuple(cli_env):
        if key in ('RUSTFLAGS', 'CARGO_ENCODED_RUSTFLAGS') or (
                key.startswith('CARGO_') and key.endswith('_RUSTFLAGS')):
            del cli_env[key]
    return cli_env


def normalize(text):
    return '\n'.join(line.rstrip() for line in text.splitlines()).rstrip() + '\n'


def api_values(source, host_source):
    # Records have a generated factory and enums have a generated runtime value.
    # Re-export their paired TypeScript types without exposing execution methods
    # or the serialization-only Host transport records through the Expo SDK.
    transport_records = set(re.findall(r'^pub struct (\w+)', host_source, re.MULTILINE))
    names = sorted(set(re.findall(r'^export (?:const|enum) ([A-Z]\w*)\b', source, re.MULTILINE))
                   - transport_records)
    if not names:
        raise ValueError('generated API contains no record or enum values')
    return ('// Generated by applications/tools/generated-bindings/generate.py. Do not edit.\n'
            '// Public record factories and enums; execution remains behind the Expo facade.\n'
            'export {\n' + ''.join(f'  {name},\n' for name in names) + '} from "./prns_app";\n')


def generated_files(cli, env):
    run('cargo', 'build', '--locked', '--manifest-path', APPLICATIONS / 'Cargo.toml',
        '-p', 'prns-app-native', '--features', 'host-test,uniffi-bindgen',
        '--lib', '--bin', 'uniffi-bindgen', '--bin', 'export_contract_fingerprints', env=env)
    target = Path(env['CARGO_TARGET_DIR']).resolve()
    suffix = 'dylib' if sys.platform == 'darwin' else 'so'
    library = target / f'debug/libprns_app.{suffix}'
    with tempfile.TemporaryDirectory(prefix='prns-generated-', dir=target) as temporary:
        temp = Path(temporary)
        ts = temp / 'typescript'
        native = temp / 'native'
        run(cli, 'generate', 'jsi2', 'bindings', '--library', library,
            '--ts-dir', ts, '--lib-name', 'prns_app', '--no-format', cwd=CRATE, env=env)
        run(target / 'debug/uniffi-bindgen', 'generate', '--library', library,
            '--config', CRATE / 'uniffi.toml', '--language', 'swift', '--language', 'kotlin',
            '--no-format', '--out-dir', native, env=env)
        files = {BINDINGS / 'typescript' / file.name: normalize(file.read_text())
                 for file in ts.glob('*.ts')}
        for file in native.iterdir():
            if file.is_file():
                files[APPLICATIONS / 'sdk/expo/ios/generated' / file.name] = normalize(file.read_text())
        for file in native.rglob('*.kt'):
            files[APPLICATIONS / 'sdk/expo/android/src/main/java' / file.relative_to(native)] = normalize(file.read_text())
        fingerprints = json.loads(run(target / 'debug/export_contract_fingerprints', env=env, capture=True))
        files[BINDINGS / 'typescript/binding-contract.generated.ts'] = (
            '// Generated from the Rust app and canonical Host contract identifiers.\n'
            f'export const NATIVE_CONTRACT_FINGERPRINT = {json.dumps(fingerprints["app"])};\n'
            f'export const HOST_CONTRACT_FINGERPRINT = {json.dumps(fingerprints["host"])};\n')
        files[BINDINGS / 'typescript/api-values.generated.ts'] = api_values(
            files[BINDINGS / 'typescript/prns_app.ts'],
            (CRATE / 'src/bindings/host_generated.rs').read_text())
        return files


def ownership(root=APPLICATIONS, manifest=OWNERSHIP):
    """Load reviewed output scopes, rejecting escapes and symlinked parents."""
    document = json.loads(manifest.read_text())
    if document.get('schemaVersion') != 1:
        raise ValueError('unsupported generated-output ownership version')
    root = root.resolve()

    def paths(key):
        result = []
        for value in document[key]:
            relative = Path(value)
            if relative.is_absolute() or not relative.parts or any(
                    part in ('', '.', '..') for part in value.split('/')):
                raise ValueError(f'invalid generated-output path: {value}')
            path = root / relative
            if any(part.is_symlink() for part in (path, *path.parents) if part != root):
                raise ValueError(f'symlink in generated-output path: {value}')
            if not path.resolve().is_relative_to(root):
                raise ValueError(f'generated-output path escapes applications: {value}')
            result.append(path)
        return result

    directories, singles = paths('directories'), paths('files')
    scaffolding = paths('scaffolding')
    if len(set(directories + singles + scaffolding)) != len(directories + singles + scaffolding):
        raise ValueError('generated-output ownership paths must be unique')
    if any(first != second and first.is_relative_to(second)
           for first in directories for second in directories):
        raise ValueError('generated-output directories must not overlap')
    if any(path.is_relative_to(directory) for path in singles + scaffolding for directory in directories):
        raise ValueError('individual files and scaffolding must be outside generated directories')
    return directories, singles


def synchronize_outputs(files, check, root=APPLICATIONS, manifest=OWNERSHIP):
    """Compare the complete owned output set; remove obsolete owned files only."""
    directories, singles = ownership(root, manifest)
    root = root.resolve()
    expected = set(files)
    for path in expected:
        if not path.is_absolute() or path != path.resolve():
            raise ValueError(f'generated output must be an absolute, non-symlink path: {path}')
        if path not in singles and not any(path.is_relative_to(directory) for directory in directories):
            raise ValueError(f'generator produced an unowned path: {path}')
        if any(part.is_symlink() for part in (path, *path.parents) if part != root):
            raise ValueError(f'symlink in generated output: {path}')
    if not set(singles).issubset(expected):
        raise ValueError('generator omitted an individually owned output')
    if any(not any(path.is_relative_to(directory) for path in expected) for directory in directories):
        raise ValueError('generator omitted an owned output directory')
    existing = existing_outputs(directories, singles)
    obsolete = existing - expected
    changed = {path for path, content in files.items()
               if not path.exists() or path.read_text() != content}
    if check and (changed or obsolete):
        details = [str(path.relative_to(root)) for path in sorted(changed)]
        details += [f'{path.relative_to(root)} (obsolete)' for path in sorted(obsolete)]
        raise ValueError('generated bindings differ; run npm run api:generate:\n' + '\n'.join(details))
    if not check:
        for path in sorted(obsolete):
            path.unlink()
        for path in sorted(changed):
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(files[path])


def existing_outputs(directories, singles):
    existing = {path for path in singles if path.exists()}
    for directory in directories:
        if directory.exists() and not directory.is_dir():
            raise ValueError(f'generated output directory is not a directory: {directory}')
        for path in directory.rglob('*'):
            if path.is_symlink():
                raise ValueError(f'symlink in generated output directory: {path}')
            if path.is_file():
                existing.add(path)
    return existing


def generate(cli, env, check):
    # Host adapters must exist before compiling the metadata library. Their
    # paths are fixed by host_contract.py and included in the complete inventory.
    existing_outputs(*ownership())
    run(sys.executable, HERE / 'host_contract.py', *(['--check'] if check else []), env=env)
    files = generated_files(cli, env)
    for path in (CRATE / 'src/bindings/host_generated.rs', CRATE / 'uniffi.toml',
                 BINDINGS / 'typescript/host-adapter.generated.ts'):
        files[path] = path.read_text()
    synchronize_outputs(files, check)


def build(cli, env, args):
    if args.command == 'android':
        expected = vendor.inputs()['toolchain']['androidNdk']
        sdk = Path(env.get('ANDROID_HOME') or env.get('ANDROID_SDK_ROOT') or
                   (Path.home() / ('Library/Android/sdk' if sys.platform == 'darwin' else 'Android/Sdk')))
        ndk = Path(env.get('ANDROID_NDK_HOME') or sdk / 'ndk' / expected).expanduser().resolve()
        properties = dict(tuple(part.strip() for part in line.split('=', 1))
                          for line in (ndk / 'source.properties').read_text().splitlines() if '=' in line)
        if properties.get('Pkg.Revision') != expected:
            raise ValueError(f'Android bindings require NDK {expected}; set ANDROID_NDK_HOME to that installation')
        env = dict(env, ANDROID_NDK_HOME=str(ndk), NDK_HOME=str(ndk))
    command = [cli, 'build', 'jsi2', args.command, '--config', BINDINGS / 'ubrn.config.yaml']
    if args.release:
        command.append('--release')
    if args.targets:
        command.extend(['--targets', args.targets])
    if args.command == 'ios' and args.sim_only:
        command.append('--sim-only')
    if args.command == 'ios' and not args.release:
        text = (BINDINGS / 'ubrn.config.yaml').read_text()
        text = text.replace('apple,uniffi-bindings', 'apple,uniffi-bindings,ios-restoration-probe')
        with tempfile.NamedTemporaryFile(mode='w', prefix='.ubrn-build-', suffix='.yaml', dir=BINDINGS) as config:
            config.write(text)
            config.flush()
            command[command.index('--config') + 1] = config.name
            run(*command, cwd=BINDINGS, env=env)
    else:
        run(*command, cwd=BINDINGS, env=env)


def execute(cli, env, args):
    if args.command == 'generate':
        generate(cli, env, args.check)
    else:
        # Both platforms must pair the current Rust image with current sources.
        # Explicit verification uses generate --check and never rewrites output.
        generate(cli, env, False)
        build(cli, env, args)


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--cache-dir', type=Path,
                        default=Path(os.environ.get('PRNS_UBRN_CACHE', APPLICATIONS / 'target/ubrn-tooling')))
    commands = parser.add_subparsers(dest='command', required=True)
    gen = commands.add_parser('generate')
    gen.add_argument('--check', action='store_true')
    for name in ('ios', 'android'):
        native = commands.add_parser(name)
        native.add_argument('--release', action='store_true')
        native.add_argument('--targets')
        if name == 'ios':
            native.add_argument('--sim-only', action='store_true')
    args = parser.parse_args()
    try:
        env = environment()
        cache = args.cache_dir.expanduser().resolve()
        cache.mkdir(parents=True, exist_ok=True)
        cli = generator(cache, env)
        execute(cli, env, args)
    except (ValueError, FileNotFoundError, subprocess.CalledProcessError) as error:
        parser.exit(1, f'generated bindings: {error}\n')
