#!/usr/bin/env python3
"""Generate the app's UniFFI transport views from the canonical Host schema.

The generated records are serialization artifacts. Runtime state remains the
canonical prns_host types; no app-owned copy of HostSnapshot is maintained.
"""
import argparse
import json
import re
import subprocess
from pathlib import Path

APPLICATIONS = Path(__file__).resolve().parents[2]
APP = APPLICATIONS / 'prns/native-composition'


def canonical_schema_path():
    # Resolve the app's actual locked dependency, including detached application
    # checkouts whose Prns core is a Cargo Git dependency outside this tree.
    metadata = json.loads(subprocess.check_output([
        'cargo', 'metadata', '--locked', '--format-version', '1',
        '--manifest-path', str(APPLICATIONS / 'Cargo.toml'),
    ], text=True))
    packages = {package['id']: package for package in metadata['packages']}
    app = next(package for package in packages.values()
               if Path(package['manifest_path']).resolve() == (APP / 'Cargo.toml').resolve())
    node = next(node for node in metadata['resolve']['nodes'] if node['id'] == app['id'])
    host_dependencies = [packages[dependency['pkg']] for dependency in node['deps']
                         if packages[dependency['pkg']]['name'] == 'prns-host']
    if len(host_dependencies) != 1:
        raise RuntimeError('expected exactly one locked prns-host dependency of prns-app-native')
    manifest = Path(host_dependencies[0]['manifest_path'])
    return manifest.parent.parent / 'schema/host-contract-v1.json'



def snake(name):
    return re.sub(r'(?<!^)(?=[A-Z])', '_', name).lower()


def generate(schema):
    records = {x['name']: x for x in schema['records']}
    enums = {x['name']: x for x in schema['enums']}
    fixed = {x['name']: x for x in schema['fixedBytes']}
    needed = set()

    def visit(typ):
        if isinstance(typ, dict):
            visit(typ['array'])
            return
        if typ in needed:
            return
        needed.add(typ)
        if typ in records:
            for field in records[typ]['fields']:
                visit(field['type'])
    visit('HostSnapshot')
    selected_records = [x for x in schema['records'] if x['name'] in needed]
    selected_enums = [x for x in schema['enums'] if x['name'] in needed]
    selected_fixed = [x for x in schema['fixedBytes'] if x['name'] in needed]

    def rust_type(typ):
        if isinstance(typ, dict):
            return f"Vec<{rust_type(typ['array'])}>"
        return {'string': 'String', 'safeUint': 'SafeUint'}.get(typ, typ + 'Transport' if typ in records else typ)

    def field_type(field):
        typ = rust_type(field['type'])
        return f'Option<{typ}>' if field.get('optional') else typ

    def convert(expr, typ, reverse=False):
        if isinstance(typ, dict):
            inner = convert("value", typ["array"], reverse)
            return expr if inner == "value" else f'{expr}.into_iter().map(|value| {inner}).collect::<Vec<_>>()'
        if typ == 'safeUint':
            return f'{expr}.0' if reverse else f'SafeUint({expr})'
        if typ in records:
            return f'{expr}.into()'
        return expr

    def convert_field(field, expr, reverse=False):
        if field.get('optional'):
            inner = convert("value", field["type"], reverse)
            if inner == "SafeUint(value)":
                return f'{expr}.map(SafeUint)'
            return expr if inner == "value" else f'{expr}.map(|value| {inner})'
        return convert(expr, field['type'], reverse)

    rust = ['// Generated by applications/tools/generated-bindings/host_contract.py. Do not edit.',
            '// Canonical source: prns-host/schema/host-contract-v1.json.', '']
    rust += ['#[derive(Clone, Copy, Debug, PartialEq, Eq)]', 'pub struct SafeUint(pub u64);',
             'uniffi::custom_type!(SafeUint, u64, {', '    lower: |value| value.0,',
             '    try_lift: |value| {', '        if value > 9_007_199_254_740_991 {',
             '            return Err(uniffi::deps::anyhow::anyhow!("safeUint exceeds the canonical JS integer range"));',
             '        }', '        Ok(SafeUint(value))', '    },', '});', '']
    for item in selected_fixed:
        name, length = item['name'], item['length']
        rust += [f'use prns_host::{name};', f'uniffi::custom_type!({name}, Vec<u8>, {{', '    remote,',
                 '    lower: |value| value.into_bytes().to_vec(),',
                 f'    try_lift: |value| Ok({name}::new(value.try_into().map_err(|_| uniffi::deps::anyhow::anyhow!("expected {length} bytes"))?)),', '});', '']
    for item in selected_enums:
        name = item['name']
        rust += [f'use prns_host::{name};', f'uniffi::custom_type!({name}, String, {{', '    remote,',
                 '    lower: |value| value.contract_name().to_owned(),', '    try_lift: |value| match value.as_str() {']
        for value in item['values']:
            rust += [f'        {json.dumps(value["name"])} => Ok({name}::{value["name"]}),']
        rust += ['        _ => Err(uniffi::deps::anyhow::anyhow!("unknown canonical enum value")),', '    },', '});', '']
    for record in selected_records:
        name = record['name']
        rust += ['#[derive(Clone, Debug, PartialEq, Eq, uniffi::Record)]', f'pub struct {name}Transport {{']
        for field in record['fields']:
            rust += [f"    pub {snake(field['name'])}: {field_type(field)},"]
        rust += ['}', f'impl From<prns_host::{name}> for {name}Transport {{', f'    fn from(value: prns_host::{name}) -> Self {{', '        Self {']
        for field in record['fields']:
            field_name = snake(field['name'])
            expr = f'value.{field_name}'
            if name == 'BackendInfo':
                expr += '()'
                if isinstance(field['type'], dict):
                    expr += '.collect::<Vec<_>>()'
            rust += [f'            {field_name}: {convert_field(field, expr)},']
        rust += ['        }', '    }', '}', f'impl From<{name}Transport> for prns_host::{name} {{', f'    fn from(value: {name}Transport) -> Self {{']
        fields = [(snake(f['name']), convert_field(f, f'value.{snake(f["name"])}', True)) for f in record['fields']]
        if name == 'BackendInfo':
            rust += ['        Self::new(' + ', '.join(v for _, v in fields) + ')']
        else:
            rust += ['        Self {'] + [f'            {n}: {v},' for n, v in fields] + ['        }']
        rust += ['    }', '}', '']
    rust += ['type CanonicalHostSnapshot = Box<prns_host::HostSnapshot>;',
             'uniffi::custom_type!(CanonicalHostSnapshot, HostSnapshotTransport, {', '    remote,',
             '    lower: |value| (*value).into(),', '    try_lift: |value| Ok(Box::new(value.into())),', '});', '']

    toml = ['# Generated by applications/tools/generated-bindings/host_contract.py. Do not edit.',
            '[bindings.typescript]', 'strictTypeChecking = true', 'strictByteArrays = true', '',
            '[bindings.swift]', 'module_name = "PrnsAppBindings"', '',
            '[bindings.kotlin]', 'package_name = "rs.reticulum.prns.app.bindings"', 'cdylib_name = "prns_app"', '']
    ts = ['// Generated by applications/tools/generated-bindings/host_contract.py. Do not edit.',
          'import type { ' + ', '.join(r['name'] for r in selected_records) + ' } from "personal-rns/contract";',
          'import type { ' + ', '.join(r['name'] + 'Transport' for r in selected_records) + ' } from "./prns_app";', '',
          'export function liftSafeUint(value: bigint): number {',
          '  if (value < 0n || value > 9_007_199_254_740_991n) throw new RangeError("safeUint is outside the canonical JS integer range");',
          '  return Number(value);', '}', 'export function lowerSafeUint(value: number): bigint {',
          '  if (!Number.isSafeInteger(value) || value < 0) throw new RangeError("expected a non-negative safe integer");',
          '  return BigInt(value);', '}', '']

    def config(name, type_name, into, out, imports):
        toml.extend([f'[bindings.typescript.customTypes.{name}]', f'typeName = {json.dumps(type_name)}',
                     'imports = ' + json.dumps(imports), f'intoCustom = {json.dumps(into)}', f'fromCustom = {json.dumps(out)}', ''])
    config('SafeUint', 'number', 'liftSafeUint({})', 'lowerSafeUint({})', [['liftSafeUint', './host-adapter.generated'], ['lowerSafeUint', './host-adapter.generated']])
    for item in selected_fixed:
        name, factory = item['name'], item['name'][0].lower() + item['name'][1:]
        config(name, 'Canonical'+name, f'{factory}({{}})', '{}', [[f'type {name} as Canonical{name}', 'personal-rns/contract'], [factory, 'personal-rns/contract']])
    for item in selected_enums:
        name = item['name']
        ts_name = 'CapabilityName' if name == 'Capability' else name
        ts += [f'import type {{ {ts_name} }} from "personal-rns/contract";',
               f'export function lift{name}(value: string): {ts_name} {{', '  switch (value) {']
        for value in item['values']:
            ts += [f'    case {json.dumps(value["name"])}: return value;']
        ts += ['    default: throw new TypeError("unknown canonical enum value");', '  }', '}', '']
        config(name, 'Canonical'+ts_name, f'lift{name}({{}})', '{}', [[f'type {ts_name} as Canonical{ts_name}', 'personal-rns/contract'], [f'lift{name}', './host-adapter.generated']])

    def ts_value(expr, typ, direction):
        if isinstance(typ, dict):
            return f'{expr}.map((item) => {ts_value("item", typ["array"], direction)})'
        if typ in records:
            return f'{direction}{typ}({expr})'
        return expr
    for record in selected_records:
        name = record['name']
        for direction in ['lift', 'lower']:
            source, target = (name+'Transport', name) if direction == 'lift' else (name, name+'Transport')
            ts += [f'export function {direction}{name}(value: {source}): {target} {{', '  return {']
            for field in record['fields']:
                f = field['name']
                expr = ts_value(f'value.{f}', field['type'], direction)
                ts += [f'    ...(value.{f} === undefined ? {{}} : {{ {f}: {expr} }}),'] if field.get('optional') else [f'    {f}: {expr},']
            ts += ['  };', '}', '']
    config('CanonicalHostSnapshot', 'HostSnapshot', 'liftHostSnapshot({})', 'lowerHostSnapshot({})', [['type HostSnapshot', 'personal-rns/contract'], ['liftHostSnapshot', './host-adapter.generated'], ['lowerHostSnapshot', './host-adapter.generated']])
    raw_rust = '\n'.join(rust)
    formatted = subprocess.run(['rustfmt', '--edition', '2021'], input=raw_rust, text=True, capture_output=True, check=True).stdout
    return {APP/'src/bindings/host_generated.rs': formatted, APP/'uniffi.toml': '\n'.join(toml), APP/'bindings/typescript/host-adapter.generated.ts': '\n'.join(ts)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    changed = []
    for path, content in generate(json.loads(canonical_schema_path().read_text())).items():
        if path.exists() and path.read_text() == content:
            continue
        changed.append(str(path.relative_to(APPLICATIONS)))
        if not args.check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content)
    if args.check and changed:
        parser.error('stale generated files: ' + ', '.join(changed))
    print('Canonical UniFFI Host adapters are current.' if args.check else 'Generated canonical UniFFI Host adapters.')


if __name__ == '__main__':
    main()
