import { createDevelopmentRuntime } from "./facade";
import nativePrnsApp from "./native";

export { HOST_CONTRACT_FINGERPRINT, NATIVE_CONTRACT_FINGERPRINT } from "./contract.generated";
export type * as WireContract from "./contract.generated";
export {
  NativeBridgeError,
  NativeContractMismatchError,
  type AnnounceLxmfOutcome,
  type Contact,
  type ContactListOutcome,
  type ContactLookupOutcome,
  type ContactMutationOutcome,
  type DescribeRemoteControlTargetInput,
  type DevelopmentNodeSnapshot,
  type DevelopmentNodeStartInput,
  type DevelopmentNodeStartOutcome,
  type DevelopmentNodeStopOutcome,
  type DevelopmentRuntime,
  type IdentityCreationOutcome,
  type IdentityImportPreviewOutcome,
  type InitiateRemoteControlPairingInput,
  type ListLxmfMessagesInput,
  type LxmfHealth,
  type LxmfMessage,
  type LxmfMessageListOutcome,
  type LxmfPeerListOutcome,
  type LxmfPeerSummary,
  type LxmfText,
  type MeasureLxmfTextInput,
  type MeasureLxmfTextOutcome,
  type PrimaryIdentityState,
  type RemoteControlDescribeOutcome,
  type RemoteControlPairingCommandOutcome,
  type RemoteControlPairingDecisionInput,
  type SendDirectTextInput,
  type SendDirectTextOutcome,
} from "./facade";
export {
  DevelopmentRuntimeConfigurationError,
  DevelopmentRuntimeOperationError,
  DevelopmentRuntimeStartError,
  DevelopmentRuntimeStopError,
  makeEffectDevelopmentRuntime,
  scopedDevelopmentRuntime,
  type DevelopmentRuntimeFailure,
  type DevelopmentRuntimeScopeOptions,
  type DevelopmentRuntimeSession,
  type EffectDevelopmentRuntime,
} from "./effects";
export { NativePayloadError } from "./hydrate";

export const developmentRuntime = createDevelopmentRuntime(nativePrnsApp);

export const {
  announceLxmf,
  approveRemoteControlPairing,
  createManualContact,
  createGeneratedIdentity,
  createImportedIdentity,
  describeRemoteControlTarget,
  deleteContact,
  getContact,
  inspectDevelopmentIdentity,
  initiateRemoteControlPairing,
  listLxmfMessages,
  listLxmfPeers,
  listContacts,
  measureLxmfText,
  previewIdentityImport,
  readDevelopmentNodeSnapshot,
  rejectRemoteControlPairing,
  resetDevelopmentData,
  saveObservedDestination,
  setContactAlias,
  setContactPinned,
  startDevelopmentNode,
  sendDirectText,
  stopDevelopmentNode,
} = developmentRuntime;
