import { createDevelopmentRuntime } from "./facade";
import { createAccessorySetupRuntime } from "./accessory-setup";
import { createAndroidRuntime } from "./android-runtime";
import { getNativePrnsApp, nativeAccessorySetup, nativeAndroidRuntime } from "./native";

export {
  createAndroidRuntime,
  parseAndroidRuntimeStatus,
  type AndroidRuntime,
  type AndroidRuntimeStatus,
} from "./android-runtime";

export {
  createAccessorySetupRuntime,
  parseAccessorySetupStatus,
  type AccessorySetupPickerOutcome,
  type AccessorySetupRuntime,
  type AccessorySetupStatus,
  type AccessorySetupSubscription,
} from "./accessory-setup";
export {
  NativeContractMismatchError,
  NativeStoragePreparationError,
  createDevelopmentRuntime,
  type DevelopmentRuntime,
} from "./facade";
export {
  DevelopmentRuntimeConfigurationError,
  DevelopmentRuntimeOperationError,
  DevelopmentRuntimeStartError,
  DevelopmentRuntimeStopError,
  makeEffectDevelopmentRuntime,
  scopedDevelopmentRuntime,
  type DevelopmentRuntimeFailure,
  type DevelopmentRuntimeScopeOptions,
  type DevelopmentRuntimeSession,
  type EffectDevelopmentRuntime,
} from "./effects";
export { NativePayloadError } from "./native-payload";

export const developmentRuntime = createDevelopmentRuntime(getNativePrnsApp);
export const accessorySetupRuntime = createAccessorySetupRuntime(nativeAccessorySetup);
export const androidRuntime = createAndroidRuntime(nativeAndroidRuntime);

export const {
  announceLxmf,
  approveRemoteControlPairing,
  cancelLxmfMessage,
  createManualContact,
  createGeneratedIdentity,
  createImportedIdentity,
  describeRemoteControlTarget,
  deleteContact,
  getContact,
  inspectDevelopmentIdentity,
  initiateRemoteControlPairing,
  listLxmfMessages,
  listLxmfPeers,
  listContacts,
  measureLxmfText,
  previewIdentityImport,
  readDevelopmentNodeSnapshot,
  rejectRemoteControlPairing,
  retryLxmfMessage,
  resetDevelopmentData,
  saveObservedDestination,
  setContactAlias,
  setContactPinned,
  startDevelopmentNode,
  sendDirectText,
  stopDevelopmentNode,
} = developmentRuntime;

export {
  AnnounceRemoteControlTargetInput,
  BindingContract,
  NativeStoragePreparationOutcome,
  NativeStoragePreparationOutcome_Tags,
  CancelLxmfMessageInput,
  Contact,
  ContactDestinationInput,
  CreateManualContactInput,
  DescribeRemoteControlTargetInput,
  DevelopmentNodeFailureStage,
  DevelopmentNodeFailure,
  DevelopmentNodeOperationKind,
  DevelopmentNodeOperation,
  DevelopmentNodeRuntime,
  PrimaryIdentityState_Tags,
  PrimaryIdentityState,
  LocalHostState_Tags,
  LocalHostState,
  LxmfHealthState,
  LxmfHealth,
  RemoteControlRequestKind,
  RemoteControlPairingFailureStage,
  RemoteControlPairingState_Tags,
  RemoteControlPairingState,
  RemoteControlPairingCandidate,
  RemoteControlTargetSnapshot,
  RemoteControlAnnounceFailureStage,
  RemoteControlAnnounceUnknownReason,
  RemoteControlAnnounceStatus_Tags,
  RemoteControlAnnounceStatus,
  RemoteControlAnnounceOperation,
  DevelopmentNodeSnapshot,
  DevelopmentNodeStartInput,
  InitiateRemoteControlPairingInput,
  ListLxmfMessagesInput,
  LxmfText_Tags,
  LxmfText,
  LxmfDirection,
  LxmfVerification,
  LxmfDeliveryFailure,
  LxmfDeliveryState_Tags,
  LxmfDeliveryState,
  LxmfMessage,
  LxmfPeerSummary,
  MeasureLxmfTextInput,
  RemoteControlPairingDecisionInput,
  RetryLxmfMessageInput,
  SendDirectTextInput,
  SetContactAliasInput,
  SetContactPinnedInput,
  AnnounceLxmfOutcome,
  AppleBluetoothRestorationPreparationFailureStage,
  AppleBluetoothRestorationPreparationOutcome_Tags,
  AppleBluetoothRestorationPreparationOutcome,
  CancelLxmfMessageOutcome_Tags,
  CancelLxmfMessageOutcome,
  ContactListOutcome_Tags,
  ContactListOutcome,
  ContactLookupOutcome_Tags,
  ContactLookupOutcome,
  ContactMutationOutcome_Tags,
  ContactMutationOutcome,
  DevelopmentNodeStartOutcome_Tags,
  DevelopmentNodeStartOutcome,
  DevelopmentNodeStopStage,
  DevelopmentNodeStopOutcome_Tags,
  DevelopmentNodeStopOutcome,
  IdentityCreationOutcome_Tags,
  IdentityCreationOutcome,
  IdentityImportPreviewOutcome_Tags,
  IdentityImportPreviewOutcome,
  LxmfMessageListOutcome_Tags,
  LxmfMessageListOutcome,
  LxmfPeerListOutcome_Tags,
  LxmfPeerListOutcome,
  MeasureLxmfTextOutcome_Tags,
  MeasureLxmfTextOutcome,
  RemoteControlAnnounceOutcome_Tags,
  RemoteControlAnnounceOutcome,
  RemoteControlDescribeFailureStage,
  RemoteControlDescribeOutcome_Tags,
  RemoteControlDescribeOutcome,
  RemoteControlPairingCommandOutcome_Tags,
  RemoteControlPairingCommandOutcome,
  RetryLxmfMessageOutcome_Tags,
  RetryLxmfMessageOutcome,
  SendDirectTextOutcome_Tags,
  SendDirectTextOutcome,
} from "@prns-internal/native-bindings";

export {
  HOST_CONTRACT_FINGERPRINT,
  NATIVE_CONTRACT_FINGERPRINT,
} from "@prns-internal/native-bindings";
