use std::env;
use std::fs;
use std::path::PathBuf;

use prns_flash_manifest::board_catalog;

pub(crate) fn generate() {
    println!("cargo:rerun-if-changed=../../release/flash/boards.json");
    let catalog = board_catalog().unwrap_or_else(|error| {
        panic!("shared board catalog is invalid: {error}");
    });
    let mut generated = String::from(
        "// @generated by build.rs from release/flash/boards.json; do not edit.\n\
         use super::{BoardTarget, PreparationProfile, Tier};\n\n\
         pub const SHIPPING_BOARD_TARGETS: &[BoardTarget] = &[\n",
    );
    for board in catalog.boards {
        let preparation_profile = match board.preparation_profile.as_str() {
            "esp-usb-boot" => "PreparationProfile::EspUsbBoot",
            "techo-uf2" => "PreparationProfile::TechoUf2",
            value => panic!("unsupported website preparation profile {value:?}"),
        };
        generated.push_str("    BoardTarget {\n");
        generated.push_str(&format!("        name: {:?},\n", board.display_name));
        generated.push_str(&format!("        slug: {:?},\n", board.slug));
        generated.push_str(&format!("        silicon: {:?},\n", board.silicon));
        generated.push_str("        tier: Tier::Flashable,\n");
        generated.push_str("        interfaces: &[\n");
        for interface in board.interfaces {
            generated.push_str(&format!("            {:?},\n", interface));
        }
        generated.push_str("        ],\n");
        generated.push_str(&format!("        icon: Some({:?}),\n", board.icon));
        generated.push_str(&format!(
            "        preparation_profile: Some({preparation_profile}),\n"
        ));
        generated.push_str("    },\n");
    }
    generated.push_str("];\n");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo");
    fs::write(PathBuf::from(out_dir).join("shipping_boards.rs"), generated)
        .expect("failed to write generated shipping board catalog");
}
