use std::env;
use std::fs;
use std::path::PathBuf;

use prns_flash_manifest::{board_catalog, BoardBuild, Transport};

pub(crate) fn generate() {
    println!("cargo:rerun-if-changed=../../release/flash/boards.json");
    let catalog = board_catalog().unwrap_or_else(|error| {
        panic!("shared board catalog is invalid: {error}");
    });
    let mut generated = String::from(
        "// @generated by build.rs from release/flash/boards.json; do not edit.\n\
         use super::{BoardFlashTarget, BoardTarget, PreparationProfile, Tier, ESPRESSIF_NATIVE_USB_VENDOR_ID};\n\n\
         pub const SHIPPING_BOARD_TARGETS: &[BoardTarget] = &[\n",
    );
    for board in catalog.shipping_boards() {
        let preparation_profile = match board.preparation_profile.as_str() {
            "esp-usb-boot" => "PreparationProfile::EspUsbBoot",
            "techo-uf2" => "PreparationProfile::TechoUf2",
            "t114-uf2" => "PreparationProfile::T114Uf2",
            value => panic!("unsupported website preparation profile {value:?}"),
        };
        let flash_target = match (&board.transport, &board.build) {
            (Transport::EspSerial, BoardBuild::Esp(_)) => {
                let expected_chip = board
                    .expected_chip
                    .as_deref()
                    .expect("validated ESP catalog target has a chip family");
                format!(
                    "BoardFlashTarget::EspSerial {{ expected_chip: {expected_chip:?}, web_serial_vendor_id: ESPRESSIF_NATIVE_USB_VENDOR_ID, supports_provisioning: {}, supports_tcp_client_provisioning: {} }}",
                    board.supports_provisioning(),
                    board.supports_tcp_client_provisioning()
                )
            }
            (Transport::Uf2MassStorage, BoardBuild::Uf2(build)) => format!(
                "BoardFlashTarget::Uf2MassStorage {{ mount_label: {:?}, board_id_prefix: {:?} }}",
                build.mount_label, build.board_id_prefix
            ),
            (Transport::NrfSerialDfu, BoardBuild::NrfSerialDfu(_)) => {
                panic!("qualification target entered the shipping website catalog")
            }
            _ => panic!("validated catalog transport and build recipe disagree"),
        };
        generated.push_str("    BoardTarget {\n");
        generated.push_str(&format!("        name: {:?},\n", board.display_name));
        generated.push_str(&format!("        slug: {:?},\n", board.slug));
        generated.push_str(&format!("        silicon: {:?},\n", board.silicon));
        generated.push_str("        tier: Tier::Flashable,\n");
        generated.push_str("        interfaces: &[\n");
        for interface in &board.interfaces {
            generated.push_str(&format!("            {:?},\n", interface));
        }
        generated.push_str("        ],\n");
        generated.push_str(&format!("        icon: Some({:?}),\n", board.icon));
        generated.push_str(&format!(
            "        preparation_profile: Some({preparation_profile}),\n"
        ));
        generated.push_str(&format!("        flash_target: Some({flash_target}),\n"));
        generated.push_str("    },\n");
    }
    generated.push_str("];\n");

    let out_dir = env::var_os("OUT_DIR").expect("OUT_DIR is set by Cargo");
    fs::write(PathBuf::from(out_dir).join("shipping_boards.rs"), generated)
        .expect("failed to write generated shipping board catalog");
}
