"""Availability accounting for native extensions outside the portable wire contract.

This inventory references public declarations, not another set of value fields.
It is documentation/coverage input and does not change native semantic fingerprints.
"""
import json
import os
from pathlib import Path
import re


INVENTORY_PATH = Path("prns-host/schema/native-extensions-v1.json")
DOCUMENT_PATH = Path("prns-host/native-extensions.generated.md")
TARGETS = ("native", "uniffi", "c", "napi", "cooperative")
TARGET_LABELS = ("Native Rust", "Native UniFFI", "C", "N-API", "Browser/cooperative")


def keys(value, required, optional=()):
    if not isinstance(value, dict) or set(value) - set(required) - set(optional) or set(required) - set(value):
        raise ValueError(f"invalid native extension inventory keys: expected {required}")


def validate(inventory, root):
    keys(inventory, ("schemaVersion", "kind", "targets", "extensions"))
    if inventory["schemaVersion"] != 1 or inventory["kind"] != "native-extension-availability":
        raise ValueError("unsupported native extension inventory version or kind")
    if inventory["targets"] != list(TARGETS):
        raise ValueError("native extension target inventory must be complete")
    names = set()
    for extension in inventory["extensions"]:
        keys(extension, ("name", "summary", "semantics", "targets"))
        name = extension["name"]
        if not isinstance(name, str) or not re.fullmatch(r"[a-z][A-Za-z0-9]*", name) or name in names:
            raise ValueError(f"invalid or duplicate native extension: {name}")
        names.add(name)
        if not all(isinstance(extension[field], str) and extension[field] for field in ("summary", "semantics")):
            raise ValueError(f"native extension {name} requires documented semantics")
        if set(extension["targets"]) != set(TARGETS):
            raise ValueError(f"native extension {name} target inventory must be complete")
        for target, support in extension["targets"].items():
            if support.get("status") == "unsupported":
                keys(support, ("status", "reason"))
                if not isinstance(support["reason"], str) or not support["reason"]:
                    raise ValueError(f"native extension {name}/{target} requires an unsupported reason")
                continue
            if support.get("status") != "supported":
                raise ValueError(f"unknown native extension status: {name}/{target}")
            keys(support, ("status", "declarations"))
            if not support["declarations"]:
                raise ValueError(f"native extension {name}/{target} requires source declarations")
            for declaration in support["declarations"]:
                keys(declaration, ("path", "kind", "name"), ("owner",))
                path = Path(declaration["path"])
                if path.is_absolute() or ".." in path.parts or path.suffix != ".rs":
                    raise ValueError(f"invalid native extension declaration path: {path}")
                source = (root / path).read_text()
                source = re.sub(r"(?m)^\s*//.*$", "", source)
                symbol = re.escape(declaration["name"])
                patterns = {
                    "function": rf"\bpub\s+(?:async\s+)?fn\s+{symbol}\s*\(",
                    "field": rf"\bpub\s+{symbol}\s*:",
                    "type": rf"\bpub\s+(?:struct|enum|type)\s+{symbol}\b",
                }
                kind = declaration["kind"]
                if kind not in patterns or not re.search(patterns[kind], source):
                    raise ValueError(f"missing native extension declaration: {path}:{declaration['name']}")
                if owner := declaration.get("owner"):
                    if not re.search(rf"\b(?:impl|struct|enum)\s+{re.escape(owner)}\b", source):
                        raise ValueError(f"missing native extension declaration owner: {path}:{owner}")
    if not names:
        raise ValueError("native extension inventory must not be empty")
    return inventory


def load(root):
    return validate(json.loads((root / INVENTORY_PATH).read_text()), root)


def documentation(inventory):
    lines = [
        "<!-- Generated by tools/repo/generate-host-contract.py; do not edit. -->",
        "# Native host extension availability", "",
        "The authoritative [extension inventory](schema/native-extensions-v1.json) records public APIs outside the portable host contract. Generation verifies supported source declarations and requires an explicit outcome for every target. This is API availability, not runtime permission, radio availability or a new BackendInfo capability bit. It does not change the portable ABI or its semantic fingerprint.", "",
        "| Extension | " + " | ".join(TARGET_LABELS) + " |",
        "| --- | " + " | ".join("---" for _ in TARGETS) + " |",
    ]
    for extension in inventory["extensions"]:
        lines.append("| " + extension["name"] + " | " + " | ".join(extension["targets"][target]["status"] for target in TARGETS) + " |")
    for extension in inventory["extensions"]:
        lines += ["", "## " + extension["name"], "", extension["summary"], "", extension["semantics"], ""]
        for target, label in zip(TARGETS, TARGET_LABELS):
            support = extension["targets"][target]
            if support["status"] == "unsupported":
                lines.append(f"- {label}: unsupported. {support['reason']}")
                continue
            references = []
            for declaration in support["declarations"]:
                name = ".".join(filter(None, (declaration.get("owner"), declaration["name"])))
                path = Path(os.path.relpath(declaration["path"], DOCUMENT_PATH.parent)).as_posix()
                references.append(f"[`{name}`]({path})")
            lines.append(f"- {label}: supported through " + ", ".join(references) + ".")
    lines += ["", "Remote Control has a separate [declaration-generated protocol inventory](schema/remote-control-v1.generated.json), including its target availability. Authenticated announce observation parity across foreign targets remains unimplemented; diagnostics must not be substituted for authenticated native service input.", ""]
    return "\n".join(lines)
