"""UniFFI transport generated from the canonical semantic host vocabulary.

Only Rust layout differences belong here. Field inventories and validation
semantics belong in the schema and canonical Rust constructors respectively.
"""
import hashlib
import json
from .formatting import format_rust
from .model import session_vocabulary, snake

# Rust represents these cases with tuple payloads rather than named fields.
TUPLES = {
    ('IdentityConfig', 'Existing'): ('Existing', None),
    ('DestinationIdentityConfig', 'DedicatedIdentity'): ('Dedicated', None),
    ('Bitrate', 'BitsPerSecond'): ('BitsPerSecond', None),
    ('DestinationConfig', 'Plain'): ('Plain', None),
    ('DestinationConfig', 'Single'): ('Single', 'SingleDestinationConfig'),
    ('HostLifecycleState', 'Stopped'): ('Stopped', None),
    ('HostLifecycleState', 'Failed'): ('Failed', None),
}
EVENT_RECORDS = {
    'SingleDelivery': 'SingleDelivery', 'LinkDelivery': 'LinkDelivery',
    'Request': 'RequestAvailable', 'Response': 'ResponseAvailable',
    'ResponseSegment': 'ResponseSegmentAvailable', 'ResourceAvailable': 'ResourceAvailable',
    'ResourceSegment': 'ResourceSegmentAvailable',
    'ResourceNeedsDecompression': 'ResourceNeedsDecompression', 'ChannelMessage': 'ChannelMessage',
}
CORE_NAMES = {'HostLifecycleState': 'LifecycleState'}
def secret_input_types(schema):
    """Propagate input-only ownership through the semantic graph, not a field list."""
    vocabulary = session_vocabulary(schema)
    secret = {item['name'] for item in vocabulary['fixedBytes'] if item.get('secret')}
    if secret != {'IdentitySecret'}:
        raise ValueError("secret types require an explicit zeroizing Rust owner mapping")
    def name(t):
        return name(t['array']) if isinstance(t, dict) else t
    changed = True
    while changed:
        changed = False
        for item in vocabulary['records'] + vocabulary['unions']:
            fields = item.get('fields', [field for case in item.get('cases', []) for field in case['fields']])
            if item['name'] not in secret and any(name(field['type']) in secret for field in fields):
                secret.add(item['name'])
                changed = True
    return secret - {'IdentitySecret'}


def generate_rust(schema):
    vocabulary = session_vocabulary(schema)
    input_only = secret_input_types(schema)
    records = {v['name']: v for v in vocabulary['records']}
    unions = {v['name']: v for v in vocabulary['unions']}
    enums = {v['name']: v for v in vocabulary['enums']}
    fixed = {v['name']: v for v in vocabulary['fixedBytes']}
    scalar = {v['name']: v['storage'] for v in vocabulary['scalars']}
    known = records.keys() | unions.keys() | enums.keys()
    fingerprint = hashlib.sha256(json.dumps(schema, sort_keys=True, separators=(',', ':')).encode()).hexdigest()

    def core(name):
        return 'prns_host::' + CORE_NAMES.get(name, name)

    def typ(t):
        if isinstance(t, dict): return f"Vec<{typ(t['array'])}>"
        if t in fixed: return 'IdentitySecretInput' if fixed[t].get('secret') else 'Vec<u8>'
        return {'bytes': 'Vec<u8>', 'string': 'String', 'u128': 'WideCounter',
                'ResourceStream': 'ResourceDescriptor', **scalar}.get(t, t)

    def field_type(f):
        t = typ(f['type'])
        return f'Option<{t}>' if f.get('optional') else t

    def convert(t, expr, reverse=False):
        if isinstance(t, dict):
            inner = convert(t['array'], 'item', reverse)
            if inner == 'item': return expr
            if reverse: return f'{expr}.into_iter().map(|item| Ok({inner})).collect::<Result<Vec<_>, BindingError>>()?'
            return f'{expr}.into_iter().map(|item| {inner}).collect()'
        if t in fixed:
            if reverse:
                if t == 'IdentitySecret': return f'{expr}.into_core()'
                return f'{core(t)}::new(fixed_bytes::<{fixed[t]["length"]}>({expr}, "{t}")?)'
            return f'{expr}.into_bytes().to_vec()'
        if t == 'safeUint': return f'safe_uint({expr})?' if reverse else expr
        if t == 'safeInt': return f'safe_int({expr})?' if reverse else expr
        if t == 'u128': return f'{expr}.into()'
        if t in known:
            return f'{expr}.try_into()?' if reverse and t not in enums else f'{expr}.into()'
        return expr

    def conv_field(f, expr, reverse=False):
        if f.get('optional'):
            inner = convert(f['type'], 'item', reverse)
            if inner == 'item': return expr
            if reverse: return f'{expr}.map(|item| Ok({inner})).transpose()?'
            return f'{expr}.map(|item| {inner})'
        return convert(f['type'], expr, reverse)

    lines = ['// Generated by tools/repo/generate-host-contract.py. Do not edit.',
             '#![allow(deprecated)]', 'use zeroize::Zeroize;',
             f'pub const HOST_SEMANTIC_FINGERPRINT: &str = "{fingerprint}";',
             '''#[derive(Debug, thiserror::Error, uniffi::Error)]
pub enum BindingError {
    #[error("host admission limit reached")]
    Busy,
    #[error("host stopped")]
    Stopped,
    #[error("stream lane already claimed")]
    AlreadyClaimed,
    #[error("wait interrupted")]
    Interrupted,
    #[error("invalid {field}: {detail}")]
    InvalidInput { field: String, detail: String },
    #[error("host contract mismatch: {detail}")]
    ContractMismatch { detail: String },
    #[error("host ownership unavailable: {detail}")]
    OwnershipUnavailable { detail: String },
    #[error("host binding failure: {detail}")]
    Backend { detail: String },
}
fn invalid(field: &str, detail: impl Into<String>) -> BindingError {
    BindingError::InvalidInput { field: field.into(), detail: detail.into() }
}
fn safe_uint(value: u64) -> Result<u64, BindingError> {
    if value > prns_host::SAFE_UINT_MAX { return Err(invalid("safeUint", "outside exact JS integer range")); }
    Ok(value)
}
fn safe_int(value: i64) -> Result<i64, BindingError> {
    if !(prns_host::SAFE_INT_MIN..=prns_host::SAFE_INT_MAX).contains(&value) {
        return Err(invalid("safeInt", "outside exact JS integer range"));
    }
    Ok(value)
}
fn fixed_bytes<const N: usize>(value: Vec<u8>, field: &str) -> Result<[u8; N], BindingError> {
    value.try_into().map_err(|_| invalid(field, format!("expected {N} bytes")))
}
fn identity_secret(mut value: Vec<u8>) -> Result<prns_host::IdentitySecret, BindingError> {
    let mut bytes = [0; prns_host::IDENTITY_SECRET_LENGTH];
    if value.len() != bytes.len() {
        value.zeroize();
        return Err(invalid("IdentitySecret", "expected 64 bytes"));
    }
    bytes.copy_from_slice(&value);
    value.zeroize();
    let secret = prns_host::IdentitySecret::new(bytes);
    bytes.zeroize();
    Ok(secret)
}
/// Input-only key material, zeroizing even when an enclosing input is rejected.
/// The SDK exports no functions returning this type or secret-bearing configs.
pub struct IdentitySecretInput(prns_host::IdentitySecret);
impl IdentitySecretInput {
    pub fn into_core(self) -> prns_host::IdentitySecret { self.0 }
}
impl TryFrom<Vec<u8>> for IdentitySecretInput {
    type Error = BindingError;
    fn try_from(value: Vec<u8>) -> Result<Self, Self::Error> { Ok(Self(identity_secret(value)?)) }
}
uniffi::custom_type!(IdentitySecretInput, Vec<u8>, {
    lower: |value| value.0.expose().to_vec(),
    try_lift: |value| Ok(IdentitySecretInput::try_from(value)?),
});
#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Record)]
pub struct WideCounter { pub high: u64, pub low: u64 }
impl From<u128> for WideCounter {
    fn from(value: u128) -> Self { Self { high: (value >> 64) as u64, low: value as u64 } }
}
impl From<WideCounter> for u128 {
    fn from(value: WideCounter) -> Self { (u128::from(value.high) << 64) | u128::from(value.low) }
}
/// A session-scoped resource token. The owning facade resolves the token;
/// it is never a process pointer and grants no access to another session.
#[derive(Clone, Debug, PartialEq, Eq, uniffi::Record)]
pub struct ResourceDescriptor { pub stream_id: u64, pub total_bytes: u64 }
''']
    for item in enums.values():
        name = item['name']
        lines += ['#[derive(Clone, Copy, Debug, PartialEq, Eq, uniffi::Enum)]', f'pub enum {name} {{']
        lines += [f'    {v["name"]},' for v in item['values']]
        lines += ['}']
        for reverse in (False, True):
            src, dst = (name, core(name)) if reverse else (core(name), name)
            lines += [f'impl From<{src}> for {dst} {{', f'    fn from(value: {src}) -> Self {{', '        match value {']
            lines += [f'            {src}::{v["name"]} => Self::{v["name"]},' for v in item['values']]
            lines += ['        }', '    }', '}']
    for item in records.values():
        name = item['name']
        derive = 'uniffi::Record' if name in input_only else 'Clone, Debug, PartialEq, Eq, uniffi::Record'
        lines += [f'#[derive({derive})]', f'pub struct {name} {{']
        lines += [f'    pub {snake(f["name"])}: {field_type(f)},' for f in item['fields']]
        lines += ['}']
        for reverse in (False, True):
            if not reverse and name in input_only: continue
            src, dst = (name, core(name)) if reverse else (core(name), name)
            trait, method, result = ('TryFrom', 'try_from', 'Result<Self, Self::Error>') if reverse else ('From', 'from', 'Self')
            lines += [f'impl {trait}<{src}> for {dst} {{']
            if reverse: lines += ['    type Error = BindingError;']
            lines += [f'    fn {method}(value: {src}) -> {result} {{']
            fields = []
            for f in item['fields']:
                n = snake(f['name']); expr = f'value.{n}'
                if not reverse and name in ('BackendInfo', 'DestinationName', 'PrnsLimits'):
                    expr += '()'
                    if name == 'BackendInfo' and isinstance(f['type'], dict): expr += '.collect::<Vec<_>>()'
                    if name == 'DestinationName': expr += '.to_owned()'
                    if name == 'PrnsLimits': expr += ' as u64'
                value = conv_field(f, expr, reverse)
                if reverse and name == 'PrnsLimits': value = f'usize::try_from({value}).map_err(|_| invalid("{n}", "outside native size range"))?'
                fields.append((n, value))
            if reverse and name in ('BackendInfo','DestinationName','PrnsLimits'):
                ctor = 'new' if name == 'BackendInfo' else 'try_new'
                expression = f'Self::{ctor}(' + ', '.join(v for _,v in fields) + ')'
                if ctor == 'try_new': expression += f'.map_err(|error| invalid("{name}", format!("{{error:?}}")))?'
            else:
                expression = 'Self { ' + ', '.join(f'{n}: {v}' for n,v in fields) + ' }'
            lines += [f'        {"Ok(" if reverse else ""}{expression}{")" if reverse else ""}', '    }', '}']
    for item in unions.values():
        name = item['name']
        derive = 'uniffi::Enum' if name in input_only else 'Clone, Debug, PartialEq, Eq, uniffi::Enum'
        lines += [f'#[derive({derive})]', f'pub enum {name} {{']
        for case in item['cases']:
            fields = ', '.join(f'{snake(f["name"])}: {field_type(f)}' for f in case['fields'])
            lines += [f'    {case["name"]}' + (f' {{ {fields} }}' if fields else '') + ',']
        lines += ['}']
        if name == 'CommandSettlement':
            lines += ['impl From<Result<prns_host::CommandOutcome, prns_host::CommandFailure>> for CommandSettlement {',
                      '    fn from(value: Result<prns_host::CommandOutcome, prns_host::CommandFailure>) -> Self {',
                      '        match value { Ok(value) => Self::Succeeded { outcome: value.into() }, Err(value) => Self::Failed { failure: value.into() } }', '    }', '}']
            continue
        for reverse in (False, True):
            if not reverse and name in input_only: continue
            # Events are output-only. Resource handles cannot be invented by input DTOs.
            if reverse and name in ('ApplicationEvent','DiagnosticEvent'): continue
            src, dst = (name, core(name)) if reverse else (core(name), name)
            trait, method, result = ('TryFrom', 'try_from', 'Result<Self, Self::Error>') if reverse else ('From', 'from', 'Self')
            lines += [f'impl {trait}<{src}> for {dst} {{']
            if reverse: lines += ['    type Error = BindingError;']
            lines += [f'    fn {method}(value: {src}) -> {result} {{', '        ' + ('Ok(' if reverse else '') + 'match value {']
            for case in item['cases']:
                cname, fs = case['name'], case['fields']
                if name == 'DiagnosticEvent' and cname == 'DiagnosticsDropped': continue
                fields = [snake(f['name']) for f in fs]
                if name == 'CommandOutcome' and cname == 'PacketDelivered':
                    if reverse:
                        lines += ['            CommandOutcome::PacketDelivered { rtt_millis, evidence, packet_hash } => {',
                                  '                let evidence = match (evidence, packet_hash) {',
                                  '                    (DeliveryEvidenceKind::ExplicitProof, Some(hash)) => prns_host::DeliveryEvidence::ExplicitProof(prns_host::PacketHash::new(fixed_bytes(hash, "PacketHash")?)),',
                                  '                    (DeliveryEvidenceKind::ImplicitProof, Some(hash)) => prns_host::DeliveryEvidence::ImplicitProof(prns_host::PacketHash::new(fixed_bytes(hash, "PacketHash")?)),',
                                  '                    (DeliveryEvidenceKind::Response, None) => prns_host::DeliveryEvidence::Response,',
                                  '                    _ => return Err(invalid("PacketDelivered", "proof evidence requires a packet hash; response evidence forbids one")),',
                                  '                };', '                Self::PacketDelivered { rtt_millis: safe_uint(rtt_millis)?, evidence }', '            },']
                    else:
                        lines += ['            prns_host::CommandOutcome::PacketDelivered { rtt_millis, evidence } => {',
                                  '                let packet_hash = match evidence { prns_host::DeliveryEvidence::ExplicitProof(hash) | prns_host::DeliveryEvidence::ImplicitProof(hash) => Some(hash.into_bytes().to_vec()), prns_host::DeliveryEvidence::Response => None };',
                                  '                Self::PacketDelivered { rtt_millis, evidence: evidence.kind().into(), packet_hash }', '            },']
                    continue
                rust_case, tuple_record = TUPLES.get((name,cname),(cname,False))
                if name == 'ApplicationEvent': tuple_record = EVENT_RECORDS[cname]
                if not reverse and name == 'ApplicationEvent' and cname == 'ResourceAvailable':
                    lines += ['            prns_host::ApplicationEvent::ResourceAvailable(value) => Self::ResourceAvailable {',
                              '                link_id: value.link_id.into_bytes().to_vec(), hash: value.hash.into_bytes().to_vec(), metadata: value.metadata,',
                              '                resource: ResourceDescriptor { stream_id: value.stream_id.get(), total_bytes: value.total_bytes },', '            },']
                    continue
                if tuple_record is not False and not reverse:
                    if tuple_record is None: pattern = f'{src}::{rust_case}({fields[0]})'
                    else: pattern = f'{src}::{rust_case}({core(tuple_record)} {{ ' + ', '.join(fields) + ' })'
                else: pattern = f'{src}::{cname}' + (' { ' + ', '.join(fields) + ' }' if fs else '')
                vals = [(snake(f['name']), conv_field(f, snake(f['name']), reverse)) for f in fs]
                if name == 'HostFailure' and cname == 'EventBackpressureExceeded':
                    vals = [(n, f'usize::try_from({v}).map_err(|_| invalid("rejectedEventBytes", "outside native size range"))?' if reverse and n=='rejected_event_bytes' else f'{v} as u64' if not reverse and n=='rejected_event_bytes' else v) for n,v in vals]
                if tuple_record is not False and reverse:
                    if tuple_record is None: expression = f'Self::{rust_case}({vals[0][1]})'
                    else:
                        vals = [(n,f'{v}.unwrap_or_default()' if n=='announce_app_data' else v) for n,v in vals]
                        args = dict(vals)
                        expression = '{ let mut destination = ' + core(tuple_record) + '::new(' + args['name'] + ', ' + args['identity'] + '); '
                        expression += ' '.join(f'destination.{n} = {v};' for n,v in vals if n not in ('name','identity'))
                        expression += f' Self::{rust_case}(destination)' + ' }'
                else: expression = f'Self::{cname}' + (' { ' + ', '.join(f'{n}: {v}' for n,v in vals) + ' }' if fs else '')
                lines += [f'            {pattern} => {expression},']
            lines += ['        }' + (')' if reverse else ''), '    }', '}']
    lines += ['''impl DiagnosticEvent {
    pub fn dropped(count: u128) -> Self { Self::DiagnosticsDropped { count: count.into() } }
}
pub fn diagnostic_batch(value: prns_host::DiagnosticBatch) -> Vec<DiagnosticEvent> {
        let mut events: Vec<_> = value.events.into_iter().map(Into::into).collect();
        if value.dropped_newest != 0 { events.push(DiagnosticEvent::dropped(value.dropped_newest)); }
        events
}
''']
    return format_rust('\n'.join(lines))


def coverage(schema, extensions=None):
    vocabulary = session_vocabulary(schema)
    projections = {}
    def project(names, target, status="projected"):
        for name in names.split():
            projections[name] = {"status": status, "target": target}
    project("contractInfo", "bindingContract: semantic fingerprint and package version")
    project("backendInfo", "backendInfo")
    project("hostCreate hostRelease hostStop", "Owned HostSession open/stop/nonblocking finalization")
    project("hostLifecycle", "Host.lifecycle")
    project("hostSnapshot hostSnapshotRead hostSnapshotRelease", "Host.snapshot async owned value")
    project("hostIdentityHash", "Host.identityHash")
    project("hostDestinationCount hostDestinationHash", "Host.destinationHashes owned array")
    project("hostAttachSuppliedPipe suppliedPipeClaimAttachment suppliedPipeNextOpenRequest suppliedPipeRegisterReadiness suppliedPipeInterruptWait suppliedPipeRelease suppliedPipeOpenRequestProvide suppliedPipeOpenRequestDecline suppliedPipeOpenRequestRelease", "Rust prepared transport embedding; no foreign file descriptor ownership API", "native-embedding-only")
    project("hostBeginResourceUpload", "Host.beginResourceUpload")
    project("resourceUploadWrite resourceUploadIsWritable", "ResourceUpload.writeChunk async readiness/admission")
    project("resourceUploadFinish", "ResourceUpload.finish")
    project("resourceUploadAbort resourceUploadRelease", "ResourceUpload.abort/nonblocking finalization")
    project("commandWait commandRegisterReadiness commandInterruptWait commandRelease", "Host.execute foreign future; wait cancellation does not cancel accepted command")
    project("hostClaimApplicationEvents hostClaimDiagnostics", "Host.applicationEvents/diagnostics single-consumer leases")
    project("eventStreamRegisterReadiness eventStreamInterruptWait readinessRegistrationRelease", "EventStream.ready non-consuming cancellable future")
    project("eventStreamRelease", "EventStream.close/nonblocking finalization")
    project("eventStreamNext", "EventStream.tryNext bounded nonblocking transfer")
    project("eventRelease eventKind eventBytes eventString eventU64 eventU128", "Generated typed HostEvent value with exact scalar conversions")
    project("eventResourceStream", "Owned ResourceReader alongside ApplicationEvent resource descriptor")
    project("resourceStreamRelease resourceStreamNext", "ResourceReader.readChunk/close/nonblocking finalization")
    names = {v['name'] for v in schema['operations']}
    if names != projections.keys():
        raise ValueError(f"UniFFI operation projection coverage drift: missing={names - projections.keys()}, stale={projections.keys() - names}")
    result = {'records':[v['name'] for v in vocabulary['records']],
              'unions':{v['name']:[c['name'] for c in v['cases']] for v in vocabulary['unions']},
              'rawOperations':projections,
              'commands':schema['commandProjection']['outcomes'],
              'inputOnly': sorted(secret_input_types(schema)),
              'resourceHandle': 'Session-scoped ResourceDescriptor, resolved by owning session; never a raw pointer',
              'diagnosticsDropped': 'Synthetic DiagnosticBatch overflow item with exact two-u64 counter'}
    if extensions is not None:
        result['nativeExtensions'] = extensions
    return json.dumps(result,indent=2)+'\n'


def generate_typescript(schema):
    vocabulary = session_vocabulary(schema)
    input_only = secret_input_types(schema)
    records = {v['name']: v for v in vocabulary['records']}
    unions = {v['name']: v for v in vocabulary['unions']}
    enums = {v['name']: v for v in vocabulary['enums']}
    fixed = {v['name']: v for v in vocabulary['fixedBytes']}
    def canonical(name):
        return 'C.' + {'Capability':'CapabilityName','HostRole':'HostRoleName'}.get(name,name)
    lines = ['// Generated by tools/repo/generate-host-contract.py. Do not edit.',
             'import * as C from "personal-rns/contract";',
             'import * as N from "./prns_host_uniffi";',
             'export type ResourceFactory = (value: N.ResourceDescriptor) => C.ResourceStream;',
             f'export const HOST_SEMANTIC_FINGERPRINT = {json.dumps(hashlib.sha256(json.dumps(schema, sort_keys=True, separators=(",", ":")).encode()).hexdigest())};',
             '''export function liftSafeUint(value: bigint): number {
  if (value < 0n || value > 9_007_199_254_740_991n) throw new RangeError("safeUint outside exact JS integer range");
  return Number(value);
}
export function lowerSafeUint(value: number): bigint {
  if (!Number.isSafeInteger(value) || value < 0) throw new RangeError("expected a non-negative safe integer");
  return BigInt(value);
}
export function liftSafeInt(value: bigint): number {
  if (value < -9_007_199_254_740_991n || value > 9_007_199_254_740_991n) throw new RangeError("safeInt outside exact JS integer range");
  return Number(value);
}
export function lowerSafeInt(value: number): bigint {
  if (!Number.isSafeInteger(value)) throw new RangeError("expected a safe integer");
  return BigInt(value);
}
export function liftWideCounter(value: N.WideCounter): bigint {
  if (value.high < 0n || value.high > 0xffff_ffff_ffff_ffffn || value.low < 0n || value.low > 0xffff_ffff_ffff_ffffn) throw new RangeError("invalid u128 limbs");
  return (value.high << 64n) | value.low;
}
export function lowerWideCounter(value: bigint): N.WideCounter {
  if (value < 0n || value > (1n << 128n) - 1n) throw new RangeError("u128 out of range");
  return { high: value >> 64n, low: value & 0xffff_ffff_ffff_ffffn };
}
function unexpected(value: never): never { throw new TypeError(`unknown host contract case: ${String(value)}`); }
''']
    needed_enums = set()
    def note(t):
        if isinstance(t,dict): return note(t['array'])
        if t in enums: needed_enums.add(t)
    for item in records.values():
        for f in item['fields']: note(f['type'])
    for item in unions.values():
        for case in item['cases']:
            for f in case['fields']: note(f['type'])
    for name in enums:
        if name not in needed_enums: continue
        for reverse in (False,True):
            direction = 'lower' if reverse else 'lift'
            src,dst = (canonical(name),'N.'+name) if reverse else ('N.'+name,canonical(name))
            lines += [f'export function {direction}{name}(value: {src}): {dst} {{', '  switch (value) {']
            for v in enums[name]['values']:
                n = v['name']; a,b = (json.dumps(n),f'N.{name}.{n}') if reverse else (f'N.{name}.{n}',json.dumps(n))
                lines += [f'    case {a}: return {b};']
            lines += ['    default: return unexpected(value);','  }','}']
    def convert(t,expr,reverse):
        direction = 'lower' if reverse else 'lift'
        if isinstance(t,dict): return f'{expr}.map((item) => {convert(t["array"],"item",reverse)})'
        if t in fixed:
            f = t[0].lower()+t[1:]
            return f'C.{f}({expr})'
        if t == 'u128': return f'{direction}WideCounter({expr})'
        if t == 'safeUint': return f'{direction}SafeUint({expr})'
        if t == 'safeInt': return f'{direction}SafeInt({expr})'
        if t in records or t in unions or t in enums: return f'{direction}{t}({expr})'
        if t == 'ResourceStream': return f'resources({expr})'
        return expr
    def fields(fs, prefix, reverse):
        result=[]
        for f in fs:
            n=f['name'];expr=f'{prefix}.{n}';v=convert(f['type'],expr,reverse)
            result.append(f'...({expr} === undefined ? {{}} : {{ {n}: {v} }})' if f.get('optional') else f'{n}: {v}')
        return '{ '+', '.join(result)+' }'
    for name,item in records.items():
        for reverse in (False,True):
            if not reverse and name in input_only: continue
            direction='lower' if reverse else 'lift'
            src,dst=(canonical(name),'N.'+name) if reverse else ('N.'+name,canonical(name))
            lines += [f'export function {direction}{name}(value: {src}): {dst} {{',f'  return {fields(item["fields"],"value",reverse)};','}']
    for name,item in unions.items():
        flat=all(not c['fields'] for c in item['cases'])
        for reverse in (False,True):
            if not reverse and name in input_only: continue
            if reverse and name in ('ApplicationEvent','DiagnosticEvent'): continue
            direction='lower' if reverse else 'lift'
            src,dst=(canonical(name),'N.'+name) if reverse else ('N.'+name,canonical(name))
            resources=', resources: ResourceFactory' if name=='ApplicationEvent' else ''
            lines += [f'export function {direction}{name}(value: {src}{resources}): {dst} {{',f'  switch (value{ ".tag" if reverse or not flat else ""}) {{']
            for case in item['cases']:
                c=case['name'];fs=case['fields']
                match=json.dumps(c) if reverse else f'N.{name}{"" if flat else "_Tags"}.{c}'
                if reverse:
                    value = f'N.{name}.{c}' if flat else f'N.{name}.{c}.new(' + (fields(fs,'value.data',True) if fs else '') + ')'
                    if name=='CommandSettlement':
                        f=fs[0];value=f'N.{name}.{c}.new({{ {f["name"]}: {convert(f["type"],"value.data",True)} }})'
                else:
                    value='{ tag: '+json.dumps(c)+((', data: '+fields(fs,'value.inner',False)) if fs else ', data: undefined')+' }'
                    if name=='CommandSettlement':
                        f=fs[0];value='{ tag: '+json.dumps(c)+', data: '+convert(f['type'],f'value.inner.{f["name"]}',False)+' }'
                lines += [f'    case {match}: return {value};']
            lines += ['    default: return unexpected(value);','  }','}']
    return '\n'.join(lines)+'\n'


def uniffi_config():
    return '''# Generated by tools/repo/generate-host-contract.py. Do not edit.
[bindings.typescript]
strictTypeChecking = true
strictByteArrays = true

[bindings.swift]
module_name = "PrnsHostBindings"

[bindings.kotlin]
package_name = "rs.reticulum.prns.host.bindings"
'''
