// Generated by tools/repo/generate-app-uniffi-host.py. Do not edit.
// Canonical source: prns-host/schema/host-contract-v1.json.

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SafeUint(pub u64);
uniffi::custom_type!(SafeUint, u64, {
    lower: |value| value.0,
    try_lift: |value| {
        if value > 9_007_199_254_740_991 {
            return Err(uniffi::deps::anyhow::anyhow!("safeUint exceeds the canonical JS integer range"));
        }
        Ok(SafeUint(value))
    },
});

use prns_host::DestinationHash;
uniffi::custom_type!(DestinationHash, Vec<u8>, {
    remote,
    lower: |value| value.into_bytes().to_vec(),
    try_lift: |value| Ok(DestinationHash::new(value.try_into().map_err(|_| uniffi::deps::anyhow::anyhow!("expected 16 bytes"))?)),
});

use prns_host::IdentityHash;
uniffi::custom_type!(IdentityHash, Vec<u8>, {
    remote,
    lower: |value| value.into_bytes().to_vec(),
    try_lift: |value| Ok(IdentityHash::new(value.try_into().map_err(|_| uniffi::deps::anyhow::anyhow!("expected 16 bytes"))?)),
});

use prns_host::InterfaceId;
uniffi::custom_type!(InterfaceId, Vec<u8>, {
    remote,
    lower: |value| value.into_bytes().to_vec(),
    try_lift: |value| Ok(InterfaceId::new(value.try_into().map_err(|_| uniffi::deps::anyhow::anyhow!("expected 8 bytes"))?)),
});

use prns_host::BackendKind;
uniffi::custom_type!(BackendKind, String, {
    remote,
    lower: |value| value.contract_name().to_owned(),
    try_lift: |value| match value.as_str() {
        "Native" => Ok(BackendKind::Native),
        "Browser" => Ok(BackendKind::Browser),
        "Cooperative" => Ok(BackendKind::Cooperative),
        _ => Err(uniffi::deps::anyhow::anyhow!("unknown canonical enum value")),
    },
});

use prns_host::Capability;
uniffi::custom_type!(Capability, String, {
    remote,
    lower: |value| value.contract_name().to_owned(),
    try_lift: |value| match value.as_str() {
        "Loopback" => Ok(Capability::Loopback),
        "TcpClient" => Ok(Capability::TcpClient),
        "TcpServer" => Ok(Capability::TcpServer),
        "Udp" => Ok(Capability::Udp),
        "Serial" => Ok(Capability::Serial),
        "Usb" => Ok(Capability::Usb),
        "Bluetooth" => Ok(Capability::Bluetooth),
        "Wifi" => Ok(Capability::Wifi),
        "WebSocket" => Ok(Capability::WebSocket),
        "BrowserRendezvous" => Ok(Capability::BrowserRendezvous),
        "I2p" => Ok(Capability::I2p),
        "Weave" => Ok(Capability::Weave),
        "SuppliedPipe" => Ok(Capability::SuppliedPipe),
        _ => Err(uniffi::deps::anyhow::anyhow!("unknown canonical enum value")),
    },
});

use prns_host::InterfaceKind;
uniffi::custom_type!(InterfaceKind, String, {
    remote,
    lower: |value| value.contract_name().to_owned(),
    try_lift: |value| match value.as_str() {
        "AutoLan" => Ok(InterfaceKind::AutoLan),
        "TcpClient" => Ok(InterfaceKind::TcpClient),
        "TcpServer" => Ok(InterfaceKind::TcpServer),
        "Udp" => Ok(InterfaceKind::Udp),
        "Serial" => Ok(InterfaceKind::Serial),
        "Kiss" => Ok(InterfaceKind::Kiss),
        "Ax25Kiss" => Ok(InterfaceKind::Ax25Kiss),
        "RNode" => Ok(InterfaceKind::RNode),
        "MultiRNode" => Ok(InterfaceKind::MultiRNode),
        "Pipe" => Ok(InterfaceKind::Pipe),
        "BackboneClient" => Ok(InterfaceKind::BackboneClient),
        "BackboneServer" => Ok(InterfaceKind::BackboneServer),
        "I2p" => Ok(InterfaceKind::I2p),
        "Weave" => Ok(InterfaceKind::Weave),
        "AutomaticUsb" => Ok(InterfaceKind::AutomaticUsb),
        "AutomaticBluetoothLe" => Ok(InterfaceKind::AutomaticBluetoothLe),
        "WebSocketClient" => Ok(InterfaceKind::WebSocketClient),
        "WebSocketServer" => Ok(InterfaceKind::WebSocketServer),
        "BrowserRendezvous" => Ok(InterfaceKind::BrowserRendezvous),
        _ => Err(uniffi::deps::anyhow::anyhow!("unknown canonical enum value")),
    },
});

use prns_host::InterfaceHealth;
uniffi::custom_type!(InterfaceHealth, String, {
    remote,
    lower: |value| value.contract_name().to_owned(),
    try_lift: |value| match value.as_str() {
        "Initializing" => Ok(InterfaceHealth::Initializing),
        "Connected" => Ok(InterfaceHealth::Connected),
        "Degraded" => Ok(InterfaceHealth::Degraded),
        "Reconnecting" => Ok(InterfaceHealth::Reconnecting),
        "Failed" => Ok(InterfaceHealth::Failed),
        "Disconnected" => Ok(InterfaceHealth::Disconnected),
        "Disabled" => Ok(InterfaceHealth::Disabled),
        "Unknown" => Ok(InterfaceHealth::Unknown),
        _ => Err(uniffi::deps::anyhow::anyhow!("unknown canonical enum value")),
    },
});

use prns_host::PersistenceFlushCause;
uniffi::custom_type!(PersistenceFlushCause, String, {
    remote,
    lower: |value| value.contract_name().to_owned(),
    try_lift: |value| match value.as_str() {
        "Startup" => Ok(PersistenceFlushCause::Startup),
        "Interval" => Ok(PersistenceFlushCause::Interval),
        "RouteChange" => Ok(PersistenceFlushCause::RouteChange),
        "RatchetRotation" => Ok(PersistenceFlushCause::RatchetRotation),
        "Shutdown" => Ok(PersistenceFlushCause::Shutdown),
        _ => Err(uniffi::deps::anyhow::anyhow!("unknown canonical enum value")),
    },
});

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Record)]
pub struct BackendInfoTransport {
    pub backend: BackendKind,
    pub capabilities: Vec<Capability>,
    pub interface_kinds: Vec<InterfaceKind>,
}
impl From<prns_host::BackendInfo> for BackendInfoTransport {
    fn from(value: prns_host::BackendInfo) -> Self {
        Self {
            backend: value.backend(),
            capabilities: value.capabilities().collect::<Vec<_>>(),
            interface_kinds: value.interface_kinds().collect::<Vec<_>>(),
        }
    }
}
impl From<BackendInfoTransport> for prns_host::BackendInfo {
    fn from(value: BackendInfoTransport) -> Self {
        Self::new(value.backend, value.capabilities, value.interface_kinds)
    }
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Record)]
pub struct InterfaceSnapshotTransport {
    pub interface_id: InterfaceId,
    pub name: Option<String>,
    pub kind: Option<InterfaceKind>,
    pub health: InterfaceHealth,
    pub failure_detail: Option<String>,
    pub rx_bytes: u64,
    pub tx_bytes: u64,
    pub rx_bps: Option<SafeUint>,
    pub tx_bps: Option<SafeUint>,
    pub route_count: u32,
    pub link_count: u32,
    pub transported_link_count: u32,
}
impl From<prns_host::InterfaceSnapshot> for InterfaceSnapshotTransport {
    fn from(value: prns_host::InterfaceSnapshot) -> Self {
        Self {
            interface_id: value.interface_id,
            name: value.name,
            kind: value.kind,
            health: value.health,
            failure_detail: value.failure_detail,
            rx_bytes: value.rx_bytes,
            tx_bytes: value.tx_bytes,
            rx_bps: value.rx_bps.map(SafeUint),
            tx_bps: value.tx_bps.map(SafeUint),
            route_count: value.route_count,
            link_count: value.link_count,
            transported_link_count: value.transported_link_count,
        }
    }
}
impl From<InterfaceSnapshotTransport> for prns_host::InterfaceSnapshot {
    fn from(value: InterfaceSnapshotTransport) -> Self {
        Self {
            interface_id: value.interface_id,
            name: value.name,
            kind: value.kind,
            health: value.health,
            failure_detail: value.failure_detail,
            rx_bytes: value.rx_bytes,
            tx_bytes: value.tx_bytes,
            rx_bps: value.rx_bps.map(|value| value.0),
            tx_bps: value.tx_bps.map(|value| value.0),
            route_count: value.route_count,
            link_count: value.link_count,
            transported_link_count: value.transported_link_count,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Record)]
pub struct RouteSnapshotTransport {
    pub destination: DestinationHash,
    pub hops: u8,
    pub via_identity: Option<IdentityHash>,
    pub interface_id: InterfaceId,
    pub learned_at_millis: SafeUint,
    pub last_route_activity_at_millis: SafeUint,
    pub expires_at_millis: SafeUint,
}
impl From<prns_host::RouteSnapshot> for RouteSnapshotTransport {
    fn from(value: prns_host::RouteSnapshot) -> Self {
        Self {
            destination: value.destination,
            hops: value.hops,
            via_identity: value.via_identity,
            interface_id: value.interface_id,
            learned_at_millis: SafeUint(value.learned_at_millis),
            last_route_activity_at_millis: SafeUint(value.last_route_activity_at_millis),
            expires_at_millis: SafeUint(value.expires_at_millis),
        }
    }
}
impl From<RouteSnapshotTransport> for prns_host::RouteSnapshot {
    fn from(value: RouteSnapshotTransport) -> Self {
        Self {
            destination: value.destination,
            hops: value.hops,
            via_identity: value.via_identity,
            interface_id: value.interface_id,
            learned_at_millis: value.learned_at_millis.0,
            last_route_activity_at_millis: value.last_route_activity_at_millis.0,
            expires_at_millis: value.expires_at_millis.0,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Record)]
pub struct DestinationIdentitySnapshotTransport {
    pub destination: DestinationHash,
    pub identity: IdentityHash,
}
impl From<prns_host::DestinationIdentitySnapshot> for DestinationIdentitySnapshotTransport {
    fn from(value: prns_host::DestinationIdentitySnapshot) -> Self {
        Self {
            destination: value.destination,
            identity: value.identity,
        }
    }
}
impl From<DestinationIdentitySnapshotTransport> for prns_host::DestinationIdentitySnapshot {
    fn from(value: DestinationIdentitySnapshotTransport) -> Self {
        Self {
            destination: value.destination,
            identity: value.identity,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Record)]
pub struct RuntimeHealthSnapshotTransport {
    pub running: bool,
    pub uptime_millis: SafeUint,
    pub interface_count: u32,
    pub online_interface_count: u32,
    pub route_count: u32,
    pub link_count: u32,
    pub transported_link_count: u32,
    pub rx_bytes: u64,
    pub tx_bytes: u64,
    pub rx_bps: SafeUint,
    pub tx_bps: SafeUint,
}
impl From<prns_host::RuntimeHealthSnapshot> for RuntimeHealthSnapshotTransport {
    fn from(value: prns_host::RuntimeHealthSnapshot) -> Self {
        Self {
            running: value.running,
            uptime_millis: SafeUint(value.uptime_millis),
            interface_count: value.interface_count,
            online_interface_count: value.online_interface_count,
            route_count: value.route_count,
            link_count: value.link_count,
            transported_link_count: value.transported_link_count,
            rx_bytes: value.rx_bytes,
            tx_bytes: value.tx_bytes,
            rx_bps: SafeUint(value.rx_bps),
            tx_bps: SafeUint(value.tx_bps),
        }
    }
}
impl From<RuntimeHealthSnapshotTransport> for prns_host::RuntimeHealthSnapshot {
    fn from(value: RuntimeHealthSnapshotTransport) -> Self {
        Self {
            running: value.running,
            uptime_millis: value.uptime_millis.0,
            interface_count: value.interface_count,
            online_interface_count: value.online_interface_count,
            route_count: value.route_count,
            link_count: value.link_count,
            transported_link_count: value.transported_link_count,
            rx_bytes: value.rx_bytes,
            tx_bytes: value.tx_bytes,
            rx_bps: value.rx_bps.0,
            tx_bps: value.tx_bps.0,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Record)]
pub struct PersistenceSnapshotTransport {
    pub persistent: bool,
    pub restored: bool,
    pub last_flush_cause: Option<PersistenceFlushCause>,
    pub last_failure_detail: Option<String>,
}
impl From<prns_host::PersistenceSnapshot> for PersistenceSnapshotTransport {
    fn from(value: prns_host::PersistenceSnapshot) -> Self {
        Self {
            persistent: value.persistent,
            restored: value.restored,
            last_flush_cause: value.last_flush_cause,
            last_failure_detail: value.last_failure_detail,
        }
    }
}
impl From<PersistenceSnapshotTransport> for prns_host::PersistenceSnapshot {
    fn from(value: PersistenceSnapshotTransport) -> Self {
        Self {
            persistent: value.persistent,
            restored: value.restored,
            last_flush_cause: value.last_flush_cause,
            last_failure_detail: value.last_failure_detail,
        }
    }
}

#[derive(Clone, Debug, PartialEq, Eq, uniffi::Record)]
pub struct HostSnapshotTransport {
    pub revision: u64,
    pub backend: BackendInfoTransport,
    pub interfaces: Vec<InterfaceSnapshotTransport>,
    pub routes: Vec<RouteSnapshotTransport>,
    pub active_link_count: u32,
    pub destination_identities: Vec<DestinationIdentitySnapshotTransport>,
    pub runtime: RuntimeHealthSnapshotTransport,
    pub persistence: PersistenceSnapshotTransport,
}
impl From<prns_host::HostSnapshot> for HostSnapshotTransport {
    fn from(value: prns_host::HostSnapshot) -> Self {
        Self {
            revision: value.revision,
            backend: value.backend.into(),
            interfaces: value
                .interfaces
                .into_iter()
                .map(|value| value.into())
                .collect::<Vec<_>>(),
            routes: value
                .routes
                .into_iter()
                .map(|value| value.into())
                .collect::<Vec<_>>(),
            active_link_count: value.active_link_count,
            destination_identities: value
                .destination_identities
                .into_iter()
                .map(|value| value.into())
                .collect::<Vec<_>>(),
            runtime: value.runtime.into(),
            persistence: value.persistence.into(),
        }
    }
}
impl From<HostSnapshotTransport> for prns_host::HostSnapshot {
    fn from(value: HostSnapshotTransport) -> Self {
        Self {
            revision: value.revision,
            backend: value.backend.into(),
            interfaces: value
                .interfaces
                .into_iter()
                .map(|value| value.into())
                .collect::<Vec<_>>(),
            routes: value
                .routes
                .into_iter()
                .map(|value| value.into())
                .collect::<Vec<_>>(),
            active_link_count: value.active_link_count,
            destination_identities: value
                .destination_identities
                .into_iter()
                .map(|value| value.into())
                .collect::<Vec<_>>(),
            runtime: value.runtime.into(),
            persistence: value.persistence.into(),
        }
    }
}

type CanonicalHostSnapshot = Box<prns_host::HostSnapshot>;
uniffi::custom_type!(CanonicalHostSnapshot, HostSnapshotTransport, {
    remote,
    lower: |value| (*value).into(),
    try_lift: |value| Ok(Box::new(value.into())),
});
