// Generated by tools/repo/generate-host-contract.py. Do not edit.
import * as C from "personal-rns/contract";
import * as N from "./prns_host_uniffi";
export type ResourceFactory = (value: N.ResourceDescriptor) => C.ResourceStream;
export const HOST_SEMANTIC_FINGERPRINT = "b5ca02be1ea5d61771f3a75eacb4d44447f99754adbeb02b6cd98537ed2fa239";
export function liftSafeUint(value: bigint): number {
  if (value < 0n || value > 9_007_199_254_740_991n) throw new RangeError("safeUint outside exact JS integer range");
  return Number(value);
}
export function lowerSafeUint(value: number): bigint {
  if (!Number.isSafeInteger(value) || value < 0) throw new RangeError("expected a non-negative safe integer");
  return BigInt(value);
}
export function liftSafeInt(value: bigint): number {
  if (value < -9_007_199_254_740_991n || value > 9_007_199_254_740_991n) throw new RangeError("safeInt outside exact JS integer range");
  return Number(value);
}
export function lowerSafeInt(value: number): bigint {
  if (!Number.isSafeInteger(value)) throw new RangeError("expected a safe integer");
  return BigInt(value);
}
export function liftWideCounter(value: N.WideCounter): bigint {
  if (value.high < 0n || value.high > 0xffff_ffff_ffff_ffffn || value.low < 0n || value.low > 0xffff_ffff_ffff_ffffn) throw new RangeError("invalid u128 limbs");
  return (value.high << 64n) | value.low;
}
export function lowerWideCounter(value: bigint): N.WideCounter {
  if (value < 0n || value > (1n << 128n) - 1n) throw new RangeError("u128 out of range");
  return { high: value >> 64n, low: value & 0xffff_ffff_ffff_ffffn };
}
function unexpected(value: never): never { throw new TypeError(`unknown host contract case: ${String(value)}`); }

export function liftBackendKind(value: N.BackendKind): C.BackendKind {
  switch (value) {
    case N.BackendKind.Native: return "Native";
    case N.BackendKind.Browser: return "Browser";
    case N.BackendKind.Cooperative: return "Cooperative";
    default: return unexpected(value);
  }
}
export function lowerBackendKind(value: C.BackendKind): N.BackendKind {
  switch (value) {
    case "Native": return N.BackendKind.Native;
    case "Browser": return N.BackendKind.Browser;
    case "Cooperative": return N.BackendKind.Cooperative;
    default: return unexpected(value);
  }
}
export function liftCapability(value: N.Capability): C.CapabilityName {
  switch (value) {
    case N.Capability.Loopback: return "Loopback";
    case N.Capability.TcpClient: return "TcpClient";
    case N.Capability.TcpServer: return "TcpServer";
    case N.Capability.Udp: return "Udp";
    case N.Capability.Serial: return "Serial";
    case N.Capability.Usb: return "Usb";
    case N.Capability.Bluetooth: return "Bluetooth";
    case N.Capability.Wifi: return "Wifi";
    case N.Capability.WebSocket: return "WebSocket";
    case N.Capability.BrowserRendezvous: return "BrowserRendezvous";
    case N.Capability.I2p: return "I2p";
    case N.Capability.Weave: return "Weave";
    case N.Capability.SuppliedPipe: return "SuppliedPipe";
    default: return unexpected(value);
  }
}
export function lowerCapability(value: C.CapabilityName): N.Capability {
  switch (value) {
    case "Loopback": return N.Capability.Loopback;
    case "TcpClient": return N.Capability.TcpClient;
    case "TcpServer": return N.Capability.TcpServer;
    case "Udp": return N.Capability.Udp;
    case "Serial": return N.Capability.Serial;
    case "Usb": return N.Capability.Usb;
    case "Bluetooth": return N.Capability.Bluetooth;
    case "Wifi": return N.Capability.Wifi;
    case "WebSocket": return N.Capability.WebSocket;
    case "BrowserRendezvous": return N.Capability.BrowserRendezvous;
    case "I2p": return N.Capability.I2p;
    case "Weave": return N.Capability.Weave;
    case "SuppliedPipe": return N.Capability.SuppliedPipe;
    default: return unexpected(value);
  }
}
export function liftInterfaceKind(value: N.InterfaceKind): C.InterfaceKind {
  switch (value) {
    case N.InterfaceKind.AutoLan: return "AutoLan";
    case N.InterfaceKind.TcpClient: return "TcpClient";
    case N.InterfaceKind.TcpServer: return "TcpServer";
    case N.InterfaceKind.Udp: return "Udp";
    case N.InterfaceKind.Serial: return "Serial";
    case N.InterfaceKind.Kiss: return "Kiss";
    case N.InterfaceKind.Ax25Kiss: return "Ax25Kiss";
    case N.InterfaceKind.RNode: return "RNode";
    case N.InterfaceKind.MultiRNode: return "MultiRNode";
    case N.InterfaceKind.Pipe: return "Pipe";
    case N.InterfaceKind.BackboneClient: return "BackboneClient";
    case N.InterfaceKind.BackboneServer: return "BackboneServer";
    case N.InterfaceKind.I2p: return "I2p";
    case N.InterfaceKind.Weave: return "Weave";
    case N.InterfaceKind.AutomaticUsb: return "AutomaticUsb";
    case N.InterfaceKind.AutomaticBluetoothLe: return "AutomaticBluetoothLe";
    case N.InterfaceKind.WebSocketClient: return "WebSocketClient";
    case N.InterfaceKind.WebSocketServer: return "WebSocketServer";
    case N.InterfaceKind.BrowserRendezvous: return "BrowserRendezvous";
    default: return unexpected(value);
  }
}
export function lowerInterfaceKind(value: C.InterfaceKind): N.InterfaceKind {
  switch (value) {
    case "AutoLan": return N.InterfaceKind.AutoLan;
    case "TcpClient": return N.InterfaceKind.TcpClient;
    case "TcpServer": return N.InterfaceKind.TcpServer;
    case "Udp": return N.InterfaceKind.Udp;
    case "Serial": return N.InterfaceKind.Serial;
    case "Kiss": return N.InterfaceKind.Kiss;
    case "Ax25Kiss": return N.InterfaceKind.Ax25Kiss;
    case "RNode": return N.InterfaceKind.RNode;
    case "MultiRNode": return N.InterfaceKind.MultiRNode;
    case "Pipe": return N.InterfaceKind.Pipe;
    case "BackboneClient": return N.InterfaceKind.BackboneClient;
    case "BackboneServer": return N.InterfaceKind.BackboneServer;
    case "I2p": return N.InterfaceKind.I2p;
    case "Weave": return N.InterfaceKind.Weave;
    case "AutomaticUsb": return N.InterfaceKind.AutomaticUsb;
    case "AutomaticBluetoothLe": return N.InterfaceKind.AutomaticBluetoothLe;
    case "WebSocketClient": return N.InterfaceKind.WebSocketClient;
    case "WebSocketServer": return N.InterfaceKind.WebSocketServer;
    case "BrowserRendezvous": return N.InterfaceKind.BrowserRendezvous;
    default: return unexpected(value);
  }
}
export function liftInterfaceMode(value: N.InterfaceMode): C.InterfaceMode {
  switch (value) {
    case N.InterfaceMode.Full: return "Full";
    case N.InterfaceMode.PointToPoint: return "PointToPoint";
    case N.InterfaceMode.AccessPoint: return "AccessPoint";
    case N.InterfaceMode.Roaming: return "Roaming";
    case N.InterfaceMode.Boundary: return "Boundary";
    case N.InterfaceMode.Gateway: return "Gateway";
    case N.InterfaceMode.Internal: return "Internal";
    default: return unexpected(value);
  }
}
export function lowerInterfaceMode(value: C.InterfaceMode): N.InterfaceMode {
  switch (value) {
    case "Full": return N.InterfaceMode.Full;
    case "PointToPoint": return N.InterfaceMode.PointToPoint;
    case "AccessPoint": return N.InterfaceMode.AccessPoint;
    case "Roaming": return N.InterfaceMode.Roaming;
    case "Boundary": return N.InterfaceMode.Boundary;
    case "Gateway": return N.InterfaceMode.Gateway;
    case "Internal": return N.InterfaceMode.Internal;
    default: return unexpected(value);
  }
}
export function liftWebSocketFramingSelection(value: N.WebSocketFramingSelection): C.WebSocketFramingSelection {
  switch (value) {
    case N.WebSocketFramingSelection.RawPacket: return "RawPacket";
    case N.WebSocketFramingSelection.Hdlc: return "Hdlc";
    case N.WebSocketFramingSelection.Kiss: return "Kiss";
    case N.WebSocketFramingSelection.Auto: return "Auto";
    default: return unexpected(value);
  }
}
export function lowerWebSocketFramingSelection(value: C.WebSocketFramingSelection): N.WebSocketFramingSelection {
  switch (value) {
    case "RawPacket": return N.WebSocketFramingSelection.RawPacket;
    case "Hdlc": return N.WebSocketFramingSelection.Hdlc;
    case "Kiss": return N.WebSocketFramingSelection.Kiss;
    case "Auto": return N.WebSocketFramingSelection.Auto;
    default: return unexpected(value);
  }
}
export function liftInterfaceHealth(value: N.InterfaceHealth): C.InterfaceHealth {
  switch (value) {
    case N.InterfaceHealth.Initializing: return "Initializing";
    case N.InterfaceHealth.Connected: return "Connected";
    case N.InterfaceHealth.Degraded: return "Degraded";
    case N.InterfaceHealth.Reconnecting: return "Reconnecting";
    case N.InterfaceHealth.Failed: return "Failed";
    case N.InterfaceHealth.Disconnected: return "Disconnected";
    case N.InterfaceHealth.Disabled: return "Disabled";
    case N.InterfaceHealth.Unknown: return "Unknown";
    default: return unexpected(value);
  }
}
export function lowerInterfaceHealth(value: C.InterfaceHealth): N.InterfaceHealth {
  switch (value) {
    case "Initializing": return N.InterfaceHealth.Initializing;
    case "Connected": return N.InterfaceHealth.Connected;
    case "Degraded": return N.InterfaceHealth.Degraded;
    case "Reconnecting": return N.InterfaceHealth.Reconnecting;
    case "Failed": return N.InterfaceHealth.Failed;
    case "Disconnected": return N.InterfaceHealth.Disconnected;
    case "Disabled": return N.InterfaceHealth.Disabled;
    case "Unknown": return N.InterfaceHealth.Unknown;
    default: return unexpected(value);
  }
}
export function liftDiscoveryScope(value: N.DiscoveryScope): C.DiscoveryScope {
  switch (value) {
    case N.DiscoveryScope.Link: return "Link";
    case N.DiscoveryScope.Admin: return "Admin";
    case N.DiscoveryScope.Site: return "Site";
    case N.DiscoveryScope.Organization: return "Organization";
    case N.DiscoveryScope.Global: return "Global";
    default: return unexpected(value);
  }
}
export function lowerDiscoveryScope(value: C.DiscoveryScope): N.DiscoveryScope {
  switch (value) {
    case "Link": return N.DiscoveryScope.Link;
    case "Admin": return N.DiscoveryScope.Admin;
    case "Site": return N.DiscoveryScope.Site;
    case "Organization": return N.DiscoveryScope.Organization;
    case "Global": return N.DiscoveryScope.Global;
    default: return unexpected(value);
  }
}
export function liftMulticastAddressType(value: N.MulticastAddressType): C.MulticastAddressType {
  switch (value) {
    case N.MulticastAddressType.Temporary: return "Temporary";
    case N.MulticastAddressType.Permanent: return "Permanent";
    default: return unexpected(value);
  }
}
export function lowerMulticastAddressType(value: C.MulticastAddressType): N.MulticastAddressType {
  switch (value) {
    case "Temporary": return N.MulticastAddressType.Temporary;
    case "Permanent": return N.MulticastAddressType.Permanent;
    default: return unexpected(value);
  }
}
export function liftSerialDataBits(value: N.SerialDataBits): C.SerialDataBits {
  switch (value) {
    case N.SerialDataBits.Five: return "Five";
    case N.SerialDataBits.Six: return "Six";
    case N.SerialDataBits.Seven: return "Seven";
    case N.SerialDataBits.Eight: return "Eight";
    default: return unexpected(value);
  }
}
export function lowerSerialDataBits(value: C.SerialDataBits): N.SerialDataBits {
  switch (value) {
    case "Five": return N.SerialDataBits.Five;
    case "Six": return N.SerialDataBits.Six;
    case "Seven": return N.SerialDataBits.Seven;
    case "Eight": return N.SerialDataBits.Eight;
    default: return unexpected(value);
  }
}
export function liftSerialParity(value: N.SerialParity): C.SerialParity {
  switch (value) {
    case N.SerialParity.None: return "None";
    case N.SerialParity.Even: return "Even";
    case N.SerialParity.Odd: return "Odd";
    default: return unexpected(value);
  }
}
export function lowerSerialParity(value: C.SerialParity): N.SerialParity {
  switch (value) {
    case "None": return N.SerialParity.None;
    case "Even": return N.SerialParity.Even;
    case "Odd": return N.SerialParity.Odd;
    default: return unexpected(value);
  }
}
export function liftSerialStopBits(value: N.SerialStopBits): C.SerialStopBits {
  switch (value) {
    case N.SerialStopBits.One: return "One";
    case N.SerialStopBits.Two: return "Two";
    default: return unexpected(value);
  }
}
export function lowerSerialStopBits(value: C.SerialStopBits): N.SerialStopBits {
  switch (value) {
    case "One": return N.SerialStopBits.One;
    case "Two": return N.SerialStopBits.Two;
    default: return unexpected(value);
  }
}
export function liftHostRole(value: N.HostRole): C.HostRoleName {
  switch (value) {
    case N.HostRole.Endpoint: return "Endpoint";
    case N.HostRole.Transport: return "Transport";
    default: return unexpected(value);
  }
}
export function lowerHostRole(value: C.HostRoleName): N.HostRole {
  switch (value) {
    case "Endpoint": return N.HostRole.Endpoint;
    case "Transport": return N.HostRole.Transport;
    default: return unexpected(value);
  }
}
export function liftRequestPolicy(value: N.RequestPolicy): C.RequestPolicy {
  switch (value) {
    case N.RequestPolicy.AllowNone: return "AllowNone";
    case N.RequestPolicy.AllowAll: return "AllowAll";
    case N.RequestPolicy.AllowList: return "AllowList";
    default: return unexpected(value);
  }
}
export function lowerRequestPolicy(value: C.RequestPolicy): N.RequestPolicy {
  switch (value) {
    case "AllowNone": return N.RequestPolicy.AllowNone;
    case "AllowAll": return N.RequestPolicy.AllowAll;
    case "AllowList": return N.RequestPolicy.AllowList;
    default: return unexpected(value);
  }
}
export function liftDeliveryEvidenceKind(value: N.DeliveryEvidenceKind): C.DeliveryEvidenceKind {
  switch (value) {
    case N.DeliveryEvidenceKind.ExplicitProof: return "ExplicitProof";
    case N.DeliveryEvidenceKind.ImplicitProof: return "ImplicitProof";
    case N.DeliveryEvidenceKind.Response: return "Response";
    default: return unexpected(value);
  }
}
export function lowerDeliveryEvidenceKind(value: C.DeliveryEvidenceKind): N.DeliveryEvidenceKind {
  switch (value) {
    case "ExplicitProof": return N.DeliveryEvidenceKind.ExplicitProof;
    case "ImplicitProof": return N.DeliveryEvidenceKind.ImplicitProof;
    case "Response": return N.DeliveryEvidenceKind.Response;
    default: return unexpected(value);
  }
}
export function liftStopReason(value: N.StopReason): C.StopReason {
  switch (value) {
    case N.StopReason.Requested: return "Requested";
    case N.StopReason.BackendExited: return "BackendExited";
    default: return unexpected(value);
  }
}
export function lowerStopReason(value: C.StopReason): N.StopReason {
  switch (value) {
    case "Requested": return N.StopReason.Requested;
    case "BackendExited": return N.StopReason.BackendExited;
    default: return unexpected(value);
  }
}
export function liftLinkClosedReason(value: N.LinkClosedReason): C.LinkClosedReason {
  switch (value) {
    case N.LinkClosedReason.Timeout: return "Timeout";
    case N.LinkClosedReason.PeerClosed: return "PeerClosed";
    case N.LinkClosedReason.MalformedRtt: return "MalformedRtt";
    case N.LinkClosedReason.LocallyClosed: return "LocallyClosed";
    default: return unexpected(value);
  }
}
export function lowerLinkClosedReason(value: C.LinkClosedReason): N.LinkClosedReason {
  switch (value) {
    case "Timeout": return N.LinkClosedReason.Timeout;
    case "PeerClosed": return N.LinkClosedReason.PeerClosed;
    case "MalformedRtt": return N.LinkClosedReason.MalformedRtt;
    case "LocallyClosed": return N.LinkClosedReason.LocallyClosed;
    default: return unexpected(value);
  }
}
export function liftPersistenceFlushCause(value: N.PersistenceFlushCause): C.PersistenceFlushCause {
  switch (value) {
    case N.PersistenceFlushCause.Startup: return "Startup";
    case N.PersistenceFlushCause.Interval: return "Interval";
    case N.PersistenceFlushCause.RouteChange: return "RouteChange";
    case N.PersistenceFlushCause.RatchetRotation: return "RatchetRotation";
    case N.PersistenceFlushCause.Shutdown: return "Shutdown";
    default: return unexpected(value);
  }
}
export function lowerPersistenceFlushCause(value: C.PersistenceFlushCause): N.PersistenceFlushCause {
  switch (value) {
    case "Startup": return N.PersistenceFlushCause.Startup;
    case "Interval": return N.PersistenceFlushCause.Interval;
    case "RouteChange": return N.PersistenceFlushCause.RouteChange;
    case "RatchetRotation": return N.PersistenceFlushCause.RatchetRotation;
    case "Shutdown": return N.PersistenceFlushCause.Shutdown;
    default: return unexpected(value);
  }
}
export function liftPersistenceFlushTarget(value: N.PersistenceFlushTarget): C.PersistenceFlushTarget {
  switch (value) {
    case N.PersistenceFlushTarget.RoutingState: return "RoutingState";
    case N.PersistenceFlushTarget.Ratchets: return "Ratchets";
    default: return unexpected(value);
  }
}
export function lowerPersistenceFlushTarget(value: C.PersistenceFlushTarget): N.PersistenceFlushTarget {
  switch (value) {
    case "RoutingState": return N.PersistenceFlushTarget.RoutingState;
    case "Ratchets": return N.PersistenceFlushTarget.Ratchets;
    default: return unexpected(value);
  }
}
export function liftDestinationName(value: N.DestinationName): C.DestinationName {
  return { appName: value.appName, aspects: value.aspects.map((item) => item) };
}
export function lowerDestinationName(value: C.DestinationName): N.DestinationName {
  return { appName: value.appName, aspects: value.aspects.map((item) => item) };
}
export function liftRequestHandlerConfig(value: N.RequestHandlerConfig): C.RequestHandlerConfig {
  return { path: value.path, policy: liftRequestPolicy(value.policy) };
}
export function lowerRequestHandlerConfig(value: C.RequestHandlerConfig): N.RequestHandlerConfig {
  return { path: value.path, policy: lowerRequestPolicy(value.policy) };
}
export function liftSerialLineConfig(value: N.SerialLineConfig): C.SerialLineConfig {
  return { baud: value.baud, dataBits: liftSerialDataBits(value.dataBits), parity: liftSerialParity(value.parity), stopBits: liftSerialStopBits(value.stopBits) };
}
export function lowerSerialLineConfig(value: C.SerialLineConfig): N.SerialLineConfig {
  return { baud: value.baud, dataBits: lowerSerialDataBits(value.dataBits), parity: lowerSerialParity(value.parity), stopBits: lowerSerialStopBits(value.stopBits) };
}
export function liftRNodeRadioConfig(value: N.RNodeRadioConfig): C.RNodeRadioConfig {
  return { frequencyHz: liftSafeUint(value.frequencyHz), bandwidthHz: value.bandwidthHz, txPowerDbm: value.txPowerDbm, spreadingFactor: value.spreadingFactor, codingRate: value.codingRate };
}
export function lowerRNodeRadioConfig(value: C.RNodeRadioConfig): N.RNodeRadioConfig {
  return { frequencyHz: lowerSafeUint(value.frequencyHz), bandwidthHz: value.bandwidthHz, txPowerDbm: value.txPowerDbm, spreadingFactor: value.spreadingFactor, codingRate: value.codingRate };
}
export function liftMultiRNodeMemberConfig(value: N.MultiRNodeMemberConfig): C.MultiRNodeMemberConfig {
  return { name: value.name, virtualPort: value.virtualPort, radio: liftRNodeRadioConfig(value.radio), flowControl: value.flowControl, outgoing: value.outgoing };
}
export function lowerMultiRNodeMemberConfig(value: C.MultiRNodeMemberConfig): N.MultiRNodeMemberConfig {
  return { name: value.name, virtualPort: value.virtualPort, radio: lowerRNodeRadioConfig(value.radio), flowControl: value.flowControl, outgoing: value.outgoing };
}
export function liftInterfaceRoutingPolicy(value: N.InterfaceRoutingPolicy): C.InterfaceRoutingPolicy {
  return { ...(value.mode === undefined ? {} : { mode: liftInterfaceMode(value.mode) }), ...(value.gravity === undefined ? {} : { gravity: liftSafeInt(value.gravity) }), ...(value.recursivePathRequests === undefined ? {} : { recursivePathRequests: value.recursivePathRequests }), ...(value.announcesFromInternal === undefined ? {} : { announcesFromInternal: value.announcesFromInternal }), ...(value.announcesToInternal === undefined ? {} : { announcesToInternal: value.announcesToInternal }) };
}
export function lowerInterfaceRoutingPolicy(value: C.InterfaceRoutingPolicy): N.InterfaceRoutingPolicy {
  return { ...(value.mode === undefined ? {} : { mode: lowerInterfaceMode(value.mode) }), ...(value.gravity === undefined ? {} : { gravity: lowerSafeInt(value.gravity) }), ...(value.recursivePathRequests === undefined ? {} : { recursivePathRequests: value.recursivePathRequests }), ...(value.announcesFromInternal === undefined ? {} : { announcesFromInternal: value.announcesFromInternal }), ...(value.announcesToInternal === undefined ? {} : { announcesToInternal: value.announcesToInternal }) };
}
export function liftBackendInfo(value: N.BackendInfo): C.BackendInfo {
  return { backend: liftBackendKind(value.backend), capabilities: value.capabilities.map((item) => liftCapability(item)), interfaceKinds: value.interfaceKinds.map((item) => liftInterfaceKind(item)) };
}
export function lowerBackendInfo(value: C.BackendInfo): N.BackendInfo {
  return { backend: lowerBackendKind(value.backend), capabilities: value.capabilities.map((item) => lowerCapability(item)), interfaceKinds: value.interfaceKinds.map((item) => lowerInterfaceKind(item)) };
}
export function liftInterfaceSnapshot(value: N.InterfaceSnapshot): C.InterfaceSnapshot {
  return { interfaceId: C.interfaceId(value.interfaceId), ...(value.name === undefined ? {} : { name: value.name }), ...(value.kind === undefined ? {} : { kind: liftInterfaceKind(value.kind) }), health: liftInterfaceHealth(value.health), ...(value.failureDetail === undefined ? {} : { failureDetail: value.failureDetail }), rxBytes: value.rxBytes, txBytes: value.txBytes, ...(value.rxBps === undefined ? {} : { rxBps: liftSafeUint(value.rxBps) }), ...(value.txBps === undefined ? {} : { txBps: liftSafeUint(value.txBps) }), routeCount: value.routeCount, linkCount: value.linkCount, transportedLinkCount: value.transportedLinkCount };
}
export function lowerInterfaceSnapshot(value: C.InterfaceSnapshot): N.InterfaceSnapshot {
  return { interfaceId: C.interfaceId(value.interfaceId), ...(value.name === undefined ? {} : { name: value.name }), ...(value.kind === undefined ? {} : { kind: lowerInterfaceKind(value.kind) }), health: lowerInterfaceHealth(value.health), ...(value.failureDetail === undefined ? {} : { failureDetail: value.failureDetail }), rxBytes: value.rxBytes, txBytes: value.txBytes, ...(value.rxBps === undefined ? {} : { rxBps: lowerSafeUint(value.rxBps) }), ...(value.txBps === undefined ? {} : { txBps: lowerSafeUint(value.txBps) }), routeCount: value.routeCount, linkCount: value.linkCount, transportedLinkCount: value.transportedLinkCount };
}
export function liftRouteSnapshot(value: N.RouteSnapshot): C.RouteSnapshot {
  return { destination: C.destinationHash(value.destination), hops: value.hops, ...(value.viaIdentity === undefined ? {} : { viaIdentity: C.identityHash(value.viaIdentity) }), interfaceId: C.interfaceId(value.interfaceId), learnedAtMillis: liftSafeUint(value.learnedAtMillis), lastRouteActivityAtMillis: liftSafeUint(value.lastRouteActivityAtMillis), expiresAtMillis: liftSafeUint(value.expiresAtMillis) };
}
export function lowerRouteSnapshot(value: C.RouteSnapshot): N.RouteSnapshot {
  return { destination: C.destinationHash(value.destination), hops: value.hops, ...(value.viaIdentity === undefined ? {} : { viaIdentity: C.identityHash(value.viaIdentity) }), interfaceId: C.interfaceId(value.interfaceId), learnedAtMillis: lowerSafeUint(value.learnedAtMillis), lastRouteActivityAtMillis: lowerSafeUint(value.lastRouteActivityAtMillis), expiresAtMillis: lowerSafeUint(value.expiresAtMillis) };
}
export function liftDestinationIdentitySnapshot(value: N.DestinationIdentitySnapshot): C.DestinationIdentitySnapshot {
  return { destination: C.destinationHash(value.destination), identity: C.identityHash(value.identity) };
}
export function lowerDestinationIdentitySnapshot(value: C.DestinationIdentitySnapshot): N.DestinationIdentitySnapshot {
  return { destination: C.destinationHash(value.destination), identity: C.identityHash(value.identity) };
}
export function liftRuntimeHealthSnapshot(value: N.RuntimeHealthSnapshot): C.RuntimeHealthSnapshot {
  return { running: value.running, uptimeMillis: liftSafeUint(value.uptimeMillis), interfaceCount: value.interfaceCount, onlineInterfaceCount: value.onlineInterfaceCount, routeCount: value.routeCount, linkCount: value.linkCount, transportedLinkCount: value.transportedLinkCount, rxBytes: value.rxBytes, txBytes: value.txBytes, rxBps: liftSafeUint(value.rxBps), txBps: liftSafeUint(value.txBps) };
}
export function lowerRuntimeHealthSnapshot(value: C.RuntimeHealthSnapshot): N.RuntimeHealthSnapshot {
  return { running: value.running, uptimeMillis: lowerSafeUint(value.uptimeMillis), interfaceCount: value.interfaceCount, onlineInterfaceCount: value.onlineInterfaceCount, routeCount: value.routeCount, linkCount: value.linkCount, transportedLinkCount: value.transportedLinkCount, rxBytes: value.rxBytes, txBytes: value.txBytes, rxBps: lowerSafeUint(value.rxBps), txBps: lowerSafeUint(value.txBps) };
}
export function liftPersistenceSnapshot(value: N.PersistenceSnapshot): C.PersistenceSnapshot {
  return { persistent: value.persistent, restored: value.restored, ...(value.lastFlushCause === undefined ? {} : { lastFlushCause: liftPersistenceFlushCause(value.lastFlushCause) }), ...(value.lastFailureDetail === undefined ? {} : { lastFailureDetail: value.lastFailureDetail }) };
}
export function lowerPersistenceSnapshot(value: C.PersistenceSnapshot): N.PersistenceSnapshot {
  return { persistent: value.persistent, restored: value.restored, ...(value.lastFlushCause === undefined ? {} : { lastFlushCause: lowerPersistenceFlushCause(value.lastFlushCause) }), ...(value.lastFailureDetail === undefined ? {} : { lastFailureDetail: value.lastFailureDetail }) };
}
export function liftHostSnapshot(value: N.HostSnapshot): C.HostSnapshot {
  return { revision: value.revision, backend: liftBackendInfo(value.backend), interfaces: value.interfaces.map((item) => liftInterfaceSnapshot(item)), routes: value.routes.map((item) => liftRouteSnapshot(item)), activeLinkCount: value.activeLinkCount, destinationIdentities: value.destinationIdentities.map((item) => liftDestinationIdentitySnapshot(item)), runtime: liftRuntimeHealthSnapshot(value.runtime), persistence: liftPersistenceSnapshot(value.persistence) };
}
export function lowerHostSnapshot(value: C.HostSnapshot): N.HostSnapshot {
  return { revision: value.revision, backend: lowerBackendInfo(value.backend), interfaces: value.interfaces.map((item) => lowerInterfaceSnapshot(item)), routes: value.routes.map((item) => lowerRouteSnapshot(item)), activeLinkCount: value.activeLinkCount, destinationIdentities: value.destinationIdentities.map((item) => lowerDestinationIdentitySnapshot(item)), runtime: lowerRuntimeHealthSnapshot(value.runtime), persistence: lowerPersistenceSnapshot(value.persistence) };
}
export function liftPrnsLimits(value: N.PrnsLimits): C.PrnsLimits {
  return { pendingCommands: liftSafeUint(value.pendingCommands), applicationEvents: liftSafeUint(value.applicationEvents), retainedEventBytes: liftSafeUint(value.retainedEventBytes), diagnostics: liftSafeUint(value.diagnostics) };
}
export function lowerPrnsLimits(value: C.PrnsLimits): N.PrnsLimits {
  return { pendingCommands: lowerSafeUint(value.pendingCommands), applicationEvents: lowerSafeUint(value.applicationEvents), retainedEventBytes: lowerSafeUint(value.retainedEventBytes), diagnostics: lowerSafeUint(value.diagnostics) };
}
export function lowerHostConfig(value: C.HostConfig): N.HostConfig {
  return { identity: lowerIdentityConfig(value.identity), persistence: lowerPersistenceConfig(value.persistence), role: lowerHostRole(value.role), destinations: value.destinations.map((item) => lowerDestinationConfig(item)), requiredCapabilities: value.requiredCapabilities.map((item) => lowerCapability(item)), limits: lowerPrnsLimits(value.limits) };
}
export function liftLifecycleSnapshot(value: N.LifecycleSnapshot): C.LifecycleSnapshot {
  return { revision: value.revision, state: liftHostLifecycleState(value.state) };
}
export function lowerLifecycleSnapshot(value: C.LifecycleSnapshot): N.LifecycleSnapshot {
  return { revision: value.revision, state: lowerHostLifecycleState(value.state) };
}
export function lowerIdentityConfig(value: C.IdentityConfig): N.IdentityConfig {
  switch (value.tag) {
    case "Existing": return N.IdentityConfig.Existing.new({ secret: C.identitySecret(value.data.secret) });
    case "GenerateEphemeral": return N.IdentityConfig.GenerateEphemeral.new();
    case "LoadOrCreate": return N.IdentityConfig.LoadOrCreate.new({ path: value.data.path });
    default: return unexpected(value);
  }
}
export function liftPersistenceConfig(value: N.PersistenceConfig): C.PersistenceConfig {
  switch (value.tag) {
    case N.PersistenceConfig_Tags.Ephemeral: return { tag: "Ephemeral", data: undefined };
    case N.PersistenceConfig_Tags.Directory: return { tag: "Directory", data: { path: value.inner.path } };
    default: return unexpected(value);
  }
}
export function lowerPersistenceConfig(value: C.PersistenceConfig): N.PersistenceConfig {
  switch (value.tag) {
    case "Ephemeral": return N.PersistenceConfig.Ephemeral.new();
    case "Directory": return N.PersistenceConfig.Directory.new({ path: value.data.path });
    default: return unexpected(value);
  }
}
export function liftInterfaceConfig(value: N.InterfaceConfig): C.InterfaceConfig {
  switch (value.tag) {
    case N.InterfaceConfig_Tags.AutoLan: return { tag: "AutoLan", data: { ...(value.inner.groupId === undefined ? {} : { groupId: value.inner.groupId }), ...(value.inner.discoveryScope === undefined ? {} : { discoveryScope: liftDiscoveryScope(value.inner.discoveryScope) }), ...(value.inner.discoveryPort === undefined ? {} : { discoveryPort: value.inner.discoveryPort }), ...(value.inner.dataPort === undefined ? {} : { dataPort: value.inner.dataPort }), devices: value.inner.devices.map((item) => item), ignoredDevices: value.inner.ignoredDevices.map((item) => item), ...(value.inner.multicastAddressType === undefined ? {} : { multicastAddressType: liftMulticastAddressType(value.inner.multicastAddressType) }) } };
    case N.InterfaceConfig_Tags.TcpClient: return { tag: "TcpClient", data: { target: value.inner.target, bitrate: liftBitrate(value.inner.bitrate) } };
    case N.InterfaceConfig_Tags.TcpServer: return { tag: "TcpServer", data: { bind: value.inner.bind, bitrate: liftBitrate(value.inner.bitrate) } };
    case N.InterfaceConfig_Tags.Udp: return { tag: "Udp", data: { local: value.inner.local, peer: value.inner.peer, bitrate: liftBitrate(value.inner.bitrate) } };
    case N.InterfaceConfig_Tags.Serial: return { tag: "Serial", data: { port: value.inner.port, line: liftSerialLineConfig(value.inner.line) } };
    case N.InterfaceConfig_Tags.Kiss: return { tag: "Kiss", data: { port: value.inner.port, line: liftSerialLineConfig(value.inner.line), flowControl: value.inner.flowControl, preambleMillis: value.inner.preambleMillis, transmitTailMillis: value.inner.transmitTailMillis, persistence: value.inner.persistence, slotTimeMillis: value.inner.slotTimeMillis, ...(value.inner.stationCallsign === undefined ? {} : { stationCallsign: value.inner.stationCallsign }), ...(value.inner.stationIntervalSeconds === undefined ? {} : { stationIntervalSeconds: liftSafeUint(value.inner.stationIntervalSeconds) }) } };
    case N.InterfaceConfig_Tags.Ax25Kiss: return { tag: "Ax25Kiss", data: { port: value.inner.port, line: liftSerialLineConfig(value.inner.line), flowControl: value.inner.flowControl, preambleMillis: value.inner.preambleMillis, transmitTailMillis: value.inner.transmitTailMillis, persistence: value.inner.persistence, slotTimeMillis: value.inner.slotTimeMillis, callsign: value.inner.callsign, ssid: value.inner.ssid } };
    case N.InterfaceConfig_Tags.RNode: return { tag: "RNode", data: { port: value.inner.port, radio: liftRNodeRadioConfig(value.inner.radio), flowControl: value.inner.flowControl, ...(value.inner.stationCallsign === undefined ? {} : { stationCallsign: value.inner.stationCallsign }), ...(value.inner.stationIntervalSeconds === undefined ? {} : { stationIntervalSeconds: liftSafeUint(value.inner.stationIntervalSeconds) }), ...(value.inner.airtimeLimitShortCentiPercent === undefined ? {} : { airtimeLimitShortCentiPercent: value.inner.airtimeLimitShortCentiPercent }), ...(value.inner.airtimeLimitLongCentiPercent === undefined ? {} : { airtimeLimitLongCentiPercent: value.inner.airtimeLimitLongCentiPercent }) } };
    case N.InterfaceConfig_Tags.MultiRNode: return { tag: "MultiRNode", data: { port: value.inner.port, ...(value.inner.stationCallsign === undefined ? {} : { stationCallsign: value.inner.stationCallsign }), ...(value.inner.stationIntervalSeconds === undefined ? {} : { stationIntervalSeconds: liftSafeUint(value.inner.stationIntervalSeconds) }), members: value.inner.members.map((item) => liftMultiRNodeMemberConfig(item)) } };
    case N.InterfaceConfig_Tags.Pipe: return { tag: "Pipe", data: { command: value.inner.command.map((item) => item), respawnDelayMillis: liftSafeUint(value.inner.respawnDelayMillis) } };
    case N.InterfaceConfig_Tags.BackboneClient: return { tag: "BackboneClient", data: { target: value.inner.target, bitrate: liftBitrate(value.inner.bitrate) } };
    case N.InterfaceConfig_Tags.BackboneServer: return { tag: "BackboneServer", data: { bind: value.inner.bind, bitrate: liftBitrate(value.inner.bitrate) } };
    case N.InterfaceConfig_Tags.I2p: return { tag: "I2p", data: { peers: value.inner.peers.map((item) => item), connectable: value.inner.connectable } };
    case N.InterfaceConfig_Tags.Weave: return { tag: "Weave", data: { port: value.inner.port } };
    case N.InterfaceConfig_Tags.AutomaticUsb: return { tag: "AutomaticUsb", data: undefined };
    case N.InterfaceConfig_Tags.AutomaticBluetoothLe: return { tag: "AutomaticBluetoothLe", data: undefined };
    case N.InterfaceConfig_Tags.WebSocketClient: return { tag: "WebSocketClient", data: { target: value.inner.target, framing: liftWebSocketFramingSelection(value.inner.framing) } };
    case N.InterfaceConfig_Tags.WebSocketServer: return { tag: "WebSocketServer", data: { bind: value.inner.bind, framing: liftWebSocketFramingSelection(value.inner.framing) } };
    case N.InterfaceConfig_Tags.BrowserRendezvous: return { tag: "BrowserRendezvous", data: { url: value.inner.url } };
    default: return unexpected(value);
  }
}
export function lowerInterfaceConfig(value: C.InterfaceConfig): N.InterfaceConfig {
  switch (value.tag) {
    case "AutoLan": return N.InterfaceConfig.AutoLan.new({ ...(value.data.groupId === undefined ? {} : { groupId: value.data.groupId }), ...(value.data.discoveryScope === undefined ? {} : { discoveryScope: lowerDiscoveryScope(value.data.discoveryScope) }), ...(value.data.discoveryPort === undefined ? {} : { discoveryPort: value.data.discoveryPort }), ...(value.data.dataPort === undefined ? {} : { dataPort: value.data.dataPort }), devices: value.data.devices.map((item) => item), ignoredDevices: value.data.ignoredDevices.map((item) => item), ...(value.data.multicastAddressType === undefined ? {} : { multicastAddressType: lowerMulticastAddressType(value.data.multicastAddressType) }) });
    case "TcpClient": return N.InterfaceConfig.TcpClient.new({ target: value.data.target, bitrate: lowerBitrate(value.data.bitrate) });
    case "TcpServer": return N.InterfaceConfig.TcpServer.new({ bind: value.data.bind, bitrate: lowerBitrate(value.data.bitrate) });
    case "Udp": return N.InterfaceConfig.Udp.new({ local: value.data.local, peer: value.data.peer, bitrate: lowerBitrate(value.data.bitrate) });
    case "Serial": return N.InterfaceConfig.Serial.new({ port: value.data.port, line: lowerSerialLineConfig(value.data.line) });
    case "Kiss": return N.InterfaceConfig.Kiss.new({ port: value.data.port, line: lowerSerialLineConfig(value.data.line), flowControl: value.data.flowControl, preambleMillis: value.data.preambleMillis, transmitTailMillis: value.data.transmitTailMillis, persistence: value.data.persistence, slotTimeMillis: value.data.slotTimeMillis, ...(value.data.stationCallsign === undefined ? {} : { stationCallsign: value.data.stationCallsign }), ...(value.data.stationIntervalSeconds === undefined ? {} : { stationIntervalSeconds: lowerSafeUint(value.data.stationIntervalSeconds) }) });
    case "Ax25Kiss": return N.InterfaceConfig.Ax25Kiss.new({ port: value.data.port, line: lowerSerialLineConfig(value.data.line), flowControl: value.data.flowControl, preambleMillis: value.data.preambleMillis, transmitTailMillis: value.data.transmitTailMillis, persistence: value.data.persistence, slotTimeMillis: value.data.slotTimeMillis, callsign: value.data.callsign, ssid: value.data.ssid });
    case "RNode": return N.InterfaceConfig.RNode.new({ port: value.data.port, radio: lowerRNodeRadioConfig(value.data.radio), flowControl: value.data.flowControl, ...(value.data.stationCallsign === undefined ? {} : { stationCallsign: value.data.stationCallsign }), ...(value.data.stationIntervalSeconds === undefined ? {} : { stationIntervalSeconds: lowerSafeUint(value.data.stationIntervalSeconds) }), ...(value.data.airtimeLimitShortCentiPercent === undefined ? {} : { airtimeLimitShortCentiPercent: value.data.airtimeLimitShortCentiPercent }), ...(value.data.airtimeLimitLongCentiPercent === undefined ? {} : { airtimeLimitLongCentiPercent: value.data.airtimeLimitLongCentiPercent }) });
    case "MultiRNode": return N.InterfaceConfig.MultiRNode.new({ port: value.data.port, ...(value.data.stationCallsign === undefined ? {} : { stationCallsign: value.data.stationCallsign }), ...(value.data.stationIntervalSeconds === undefined ? {} : { stationIntervalSeconds: lowerSafeUint(value.data.stationIntervalSeconds) }), members: value.data.members.map((item) => lowerMultiRNodeMemberConfig(item)) });
    case "Pipe": return N.InterfaceConfig.Pipe.new({ command: value.data.command.map((item) => item), respawnDelayMillis: lowerSafeUint(value.data.respawnDelayMillis) });
    case "BackboneClient": return N.InterfaceConfig.BackboneClient.new({ target: value.data.target, bitrate: lowerBitrate(value.data.bitrate) });
    case "BackboneServer": return N.InterfaceConfig.BackboneServer.new({ bind: value.data.bind, bitrate: lowerBitrate(value.data.bitrate) });
    case "I2p": return N.InterfaceConfig.I2p.new({ peers: value.data.peers.map((item) => item), connectable: value.data.connectable });
    case "Weave": return N.InterfaceConfig.Weave.new({ port: value.data.port });
    case "AutomaticUsb": return N.InterfaceConfig.AutomaticUsb.new();
    case "AutomaticBluetoothLe": return N.InterfaceConfig.AutomaticBluetoothLe.new();
    case "WebSocketClient": return N.InterfaceConfig.WebSocketClient.new({ target: value.data.target, framing: lowerWebSocketFramingSelection(value.data.framing) });
    case "WebSocketServer": return N.InterfaceConfig.WebSocketServer.new({ bind: value.data.bind, framing: lowerWebSocketFramingSelection(value.data.framing) });
    case "BrowserRendezvous": return N.InterfaceConfig.BrowserRendezvous.new({ url: value.data.url });
    default: return unexpected(value);
  }
}
export function lowerDestinationIdentityConfig(value: C.DestinationIdentityConfig): N.DestinationIdentityConfig {
  switch (value.tag) {
    case "HostIdentity": return N.DestinationIdentityConfig.HostIdentity.new();
    case "DedicatedIdentity": return N.DestinationIdentityConfig.DedicatedIdentity.new({ identity: lowerIdentityConfig(value.data.identity) });
    default: return unexpected(value);
  }
}
export function liftBitrate(value: N.Bitrate): C.Bitrate {
  switch (value.tag) {
    case N.Bitrate_Tags.Auto: return { tag: "Auto", data: undefined };
    case N.Bitrate_Tags.BitsPerSecond: return { tag: "BitsPerSecond", data: { value: liftSafeUint(value.inner.value) } };
    default: return unexpected(value);
  }
}
export function lowerBitrate(value: C.Bitrate): N.Bitrate {
  switch (value.tag) {
    case "Auto": return N.Bitrate.Auto.new();
    case "BitsPerSecond": return N.Bitrate.BitsPerSecond.new({ value: lowerSafeUint(value.data.value) });
    default: return unexpected(value);
  }
}
export function liftResponseTimeout(value: N.ResponseTimeout): C.ResponseTimeout {
  switch (value.tag) {
    case N.ResponseTimeout_Tags.LinkDefault: return { tag: "LinkDefault", data: undefined };
    case N.ResponseTimeout_Tags.Exact: return { tag: "Exact", data: { millis: liftSafeUint(value.inner.millis) } };
    default: return unexpected(value);
  }
}
export function lowerResponseTimeout(value: C.ResponseTimeout): N.ResponseTimeout {
  switch (value.tag) {
    case "LinkDefault": return N.ResponseTimeout.LinkDefault.new();
    case "Exact": return N.ResponseTimeout.Exact.new({ millis: lowerSafeUint(value.data.millis) });
    default: return unexpected(value);
  }
}
export function liftResourceCompression(value: N.ResourceCompression): C.ResourceCompression {
  switch (value) {
    case N.ResourceCompression.Auto: return { tag: "Auto", data: undefined };
    case N.ResourceCompression.Never: return { tag: "Never", data: undefined };
    default: return unexpected(value);
  }
}
export function lowerResourceCompression(value: C.ResourceCompression): N.ResourceCompression {
  switch (value.tag) {
    case "Auto": return N.ResourceCompression.Auto;
    case "Never": return N.ResourceCompression.Never;
    default: return unexpected(value);
  }
}
export function liftResourceStrategy(value: N.ResourceStrategy): C.ResourceStrategy {
  switch (value.tag) {
    case N.ResourceStrategy_Tags.Refuse: return { tag: "Refuse", data: undefined };
    case N.ResourceStrategy_Tags.Accept: return { tag: "Accept", data: { maximumUncompressedBytes: liftSafeUint(value.inner.maximumUncompressedBytes), acceptCompressed: value.inner.acceptCompressed } };
    default: return unexpected(value);
  }
}
export function lowerResourceStrategy(value: C.ResourceStrategy): N.ResourceStrategy {
  switch (value.tag) {
    case "Refuse": return N.ResourceStrategy.Refuse.new();
    case "Accept": return N.ResourceStrategy.Accept.new({ maximumUncompressedBytes: lowerSafeUint(value.data.maximumUncompressedBytes), acceptCompressed: value.data.acceptCompressed });
    default: return unexpected(value);
  }
}
export function lowerDestinationConfig(value: C.DestinationConfig): N.DestinationConfig {
  switch (value.tag) {
    case "Plain": return N.DestinationConfig.Plain.new({ name: lowerDestinationName(value.data.name) });
    case "Single": return N.DestinationConfig.Single.new({ name: lowerDestinationName(value.data.name), identity: lowerDestinationIdentityConfig(value.data.identity), ...(value.data.announceAppData === undefined ? {} : { announceAppData: value.data.announceAppData }), ...(value.data.maximumRequestBytes === undefined ? {} : { maximumRequestBytes: lowerSafeUint(value.data.maximumRequestBytes) }), requestHandlers: value.data.requestHandlers.map((item) => lowerRequestHandlerConfig(item)) });
    default: return unexpected(value);
  }
}
export function liftHostCommand(value: N.HostCommand): C.HostCommand {
  switch (value.tag) {
    case N.HostCommand_Tags.Announce: return { tag: "Announce", data: { destination: C.destinationHash(value.inner.destination), ...(value.inner.interface === undefined ? {} : { interface: C.interfaceId(value.inner.interface) }) } };
    case N.HostCommand_Tags.SendSinglePacket: return { tag: "SendSinglePacket", data: { destination: C.destinationHash(value.inner.destination), payload: value.inner.payload } };
    case N.HostCommand_Tags.CloseLink: return { tag: "CloseLink", data: { linkId: C.linkId(value.inner.linkId) } };
    case N.HostCommand_Tags.AttachTcpServer: return { tag: "AttachTcpServer", data: { bind: value.inner.bind, bitrate: liftBitrate(value.inner.bitrate) } };
    case N.HostCommand_Tags.AttachTcpClient: return { tag: "AttachTcpClient", data: { target: value.inner.target, bitrate: liftBitrate(value.inner.bitrate) } };
    case N.HostCommand_Tags.AttachUdp: return { tag: "AttachUdp", data: { local: value.inner.local, peer: value.inner.peer, bitrate: liftBitrate(value.inner.bitrate) } };
    case N.HostCommand_Tags.DetachInterface: return { tag: "DetachInterface", data: { interface: C.interfaceId(value.inner.interface) } };
    case N.HostCommand_Tags.EstablishLink: return { tag: "EstablishLink", data: { destination: C.destinationHash(value.inner.destination) } };
    case N.HostCommand_Tags.RequestPath: return { tag: "RequestPath", data: { destination: C.destinationHash(value.inner.destination) } };
    case N.HostCommand_Tags.Identify: return { tag: "Identify", data: { linkId: C.linkId(value.inner.linkId), identity: C.identityHash(value.inner.identity) } };
    case N.HostCommand_Tags.SendLinkPacket: return { tag: "SendLinkPacket", data: { linkId: C.linkId(value.inner.linkId), payload: value.inner.payload } };
    case N.HostCommand_Tags.Request: return { tag: "Request", data: { linkId: C.linkId(value.inner.linkId), pathHash: C.requestPathHash(value.inner.pathHash), payload: value.inner.payload, timeout: liftResponseTimeout(value.inner.timeout), ...(value.inner.maximumResponseBytes === undefined ? {} : { maximumResponseBytes: liftSafeUint(value.inner.maximumResponseBytes) }) } };
    case N.HostCommand_Tags.Respond: return { tag: "Respond", data: { linkId: C.linkId(value.inner.linkId), requestId: C.requestId(value.inner.requestId), requestRttMillis: liftSafeUint(value.inner.requestRttMillis), payload: value.inner.payload } };
    case N.HostCommand_Tags.SendResource: return { tag: "SendResource", data: { linkId: C.linkId(value.inner.linkId), payload: value.inner.payload, ...(value.inner.packedMetadata === undefined ? {} : { packedMetadata: value.inner.packedMetadata }), compression: liftResourceCompression(value.inner.compression) } };
    case N.HostCommand_Tags.SetLinkResourceStrategy: return { tag: "SetLinkResourceStrategy", data: { linkId: C.linkId(value.inner.linkId), strategy: liftResourceStrategy(value.inner.strategy) } };
    case N.HostCommand_Tags.SetDestinationResourceStrategy: return { tag: "SetDestinationResourceStrategy", data: { destination: C.destinationHash(value.inner.destination), strategy: liftResourceStrategy(value.inner.strategy) } };
    case N.HostCommand_Tags.SendChannelMessage: return { tag: "SendChannelMessage", data: { linkId: C.linkId(value.inner.linkId), messageType: value.inner.messageType, payload: value.inner.payload } };
    case N.HostCommand_Tags.AllowRequester: return { tag: "AllowRequester", data: { destination: C.destinationHash(value.inner.destination), pathHash: C.requestPathHash(value.inner.pathHash), identity: C.identityHash(value.inner.identity) } };
    case N.HostCommand_Tags.AttachInterface: return { tag: "AttachInterface", data: { config: liftInterfaceConfig(value.inner.config), ...(value.inner.routing === undefined ? {} : { routing: liftInterfaceRoutingPolicy(value.inner.routing) }) } };
    default: return unexpected(value);
  }
}
export function lowerHostCommand(value: C.HostCommand): N.HostCommand {
  switch (value.tag) {
    case "Announce": return N.HostCommand.Announce.new({ destination: C.destinationHash(value.data.destination), ...(value.data.interface === undefined ? {} : { interface: C.interfaceId(value.data.interface) }) });
    case "SendSinglePacket": return N.HostCommand.SendSinglePacket.new({ destination: C.destinationHash(value.data.destination), payload: value.data.payload });
    case "CloseLink": return N.HostCommand.CloseLink.new({ linkId: C.linkId(value.data.linkId) });
    case "AttachTcpServer": return N.HostCommand.AttachTcpServer.new({ bind: value.data.bind, bitrate: lowerBitrate(value.data.bitrate) });
    case "AttachTcpClient": return N.HostCommand.AttachTcpClient.new({ target: value.data.target, bitrate: lowerBitrate(value.data.bitrate) });
    case "AttachUdp": return N.HostCommand.AttachUdp.new({ local: value.data.local, peer: value.data.peer, bitrate: lowerBitrate(value.data.bitrate) });
    case "DetachInterface": return N.HostCommand.DetachInterface.new({ interface: C.interfaceId(value.data.interface) });
    case "EstablishLink": return N.HostCommand.EstablishLink.new({ destination: C.destinationHash(value.data.destination) });
    case "RequestPath": return N.HostCommand.RequestPath.new({ destination: C.destinationHash(value.data.destination) });
    case "Identify": return N.HostCommand.Identify.new({ linkId: C.linkId(value.data.linkId), identity: C.identityHash(value.data.identity) });
    case "SendLinkPacket": return N.HostCommand.SendLinkPacket.new({ linkId: C.linkId(value.data.linkId), payload: value.data.payload });
    case "Request": return N.HostCommand.Request.new({ linkId: C.linkId(value.data.linkId), pathHash: C.requestPathHash(value.data.pathHash), payload: value.data.payload, timeout: lowerResponseTimeout(value.data.timeout), ...(value.data.maximumResponseBytes === undefined ? {} : { maximumResponseBytes: lowerSafeUint(value.data.maximumResponseBytes) }) });
    case "Respond": return N.HostCommand.Respond.new({ linkId: C.linkId(value.data.linkId), requestId: C.requestId(value.data.requestId), requestRttMillis: lowerSafeUint(value.data.requestRttMillis), payload: value.data.payload });
    case "SendResource": return N.HostCommand.SendResource.new({ linkId: C.linkId(value.data.linkId), payload: value.data.payload, ...(value.data.packedMetadata === undefined ? {} : { packedMetadata: value.data.packedMetadata }), compression: lowerResourceCompression(value.data.compression) });
    case "SetLinkResourceStrategy": return N.HostCommand.SetLinkResourceStrategy.new({ linkId: C.linkId(value.data.linkId), strategy: lowerResourceStrategy(value.data.strategy) });
    case "SetDestinationResourceStrategy": return N.HostCommand.SetDestinationResourceStrategy.new({ destination: C.destinationHash(value.data.destination), strategy: lowerResourceStrategy(value.data.strategy) });
    case "SendChannelMessage": return N.HostCommand.SendChannelMessage.new({ linkId: C.linkId(value.data.linkId), messageType: value.data.messageType, payload: value.data.payload });
    case "AllowRequester": return N.HostCommand.AllowRequester.new({ destination: C.destinationHash(value.data.destination), pathHash: C.requestPathHash(value.data.pathHash), identity: C.identityHash(value.data.identity) });
    case "AttachInterface": return N.HostCommand.AttachInterface.new({ config: lowerInterfaceConfig(value.data.config), ...(value.data.routing === undefined ? {} : { routing: lowerInterfaceRoutingPolicy(value.data.routing) }) });
    default: return unexpected(value);
  }
}
export function liftCommandOutcome(value: N.CommandOutcome): C.CommandOutcome {
  switch (value.tag) {
    case N.CommandOutcome_Tags.Announced: return { tag: "Announced", data: undefined };
    case N.CommandOutcome_Tags.PacketDelivered: return { tag: "PacketDelivered", data: { rttMillis: liftSafeUint(value.inner.rttMillis), evidence: liftDeliveryEvidenceKind(value.inner.evidence), ...(value.inner.packetHash === undefined ? {} : { packetHash: C.packetHash(value.inner.packetHash) }) } };
    case N.CommandOutcome_Tags.LinkCloseQueued: return { tag: "LinkCloseQueued", data: undefined };
    case N.CommandOutcome_Tags.InterfaceAttached: return { tag: "InterfaceAttached", data: { interface: C.interfaceId(value.inner.interface) } };
    case N.CommandOutcome_Tags.InterfaceDetached: return { tag: "InterfaceDetached", data: { interface: C.interfaceId(value.inner.interface) } };
    case N.CommandOutcome_Tags.LinkEstablished: return { tag: "LinkEstablished", data: { linkId: C.linkId(value.inner.linkId), rttMillis: liftSafeUint(value.inner.rttMillis) } };
    case N.CommandOutcome_Tags.PathDiscovered: return { tag: "PathDiscovered", data: { hops: value.inner.hops } };
    case N.CommandOutcome_Tags.Identified: return { tag: "Identified", data: undefined };
    case N.CommandOutcome_Tags.ResponseReceived: return { tag: "ResponseReceived", data: { data: value.inner.data, rttMillis: liftSafeUint(value.inner.rttMillis) } };
    case N.CommandOutcome_Tags.ResponseSent: return { tag: "ResponseSent", data: { rttMillis: liftSafeUint(value.inner.rttMillis) } };
    case N.CommandOutcome_Tags.ResourceSent: return { tag: "ResourceSent", data: undefined };
    case N.CommandOutcome_Tags.ResourceStrategySet: return { tag: "ResourceStrategySet", data: undefined };
    case N.CommandOutcome_Tags.RequesterAllowed: return { tag: "RequesterAllowed", data: undefined };
    default: return unexpected(value);
  }
}
export function lowerCommandOutcome(value: C.CommandOutcome): N.CommandOutcome {
  switch (value.tag) {
    case "Announced": return N.CommandOutcome.Announced.new();
    case "PacketDelivered": return N.CommandOutcome.PacketDelivered.new({ rttMillis: lowerSafeUint(value.data.rttMillis), evidence: lowerDeliveryEvidenceKind(value.data.evidence), ...(value.data.packetHash === undefined ? {} : { packetHash: C.packetHash(value.data.packetHash) }) });
    case "LinkCloseQueued": return N.CommandOutcome.LinkCloseQueued.new();
    case "InterfaceAttached": return N.CommandOutcome.InterfaceAttached.new({ interface: C.interfaceId(value.data.interface) });
    case "InterfaceDetached": return N.CommandOutcome.InterfaceDetached.new({ interface: C.interfaceId(value.data.interface) });
    case "LinkEstablished": return N.CommandOutcome.LinkEstablished.new({ linkId: C.linkId(value.data.linkId), rttMillis: lowerSafeUint(value.data.rttMillis) });
    case "PathDiscovered": return N.CommandOutcome.PathDiscovered.new({ hops: value.data.hops });
    case "Identified": return N.CommandOutcome.Identified.new();
    case "ResponseReceived": return N.CommandOutcome.ResponseReceived.new({ data: value.data.data, rttMillis: lowerSafeUint(value.data.rttMillis) });
    case "ResponseSent": return N.CommandOutcome.ResponseSent.new({ rttMillis: lowerSafeUint(value.data.rttMillis) });
    case "ResourceSent": return N.CommandOutcome.ResourceSent.new();
    case "ResourceStrategySet": return N.CommandOutcome.ResourceStrategySet.new();
    case "RequesterAllowed": return N.CommandOutcome.RequesterAllowed.new();
    default: return unexpected(value);
  }
}
export function liftCommandFailure(value: N.CommandFailure): C.CommandFailure {
  switch (value.tag) {
    case N.CommandFailure_Tags.NodeStopped: return { tag: "NodeStopped", data: undefined };
    case N.CommandFailure_Tags.Busy: return { tag: "Busy", data: undefined };
    case N.CommandFailure_Tags.PayloadTooLarge: return { tag: "PayloadTooLarge", data: undefined };
    case N.CommandFailure_Tags.UnknownDestination: return { tag: "UnknownDestination", data: undefined };
    case N.CommandFailure_Tags.NotSingleDestination: return { tag: "NotSingleDestination", data: undefined };
    case N.CommandFailure_Tags.AnnounceAppDataTooLong: return { tag: "AnnounceAppDataTooLong", data: undefined };
    case N.CommandFailure_Tags.UnknownInterface: return { tag: "UnknownInterface", data: undefined };
    case N.CommandFailure_Tags.NoRouteToDestination: return { tag: "NoRouteToDestination", data: undefined };
    case N.CommandFailure_Tags.NotDirectlyReachable: return { tag: "NotDirectlyReachable", data: undefined };
    case N.CommandFailure_Tags.PacketCulled: return { tag: "PacketCulled", data: undefined };
    case N.CommandFailure_Tags.DeliveryTimedOut: return { tag: "DeliveryTimedOut", data: undefined };
    case N.CommandFailure_Tags.InvalidBitrate: return { tag: "InvalidBitrate", data: undefined };
    case N.CommandFailure_Tags.BindFailed: return { tag: "BindFailed", data: { detail: value.inner.detail } };
    case N.CommandFailure_Tags.WriteFailed: return { tag: "WriteFailed", data: { detail: value.inner.detail } };
    case N.CommandFailure_Tags.UnsupportedByBackend: return { tag: "UnsupportedByBackend", data: undefined };
    case N.CommandFailure_Tags.UnknownLink: return { tag: "UnknownLink", data: undefined };
    case N.CommandFailure_Tags.LinkNotActive: return { tag: "LinkNotActive", data: undefined };
    case N.CommandFailure_Tags.EntropyUnavailable: return { tag: "EntropyUnavailable", data: undefined };
    case N.CommandFailure_Tags.NotLinkInitiator: return { tag: "NotLinkInitiator", data: undefined };
    case N.CommandFailure_Tags.IdentityNotHeld: return { tag: "IdentityNotHeld", data: undefined };
    case N.CommandFailure_Tags.UnknownRequestHandler: return { tag: "UnknownRequestHandler", data: undefined };
    case N.CommandFailure_Tags.RequestPolicyNotAllowList: return { tag: "RequestPolicyNotAllowList", data: undefined };
    case N.CommandFailure_Tags.RequestAllowListFull: return { tag: "RequestAllowListFull", data: undefined };
    case N.CommandFailure_Tags.LinkBusy: return { tag: "LinkBusy", data: undefined };
    case N.CommandFailure_Tags.ResourceTableFull: return { tag: "ResourceTableFull", data: undefined };
    case N.CommandFailure_Tags.ResourceMetadataTooLarge: return { tag: "ResourceMetadataTooLarge", data: undefined };
    case N.CommandFailure_Tags.ResourceRejectedByPeer: return { tag: "ResourceRejectedByPeer", data: undefined };
    case N.CommandFailure_Tags.ResourceSequencingFailed: return { tag: "ResourceSequencingFailed", data: undefined };
    case N.CommandFailure_Tags.ResourcePredecessorFailed: return { tag: "ResourcePredecessorFailed", data: undefined };
    case N.CommandFailure_Tags.ChannelWindowFull: return { tag: "ChannelWindowFull", data: undefined };
    case N.CommandFailure_Tags.ChannelUntrackable: return { tag: "ChannelUntrackable", data: undefined };
    case N.CommandFailure_Tags.InvalidChannelMessageType: return { tag: "InvalidChannelMessageType", data: undefined };
    case N.CommandFailure_Tags.InvalidConfiguration: return { tag: "InvalidConfiguration", data: { detail: value.inner.detail } };
    case N.CommandFailure_Tags.ResourceUploadCancelled: return { tag: "ResourceUploadCancelled", data: undefined };
    case N.CommandFailure_Tags.ResourceEarlyEof: return { tag: "ResourceEarlyEof", data: undefined };
    case N.CommandFailure_Tags.ResourceLengthOverrun: return { tag: "ResourceLengthOverrun", data: undefined };
    case N.CommandFailure_Tags.PermissionDenied: return { tag: "PermissionDenied", data: { detail: value.inner.detail } };
    case N.CommandFailure_Tags.DeviceUnavailable: return { tag: "DeviceUnavailable", data: { detail: value.inner.detail } };
    case N.CommandFailure_Tags.ConnectFailed: return { tag: "ConnectFailed", data: { detail: value.inner.detail } };
    case N.CommandFailure_Tags.BackendFailed: return { tag: "BackendFailed", data: { detail: value.inner.detail } };
    case N.CommandFailure_Tags.ResponseTooLarge: return { tag: "ResponseTooLarge", data: undefined };
    case N.CommandFailure_Tags.LinkClosed: return { tag: "LinkClosed", data: undefined };
    case N.CommandFailure_Tags.ResponseCancelledBySender: return { tag: "ResponseCancelledBySender", data: undefined };
    case N.CommandFailure_Tags.ResponseHashmapBeyondPartCount: return { tag: "ResponseHashmapBeyondPartCount", data: undefined };
    case N.CommandFailure_Tags.ResponseHashmapSkipsAhead: return { tag: "ResponseHashmapSkipsAhead", data: undefined };
    case N.CommandFailure_Tags.ResponseHashmapTooLong: return { tag: "ResponseHashmapTooLong", data: undefined };
    case N.CommandFailure_Tags.ResponseHashmapRagged: return { tag: "ResponseHashmapRagged", data: undefined };
    case N.CommandFailure_Tags.ResponseRetriesExhausted: return { tag: "ResponseRetriesExhausted", data: undefined };
    case N.CommandFailure_Tags.ResponseLinkVanished: return { tag: "ResponseLinkVanished", data: undefined };
    case N.CommandFailure_Tags.ResponseTransferUnopenable: return { tag: "ResponseTransferUnopenable", data: undefined };
    case N.CommandFailure_Tags.ResponseTransferCorrupt: return { tag: "ResponseTransferCorrupt", data: undefined };
    case N.CommandFailure_Tags.ResponseProofUnsendable: return { tag: "ResponseProofUnsendable", data: undefined };
    case N.CommandFailure_Tags.ResponseDecompressionFailed: return { tag: "ResponseDecompressionFailed", data: undefined };
    case N.CommandFailure_Tags.ResponseDecompressionTimedOut: return { tag: "ResponseDecompressionTimedOut", data: undefined };
    case N.CommandFailure_Tags.ResponseOpenTimedOut: return { tag: "ResponseOpenTimedOut", data: undefined };
    case N.CommandFailure_Tags.ResponseMetadataOverrun: return { tag: "ResponseMetadataOverrun", data: undefined };
    default: return unexpected(value);
  }
}
export function lowerCommandFailure(value: C.CommandFailure): N.CommandFailure {
  switch (value.tag) {
    case "NodeStopped": return N.CommandFailure.NodeStopped.new();
    case "Busy": return N.CommandFailure.Busy.new();
    case "PayloadTooLarge": return N.CommandFailure.PayloadTooLarge.new();
    case "UnknownDestination": return N.CommandFailure.UnknownDestination.new();
    case "NotSingleDestination": return N.CommandFailure.NotSingleDestination.new();
    case "AnnounceAppDataTooLong": return N.CommandFailure.AnnounceAppDataTooLong.new();
    case "UnknownInterface": return N.CommandFailure.UnknownInterface.new();
    case "NoRouteToDestination": return N.CommandFailure.NoRouteToDestination.new();
    case "NotDirectlyReachable": return N.CommandFailure.NotDirectlyReachable.new();
    case "PacketCulled": return N.CommandFailure.PacketCulled.new();
    case "DeliveryTimedOut": return N.CommandFailure.DeliveryTimedOut.new();
    case "InvalidBitrate": return N.CommandFailure.InvalidBitrate.new();
    case "BindFailed": return N.CommandFailure.BindFailed.new({ detail: value.data.detail });
    case "WriteFailed": return N.CommandFailure.WriteFailed.new({ detail: value.data.detail });
    case "UnsupportedByBackend": return N.CommandFailure.UnsupportedByBackend.new();
    case "UnknownLink": return N.CommandFailure.UnknownLink.new();
    case "LinkNotActive": return N.CommandFailure.LinkNotActive.new();
    case "EntropyUnavailable": return N.CommandFailure.EntropyUnavailable.new();
    case "NotLinkInitiator": return N.CommandFailure.NotLinkInitiator.new();
    case "IdentityNotHeld": return N.CommandFailure.IdentityNotHeld.new();
    case "UnknownRequestHandler": return N.CommandFailure.UnknownRequestHandler.new();
    case "RequestPolicyNotAllowList": return N.CommandFailure.RequestPolicyNotAllowList.new();
    case "RequestAllowListFull": return N.CommandFailure.RequestAllowListFull.new();
    case "LinkBusy": return N.CommandFailure.LinkBusy.new();
    case "ResourceTableFull": return N.CommandFailure.ResourceTableFull.new();
    case "ResourceMetadataTooLarge": return N.CommandFailure.ResourceMetadataTooLarge.new();
    case "ResourceRejectedByPeer": return N.CommandFailure.ResourceRejectedByPeer.new();
    case "ResourceSequencingFailed": return N.CommandFailure.ResourceSequencingFailed.new();
    case "ResourcePredecessorFailed": return N.CommandFailure.ResourcePredecessorFailed.new();
    case "ChannelWindowFull": return N.CommandFailure.ChannelWindowFull.new();
    case "ChannelUntrackable": return N.CommandFailure.ChannelUntrackable.new();
    case "InvalidChannelMessageType": return N.CommandFailure.InvalidChannelMessageType.new();
    case "InvalidConfiguration": return N.CommandFailure.InvalidConfiguration.new({ detail: value.data.detail });
    case "ResourceUploadCancelled": return N.CommandFailure.ResourceUploadCancelled.new();
    case "ResourceEarlyEof": return N.CommandFailure.ResourceEarlyEof.new();
    case "ResourceLengthOverrun": return N.CommandFailure.ResourceLengthOverrun.new();
    case "PermissionDenied": return N.CommandFailure.PermissionDenied.new({ detail: value.data.detail });
    case "DeviceUnavailable": return N.CommandFailure.DeviceUnavailable.new({ detail: value.data.detail });
    case "ConnectFailed": return N.CommandFailure.ConnectFailed.new({ detail: value.data.detail });
    case "BackendFailed": return N.CommandFailure.BackendFailed.new({ detail: value.data.detail });
    case "ResponseTooLarge": return N.CommandFailure.ResponseTooLarge.new();
    case "LinkClosed": return N.CommandFailure.LinkClosed.new();
    case "ResponseCancelledBySender": return N.CommandFailure.ResponseCancelledBySender.new();
    case "ResponseHashmapBeyondPartCount": return N.CommandFailure.ResponseHashmapBeyondPartCount.new();
    case "ResponseHashmapSkipsAhead": return N.CommandFailure.ResponseHashmapSkipsAhead.new();
    case "ResponseHashmapTooLong": return N.CommandFailure.ResponseHashmapTooLong.new();
    case "ResponseHashmapRagged": return N.CommandFailure.ResponseHashmapRagged.new();
    case "ResponseRetriesExhausted": return N.CommandFailure.ResponseRetriesExhausted.new();
    case "ResponseLinkVanished": return N.CommandFailure.ResponseLinkVanished.new();
    case "ResponseTransferUnopenable": return N.CommandFailure.ResponseTransferUnopenable.new();
    case "ResponseTransferCorrupt": return N.CommandFailure.ResponseTransferCorrupt.new();
    case "ResponseProofUnsendable": return N.CommandFailure.ResponseProofUnsendable.new();
    case "ResponseDecompressionFailed": return N.CommandFailure.ResponseDecompressionFailed.new();
    case "ResponseDecompressionTimedOut": return N.CommandFailure.ResponseDecompressionTimedOut.new();
    case "ResponseOpenTimedOut": return N.CommandFailure.ResponseOpenTimedOut.new();
    case "ResponseMetadataOverrun": return N.CommandFailure.ResponseMetadataOverrun.new();
    default: return unexpected(value);
  }
}
export function liftApplicationEvent(value: N.ApplicationEvent, resources: ResourceFactory): C.ApplicationEvent {
  switch (value.tag) {
    case N.ApplicationEvent_Tags.SingleDelivery: return { tag: "SingleDelivery", data: { destination: C.destinationHash(value.inner.destination), sourceInterface: C.interfaceId(value.inner.sourceInterface), plaintext: value.inner.plaintext } };
    case N.ApplicationEvent_Tags.Request: return { tag: "Request", data: { destination: C.destinationHash(value.inner.destination), linkId: C.linkId(value.inner.linkId), requestId: C.requestId(value.inner.requestId), ...(value.inner.requester === undefined ? {} : { requester: C.identityHash(value.inner.requester) }), pathHash: C.requestPathHash(value.inner.pathHash), rttMillis: liftSafeUint(value.inner.rttMillis), data: value.inner.data } };
    case N.ApplicationEvent_Tags.Response: return { tag: "Response", data: { linkId: C.linkId(value.inner.linkId), requestId: C.requestId(value.inner.requestId), data: value.inner.data } };
    case N.ApplicationEvent_Tags.ResponseSegment: return { tag: "ResponseSegment", data: { linkId: C.linkId(value.inner.linkId), requestId: C.requestId(value.inner.requestId), segmentIndex: liftSafeUint(value.inner.segmentIndex), totalSegments: liftSafeUint(value.inner.totalSegments), data: value.inner.data } };
    case N.ApplicationEvent_Tags.ResourceAvailable: return { tag: "ResourceAvailable", data: { linkId: C.linkId(value.inner.linkId), hash: C.resourceHash(value.inner.hash), ...(value.inner.metadata === undefined ? {} : { metadata: value.inner.metadata }), resource: resources(value.inner.resource) } };
    case N.ApplicationEvent_Tags.ResourceSegment: return { tag: "ResourceSegment", data: { linkId: C.linkId(value.inner.linkId), originalHash: C.resourceHash(value.inner.originalHash), segmentIndex: liftSafeUint(value.inner.segmentIndex), totalSegments: liftSafeUint(value.inner.totalSegments), ...(value.inner.metadata === undefined ? {} : { metadata: value.inner.metadata }), data: value.inner.data } };
    case N.ApplicationEvent_Tags.ResourceNeedsDecompression: return { tag: "ResourceNeedsDecompression", data: { linkId: C.linkId(value.inner.linkId), hash: C.resourceHash(value.inner.hash), stream: value.inner.stream, uncompressedDataBytes: value.inner.uncompressedDataBytes } };
    case N.ApplicationEvent_Tags.ChannelMessage: return { tag: "ChannelMessage", data: { linkId: C.linkId(value.inner.linkId), messageType: value.inner.messageType, data: value.inner.data } };
    case N.ApplicationEvent_Tags.LinkDelivery: return { tag: "LinkDelivery", data: { linkId: C.linkId(value.inner.linkId), sourceInterface: C.interfaceId(value.inner.sourceInterface), plaintext: value.inner.plaintext, ...(value.inner.localDestination === undefined ? {} : { localDestination: C.destinationHash(value.inner.localDestination) }), arrivedAtMillis: liftSafeUint(value.inner.arrivedAtMillis) } };
    default: return unexpected(value);
  }
}
export function liftDiagnosticEvent(value: N.DiagnosticEvent): C.DiagnosticEvent {
  switch (value.tag) {
    case N.DiagnosticEvent_Tags.AnnounceHeard: return { tag: "AnnounceHeard", data: { destination: C.destinationHash(value.inner.destination), hops: value.inner.hops, sourceInterface: C.interfaceId(value.inner.sourceInterface), appData: value.inner.appData } };
    case N.DiagnosticEvent_Tags.LinkEstablished: return { tag: "LinkEstablished", data: { linkId: C.linkId(value.inner.linkId), rttMillis: liftSafeUint(value.inner.rttMillis) } };
    case N.DiagnosticEvent_Tags.PeerIdentified: return { tag: "PeerIdentified", data: { linkId: C.linkId(value.inner.linkId), identity: C.identityHash(value.inner.identity) } };
    case N.DiagnosticEvent_Tags.LinkClosed: return { tag: "LinkClosed", data: { linkId: C.linkId(value.inner.linkId), reason: liftLinkClosedReason(value.inner.reason) } };
    case N.DiagnosticEvent_Tags.LinkInterfaceMismatch: return { tag: "LinkInterfaceMismatch", data: { linkId: C.linkId(value.inner.linkId), attachedInterface: C.interfaceId(value.inner.attachedInterface), arrivedOn: C.interfaceId(value.inner.arrivedOn) } };
    case N.DiagnosticEvent_Tags.ResourceAssembled: return { tag: "ResourceAssembled", data: { linkId: C.linkId(value.inner.linkId), originalHash: C.resourceHash(value.inner.originalHash), totalSizeBytes: value.inner.totalSizeBytes } };
    case N.DiagnosticEvent_Tags.ResourceFailed: return { tag: "ResourceFailed", data: { linkId: C.linkId(value.inner.linkId), hash: C.resourceHash(value.inner.hash), cause: value.inner.cause } };
    case N.DiagnosticEvent_Tags.ResourceSendProgress: return { tag: "ResourceSendProgress", data: { linkId: C.linkId(value.inner.linkId), transferredBytes: value.inner.transferredBytes, totalBytes: value.inner.totalBytes, physicalTransferredBytes: value.inner.physicalTransferredBytes, segmentIndex: liftSafeUint(value.inner.segmentIndex), totalSegments: liftSafeUint(value.inner.totalSegments) } };
    case N.DiagnosticEvent_Tags.SelfRatchetRotated: return { tag: "SelfRatchetRotated", data: { destination: C.destinationHash(value.inner.destination) } };
    case N.DiagnosticEvent_Tags.AnnounceHeldDropped: return { tag: "AnnounceHeldDropped", data: { destination: C.destinationHash(value.inner.destination), sourceInterface: C.interfaceId(value.inner.sourceInterface), cause: value.inner.cause } };
    case N.DiagnosticEvent_Tags.Delivered: return { tag: "Delivered", data: { detail: value.inner.detail } };
    case N.DiagnosticEvent_Tags.RouteExpired: return { tag: "RouteExpired", data: { destination: C.destinationHash(value.inner.destination) } };
    case N.DiagnosticEvent_Tags.RouteEvicted: return { tag: "RouteEvicted", data: { destination: C.destinationHash(value.inner.destination) } };
    case N.DiagnosticEvent_Tags.RouteInterfaceGone: return { tag: "RouteInterfaceGone", data: { destination: C.destinationHash(value.inner.destination) } };
    case N.DiagnosticEvent_Tags.RouteDropped: return { tag: "RouteDropped", data: { destination: C.destinationHash(value.inner.destination) } };
    case N.DiagnosticEvent_Tags.BackendDiagnostic: return { tag: "BackendDiagnostic", data: { kind: value.inner.kind, detail: value.inner.detail } };
    case N.DiagnosticEvent_Tags.DiagnosticsDropped: return { tag: "DiagnosticsDropped", data: { count: liftWideCounter(value.inner.count) } };
    case N.DiagnosticEvent_Tags.PersistenceRestored: return { tag: "PersistenceRestored", data: { routes: liftSafeUint(value.inner.routes), destinationIdentities: liftSafeUint(value.inner.destinationIdentities), tunnels: liftSafeUint(value.inner.tunnels), ratchets: liftSafeUint(value.inner.ratchets), refused: liftSafeUint(value.inner.refused), dropped: liftSafeUint(value.inner.dropped) } };
    case N.DiagnosticEvent_Tags.PersistenceFlushed: return { tag: "PersistenceFlushed", data: { cause: liftPersistenceFlushCause(value.inner.cause), target: liftPersistenceFlushTarget(value.inner.target) } };
    case N.DiagnosticEvent_Tags.PersistenceFlushFailed: return { tag: "PersistenceFlushFailed", data: { cause: liftPersistenceFlushCause(value.inner.cause), target: liftPersistenceFlushTarget(value.inner.target) } };
    default: return unexpected(value);
  }
}
export function liftHostFailure(value: N.HostFailure): C.HostFailure {
  switch (value.tag) {
    case N.HostFailure_Tags.EventBackpressureExceeded: return { tag: "EventBackpressureExceeded", data: { limits: liftPrnsLimits(value.inner.limits), rejectedEventBytes: liftSafeUint(value.inner.rejectedEventBytes) } };
    case N.HostFailure_Tags.BackendFailed: return { tag: "BackendFailed", data: { component: value.inner.component, detail: value.inner.detail } };
    case N.HostFailure_Tags.ContractViolated: return { tag: "ContractViolated", data: { detail: value.inner.detail } };
    default: return unexpected(value);
  }
}
export function lowerHostFailure(value: C.HostFailure): N.HostFailure {
  switch (value.tag) {
    case "EventBackpressureExceeded": return N.HostFailure.EventBackpressureExceeded.new({ limits: lowerPrnsLimits(value.data.limits), rejectedEventBytes: lowerSafeUint(value.data.rejectedEventBytes) });
    case "BackendFailed": return N.HostFailure.BackendFailed.new({ component: value.data.component, detail: value.data.detail });
    case "ContractViolated": return N.HostFailure.ContractViolated.new({ detail: value.data.detail });
    default: return unexpected(value);
  }
}
export function liftHostLifecycleState(value: N.HostLifecycleState): C.HostLifecycleState {
  switch (value.tag) {
    case N.HostLifecycleState_Tags.Starting: return { tag: "Starting", data: undefined };
    case N.HostLifecycleState_Tags.Running: return { tag: "Running", data: undefined };
    case N.HostLifecycleState_Tags.Stopping: return { tag: "Stopping", data: undefined };
    case N.HostLifecycleState_Tags.Stopped: return { tag: "Stopped", data: { reason: liftStopReason(value.inner.reason) } };
    case N.HostLifecycleState_Tags.Failed: return { tag: "Failed", data: { failure: liftHostFailure(value.inner.failure) } };
    default: return unexpected(value);
  }
}
export function lowerHostLifecycleState(value: C.HostLifecycleState): N.HostLifecycleState {
  switch (value.tag) {
    case "Starting": return N.HostLifecycleState.Starting.new();
    case "Running": return N.HostLifecycleState.Running.new();
    case "Stopping": return N.HostLifecycleState.Stopping.new();
    case "Stopped": return N.HostLifecycleState.Stopped.new({ reason: lowerStopReason(value.data.reason) });
    case "Failed": return N.HostLifecycleState.Failed.new({ failure: lowerHostFailure(value.data.failure) });
    default: return unexpected(value);
  }
}
export function liftCommandSettlement(value: N.CommandSettlement): C.CommandSettlement {
  switch (value.tag) {
    case N.CommandSettlement_Tags.Succeeded: return { tag: "Succeeded", data: liftCommandOutcome(value.inner.outcome) };
    case N.CommandSettlement_Tags.Failed: return { tag: "Failed", data: liftCommandFailure(value.inner.failure) };
    default: return unexpected(value);
  }
}
export function lowerCommandSettlement(value: C.CommandSettlement): N.CommandSettlement {
  switch (value.tag) {
    case "Succeeded": return N.CommandSettlement.Succeeded.new({ outcome: lowerCommandOutcome(value.data) });
    case "Failed": return N.CommandSettlement.Failed.new({ failure: lowerCommandFailure(value.data) });
    default: return unexpected(value);
  }
}
