[package]
name = "hopspot-hub-prns"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
hopspot-hub-core = { path = "../core" }
personal-rns = { path = "../../../personal-rns", default-features = false, features = ["tokio-host", "usb"] }
pipecircuit = { version = "=0.0.16", default-features = false }
tokio = { version = "1", features = ["rt", "sync"] }

[dev-dependencies]
proptest = "=1.11.0"
personal-hopspot-core = { path = "../../core", default-features = false }
expect-test = "=1.5.1"
pipecircuit-visualization = "=0.0.2"
personal-rns = { path = "../../../personal-rns", default-features = false, features = ["tokio-host", "usb", "test-support", "tcp"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }

[lints]
workspace = true
