[package]
name = "personal-hopspot-assurance-kernel"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
rust-version.workspace = true
publish = false

[features]
default = []
host = []
thumbv7em = [
    "dep:cortex-m-rt",
    "dep:cortex-m-semihosting",
    "dep:panic-halt",
]

[dependencies]
embassy-futures = { version = "0.1", default-features = false }
embedded-hal = { version = "1", default-features = false }
embedded-hal-async = { version = "1", default-features = false }
prns-core = { path = "../../prns-core", default-features = false, features = ["embassy-host"] }
prns-interfaces-embassy = { path = "../../prns-interfaces/impls/embassy", default-features = false, features = ["lora"] }
cortex-m-rt = { version = "0.7", optional = true }
cortex-m-semihosting = { version = "0.5", optional = true }
panic-halt = { version = "1", optional = true }

[[bin]]
name = "assurance-host"
path = "src/bin/host.rs"
required-features = ["host"]

[[bin]]
name = "assurance-thumbv7em"
path = "src/bin/thumbv7em.rs"
required-features = ["thumbv7em"]

[lints]
workspace = true
