// Generated by tools/repo/generate-app-uniffi-host.py. Do not edit.
import type { BackendInfo, InterfaceSnapshot, RouteSnapshot, DestinationIdentitySnapshot, RuntimeHealthSnapshot, PersistenceSnapshot, HostSnapshot } from "personal-rns/contract";
import type { BackendInfoTransport, InterfaceSnapshotTransport, RouteSnapshotTransport, DestinationIdentitySnapshotTransport, RuntimeHealthSnapshotTransport, PersistenceSnapshotTransport, HostSnapshotTransport } from "./prns_app";

export function liftSafeUint(value: bigint): number {
  if (value < 0n || value > 9_007_199_254_740_991n) throw new RangeError("safeUint is outside the canonical JS integer range");
  return Number(value);
}
export function lowerSafeUint(value: number): bigint {
  if (!Number.isSafeInteger(value) || value < 0) throw new RangeError("expected a non-negative safe integer");
  return BigInt(value);
}

import type { BackendKind } from "personal-rns/contract";
export function liftBackendKind(value: string): BackendKind {
  switch (value) {
    case "Native": return value;
    case "Browser": return value;
    case "Cooperative": return value;
    default: throw new TypeError("unknown canonical enum value");
  }
}

import type { CapabilityName } from "personal-rns/contract";
export function liftCapability(value: string): CapabilityName {
  switch (value) {
    case "Loopback": return value;
    case "TcpClient": return value;
    case "TcpServer": return value;
    case "Udp": return value;
    case "Serial": return value;
    case "Usb": return value;
    case "Bluetooth": return value;
    case "Wifi": return value;
    case "WebSocket": return value;
    case "BrowserRendezvous": return value;
    case "I2p": return value;
    case "Weave": return value;
    case "SuppliedPipe": return value;
    default: throw new TypeError("unknown canonical enum value");
  }
}

import type { InterfaceKind } from "personal-rns/contract";
export function liftInterfaceKind(value: string): InterfaceKind {
  switch (value) {
    case "AutoLan": return value;
    case "TcpClient": return value;
    case "TcpServer": return value;
    case "Udp": return value;
    case "Serial": return value;
    case "Kiss": return value;
    case "Ax25Kiss": return value;
    case "RNode": return value;
    case "MultiRNode": return value;
    case "Pipe": return value;
    case "BackboneClient": return value;
    case "BackboneServer": return value;
    case "I2p": return value;
    case "Weave": return value;
    case "AutomaticUsb": return value;
    case "AutomaticBluetoothLe": return value;
    case "WebSocketClient": return value;
    case "WebSocketServer": return value;
    case "BrowserRendezvous": return value;
    default: throw new TypeError("unknown canonical enum value");
  }
}

import type { InterfaceHealth } from "personal-rns/contract";
export function liftInterfaceHealth(value: string): InterfaceHealth {
  switch (value) {
    case "Initializing": return value;
    case "Connected": return value;
    case "Degraded": return value;
    case "Reconnecting": return value;
    case "Failed": return value;
    case "Disconnected": return value;
    case "Disabled": return value;
    case "Unknown": return value;
    default: throw new TypeError("unknown canonical enum value");
  }
}

import type { PersistenceFlushCause } from "personal-rns/contract";
export function liftPersistenceFlushCause(value: string): PersistenceFlushCause {
  switch (value) {
    case "Startup": return value;
    case "Interval": return value;
    case "RouteChange": return value;
    case "RatchetRotation": return value;
    case "Shutdown": return value;
    default: throw new TypeError("unknown canonical enum value");
  }
}

export function liftBackendInfo(value: BackendInfoTransport): BackendInfo {
  return {
    backend: value.backend,
    capabilities: value.capabilities.map((item) => item),
    interfaceKinds: value.interfaceKinds.map((item) => item),
  };
}

export function lowerBackendInfo(value: BackendInfo): BackendInfoTransport {
  return {
    backend: value.backend,
    capabilities: value.capabilities.map((item) => item),
    interfaceKinds: value.interfaceKinds.map((item) => item),
  };
}

export function liftInterfaceSnapshot(value: InterfaceSnapshotTransport): InterfaceSnapshot {
  return {
    interfaceId: value.interfaceId,
    ...(value.name === undefined ? {} : { name: value.name }),
    ...(value.kind === undefined ? {} : { kind: value.kind }),
    health: value.health,
    ...(value.failureDetail === undefined ? {} : { failureDetail: value.failureDetail }),
    rxBytes: value.rxBytes,
    txBytes: value.txBytes,
    ...(value.rxBps === undefined ? {} : { rxBps: value.rxBps }),
    ...(value.txBps === undefined ? {} : { txBps: value.txBps }),
    routeCount: value.routeCount,
    linkCount: value.linkCount,
    transportedLinkCount: value.transportedLinkCount,
  };
}

export function lowerInterfaceSnapshot(value: InterfaceSnapshot): InterfaceSnapshotTransport {
  return {
    interfaceId: value.interfaceId,
    ...(value.name === undefined ? {} : { name: value.name }),
    ...(value.kind === undefined ? {} : { kind: value.kind }),
    health: value.health,
    ...(value.failureDetail === undefined ? {} : { failureDetail: value.failureDetail }),
    rxBytes: value.rxBytes,
    txBytes: value.txBytes,
    ...(value.rxBps === undefined ? {} : { rxBps: value.rxBps }),
    ...(value.txBps === undefined ? {} : { txBps: value.txBps }),
    routeCount: value.routeCount,
    linkCount: value.linkCount,
    transportedLinkCount: value.transportedLinkCount,
  };
}

export function liftRouteSnapshot(value: RouteSnapshotTransport): RouteSnapshot {
  return {
    destination: value.destination,
    hops: value.hops,
    ...(value.viaIdentity === undefined ? {} : { viaIdentity: value.viaIdentity }),
    interfaceId: value.interfaceId,
    learnedAtMillis: value.learnedAtMillis,
    lastRouteActivityAtMillis: value.lastRouteActivityAtMillis,
    expiresAtMillis: value.expiresAtMillis,
  };
}

export function lowerRouteSnapshot(value: RouteSnapshot): RouteSnapshotTransport {
  return {
    destination: value.destination,
    hops: value.hops,
    ...(value.viaIdentity === undefined ? {} : { viaIdentity: value.viaIdentity }),
    interfaceId: value.interfaceId,
    learnedAtMillis: value.learnedAtMillis,
    lastRouteActivityAtMillis: value.lastRouteActivityAtMillis,
    expiresAtMillis: value.expiresAtMillis,
  };
}

export function liftDestinationIdentitySnapshot(value: DestinationIdentitySnapshotTransport): DestinationIdentitySnapshot {
  return {
    destination: value.destination,
    identity: value.identity,
  };
}

export function lowerDestinationIdentitySnapshot(value: DestinationIdentitySnapshot): DestinationIdentitySnapshotTransport {
  return {
    destination: value.destination,
    identity: value.identity,
  };
}

export function liftRuntimeHealthSnapshot(value: RuntimeHealthSnapshotTransport): RuntimeHealthSnapshot {
  return {
    running: value.running,
    uptimeMillis: value.uptimeMillis,
    interfaceCount: value.interfaceCount,
    onlineInterfaceCount: value.onlineInterfaceCount,
    routeCount: value.routeCount,
    linkCount: value.linkCount,
    transportedLinkCount: value.transportedLinkCount,
    rxBytes: value.rxBytes,
    txBytes: value.txBytes,
    rxBps: value.rxBps,
    txBps: value.txBps,
  };
}

export function lowerRuntimeHealthSnapshot(value: RuntimeHealthSnapshot): RuntimeHealthSnapshotTransport {
  return {
    running: value.running,
    uptimeMillis: value.uptimeMillis,
    interfaceCount: value.interfaceCount,
    onlineInterfaceCount: value.onlineInterfaceCount,
    routeCount: value.routeCount,
    linkCount: value.linkCount,
    transportedLinkCount: value.transportedLinkCount,
    rxBytes: value.rxBytes,
    txBytes: value.txBytes,
    rxBps: value.rxBps,
    txBps: value.txBps,
  };
}

export function liftPersistenceSnapshot(value: PersistenceSnapshotTransport): PersistenceSnapshot {
  return {
    persistent: value.persistent,
    restored: value.restored,
    ...(value.lastFlushCause === undefined ? {} : { lastFlushCause: value.lastFlushCause }),
    ...(value.lastFailureDetail === undefined ? {} : { lastFailureDetail: value.lastFailureDetail }),
  };
}

export function lowerPersistenceSnapshot(value: PersistenceSnapshot): PersistenceSnapshotTransport {
  return {
    persistent: value.persistent,
    restored: value.restored,
    ...(value.lastFlushCause === undefined ? {} : { lastFlushCause: value.lastFlushCause }),
    ...(value.lastFailureDetail === undefined ? {} : { lastFailureDetail: value.lastFailureDetail }),
  };
}

export function liftHostSnapshot(value: HostSnapshotTransport): HostSnapshot {
  return {
    revision: value.revision,
    backend: liftBackendInfo(value.backend),
    interfaces: value.interfaces.map((item) => liftInterfaceSnapshot(item)),
    routes: value.routes.map((item) => liftRouteSnapshot(item)),
    activeLinkCount: value.activeLinkCount,
    destinationIdentities: value.destinationIdentities.map((item) => liftDestinationIdentitySnapshot(item)),
    runtime: liftRuntimeHealthSnapshot(value.runtime),
    persistence: liftPersistenceSnapshot(value.persistence),
  };
}

export function lowerHostSnapshot(value: HostSnapshot): HostSnapshotTransport {
  return {
    revision: value.revision,
    backend: lowerBackendInfo(value.backend),
    interfaces: value.interfaces.map((item) => lowerInterfaceSnapshot(item)),
    routes: value.routes.map((item) => lowerRouteSnapshot(item)),
    activeLinkCount: value.activeLinkCount,
    destinationIdentities: value.destinationIdentities.map((item) => lowerDestinationIdentitySnapshot(item)),
    runtime: lowerRuntimeHealthSnapshot(value.runtime),
    persistence: lowerPersistenceSnapshot(value.persistence),
  };
}
