// This file was autogenerated by some hot garbage in the `uniffi-bindgen-react-native` crate.
// Trust me, you don't want to mess with it!
import { FfiType } from "@ubjs/core";

import {
  type StructuralEquality as UniffiStructuralEquality,
  type UniffiForeignFuture as RuntimeUniffiForeignFuture,
  type UniffiRustCallStatus,
  type UniffiGcObject,
  type UniffiRustFutureContinuationCallback as RuntimeUniffiRustFutureContinuationCallback,
  type UniffiResult,
} from '@ubjs/core';

// Arrays stay mutable; readonly does not assign to `FfiTypeDesc[]`.
const DEFINITIONS = {
  symbols: {
    rustbuffer_alloc: "ffi_prns_app_rustbuffer_alloc",
    rustbuffer_free: "ffi_prns_app_rustbuffer_free",
    rustbuffer_from_bytes: "ffi_prns_app_rustbuffer_from_bytes",
  },
  functions: {
    "ffi_prns_app_rust_future_poll_u8": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_cancel_u8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_complete_u8": {
      args: [FfiType.Handle],
      ret: FfiType.UInt8,
      hasRustCallStatus: true,
    },
    "ffi_prns_app_rust_future_free_u8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_poll_i8": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_cancel_i8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_complete_i8": {
      args: [FfiType.Handle],
      ret: FfiType.Int8,
      hasRustCallStatus: true,
    },
    "ffi_prns_app_rust_future_free_i8": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_poll_u16": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_cancel_u16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_complete_u16": {
      args: [FfiType.Handle],
      ret: FfiType.UInt16,
      hasRustCallStatus: true,
    },
    "ffi_prns_app_rust_future_free_u16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_poll_i16": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_cancel_i16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_complete_i16": {
      args: [FfiType.Handle],
      ret: FfiType.Int16,
      hasRustCallStatus: true,
    },
    "ffi_prns_app_rust_future_free_i16": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_poll_u32": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_cancel_u32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_complete_u32": {
      args: [FfiType.Handle],
      ret: FfiType.UInt32,
      hasRustCallStatus: true,
    },
    "ffi_prns_app_rust_future_free_u32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_poll_i32": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_cancel_i32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_complete_i32": {
      args: [FfiType.Handle],
      ret: FfiType.Int32,
      hasRustCallStatus: true,
    },
    "ffi_prns_app_rust_future_free_i32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_poll_u64": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_cancel_u64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_complete_u64": {
      args: [FfiType.Handle],
      ret: FfiType.Handle,
      hasRustCallStatus: true,
    },
    "ffi_prns_app_rust_future_free_u64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_poll_i64": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_cancel_i64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_complete_i64": {
      args: [FfiType.Handle],
      ret: FfiType.Int64,
      hasRustCallStatus: true,
    },
    "ffi_prns_app_rust_future_free_i64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_poll_f32": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_cancel_f32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_complete_f32": {
      args: [FfiType.Handle],
      ret: FfiType.Float32,
      hasRustCallStatus: true,
    },
    "ffi_prns_app_rust_future_free_f32": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_poll_f64": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_cancel_f64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_complete_f64": {
      args: [FfiType.Handle],
      ret: FfiType.Float64,
      hasRustCallStatus: true,
    },
    "ffi_prns_app_rust_future_free_f64": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_poll_rust_buffer": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_cancel_rust_buffer": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_complete_rust_buffer": {
      args: [FfiType.Handle],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "ffi_prns_app_rust_future_free_rust_buffer": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_poll_void": {
      args: [FfiType.Handle, FfiType.Callback("RustFutureContinuationCallback"), FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_cancel_void": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_rust_future_complete_void": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: true,
    },
    "ffi_prns_app_rust_future_free_void": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_announce_lxmf": {
      args: [],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_announce_target": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_approve_pairing": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_binding_contract": {
      args: [],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_prns_app_fn_func_cancel_lxmf_message": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_create_manual_contact": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_delete_contact": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_describe_target": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_get_contact": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_initiate_pairing": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_list_contacts": {
      args: [],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_list_lxmf_messages": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_list_lxmf_peers": {
      args: [],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_measure_lxmf_text": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_native_create_generated_identity": {
      args: [FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_prns_app_fn_func_native_create_imported_identity": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_prns_app_fn_func_native_inspect_identity": {
      args: [FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_prns_app_fn_func_native_prepare_apple_bluetooth_central_restoration": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_prns_app_fn_func_native_prepare_storage": {
      args: [FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_prns_app_fn_func_native_reset": {
      args: [FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_prns_app_fn_func_native_start": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_prns_app_fn_func_native_start_with_apple_bluetooth_central_restoration": {
      args: [FfiType.RustBuffer, FfiType.RustBuffer, FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_prns_app_fn_func_native_stop": {
      args: [],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_prns_app_fn_func_preview_identity_import": {
      args: [FfiType.RustBuffer],
      ret: FfiType.RustBuffer,
      hasRustCallStatus: true,
    },
    "uniffi_prns_app_fn_func_read_snapshot": {
      args: [],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_reject_pairing": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_retry_lxmf_message": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_save_observed_destination": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_send_direct_text": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_set_contact_alias": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_fn_func_set_contact_pinned": {
      args: [FfiType.RustBuffer],
      ret: FfiType.Handle,
      hasRustCallStatus: false,
    },
    "ffi_prns_app_uniffi_contract_version": {
      args: [],
      ret: FfiType.UInt32,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_announce_lxmf": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_announce_target": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_approve_pairing": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_binding_contract": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_cancel_lxmf_message": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_create_manual_contact": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_delete_contact": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_describe_target": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_get_contact": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_initiate_pairing": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_list_contacts": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_list_lxmf_messages": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_list_lxmf_peers": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_measure_lxmf_text": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_native_create_generated_identity": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_native_create_imported_identity": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_native_inspect_identity": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_native_prepare_apple_bluetooth_central_restoration": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_native_prepare_storage": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_native_reset": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_native_start": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_native_start_with_apple_bluetooth_central_restoration": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_native_stop": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_preview_identity_import": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_read_snapshot": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_reject_pairing": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_retry_lxmf_message": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_save_observed_destination": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_send_direct_text": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_set_contact_alias": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
    "uniffi_prns_app_checksum_func_set_contact_pinned": {
      args: [],
      ret: FfiType.UInt16,
      hasRustCallStatus: false,
    },
  },
  callbacks: {
    "RustFutureContinuationCallback": {
      args: [FfiType.Handle, FfiType.Int8],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
    "ForeignFutureDroppedCallback": {
      args: [FfiType.Handle],
      ret: FfiType.Void,
      hasRustCallStatus: false,
    },
  },
  structs: {
    "ForeignFutureDroppedCallbackStruct": [
      { name: "handle", type: FfiType.Handle },
      { name: "free", type: FfiType.Callback("ForeignFutureDroppedCallback") },
    ],
  },
};

interface NativeModuleInterface {
    ubrn_uniffi_internal_fn_func_ffi__string_to_byte_length(string: string, uniffi_out_err: UniffiRustCallStatus): number;
    ubrn_uniffi_internal_fn_func_ffi__string_to_buffer(string: string, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    ubrn_uniffi_internal_fn_func_ffi__string_from_buffer(buffer: Uint8Array, uniffi_out_err: UniffiRustCallStatus): string;
    ubrn_uniffi_internal_fn_func_ffi__read_string_from_buffer(buffer: any, offset: number, length: number): string;
    ffi_prns_app_rust_future_poll_u8(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_prns_app_rust_future_cancel_u8(handle: bigint): void;
    ffi_prns_app_rust_future_complete_u8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_prns_app_rust_future_free_u8(handle: bigint): void;
    ffi_prns_app_rust_future_poll_i8(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_prns_app_rust_future_cancel_i8(handle: bigint): void;
    ffi_prns_app_rust_future_complete_i8(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_prns_app_rust_future_free_i8(handle: bigint): void;
    ffi_prns_app_rust_future_poll_u16(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_prns_app_rust_future_cancel_u16(handle: bigint): void;
    ffi_prns_app_rust_future_complete_u16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_prns_app_rust_future_free_u16(handle: bigint): void;
    ffi_prns_app_rust_future_poll_i16(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_prns_app_rust_future_cancel_i16(handle: bigint): void;
    ffi_prns_app_rust_future_complete_i16(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_prns_app_rust_future_free_i16(handle: bigint): void;
    ffi_prns_app_rust_future_poll_u32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_prns_app_rust_future_cancel_u32(handle: bigint): void;
    ffi_prns_app_rust_future_complete_u32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_prns_app_rust_future_free_u32(handle: bigint): void;
    ffi_prns_app_rust_future_poll_i32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_prns_app_rust_future_cancel_i32(handle: bigint): void;
    ffi_prns_app_rust_future_complete_i32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_prns_app_rust_future_free_i32(handle: bigint): void;
    ffi_prns_app_rust_future_poll_u64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_prns_app_rust_future_cancel_u64(handle: bigint): void;
    ffi_prns_app_rust_future_complete_u64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    ffi_prns_app_rust_future_free_u64(handle: bigint): void;
    ffi_prns_app_rust_future_poll_i64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_prns_app_rust_future_cancel_i64(handle: bigint): void;
    ffi_prns_app_rust_future_complete_i64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): bigint;
    ffi_prns_app_rust_future_free_i64(handle: bigint): void;
    ffi_prns_app_rust_future_poll_f32(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_prns_app_rust_future_cancel_f32(handle: bigint): void;
    ffi_prns_app_rust_future_complete_f32(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_prns_app_rust_future_free_f32(handle: bigint): void;
    ffi_prns_app_rust_future_poll_f64(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_prns_app_rust_future_cancel_f64(handle: bigint): void;
    ffi_prns_app_rust_future_complete_f64(handle: bigint, uniffi_out_err: UniffiRustCallStatus): number;
    ffi_prns_app_rust_future_free_f64(handle: bigint): void;
    ffi_prns_app_rust_future_poll_rust_buffer(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_prns_app_rust_future_cancel_rust_buffer(handle: bigint): void;
    ffi_prns_app_rust_future_complete_rust_buffer(handle: bigint, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    ffi_prns_app_rust_future_free_rust_buffer(handle: bigint): void;
    ffi_prns_app_rust_future_poll_void(handle: bigint, callback: UniffiRustFutureContinuationCallback, callbackData: bigint): void;
    ffi_prns_app_rust_future_cancel_void(handle: bigint): void;
    ffi_prns_app_rust_future_complete_void(handle: bigint, uniffi_out_err: UniffiRustCallStatus): void;
    ffi_prns_app_rust_future_free_void(handle: bigint): void;
    uniffi_prns_app_fn_func_announce_lxmf(): bigint;
    uniffi_prns_app_fn_func_announce_target(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_approve_pairing(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_binding_contract(uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_prns_app_fn_func_cancel_lxmf_message(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_create_manual_contact(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_delete_contact(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_describe_target(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_get_contact(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_initiate_pairing(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_list_contacts(): bigint;
    uniffi_prns_app_fn_func_list_lxmf_messages(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_list_lxmf_peers(): bigint;
    uniffi_prns_app_fn_func_measure_lxmf_text(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_native_create_generated_identity(storageRoot: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_prns_app_fn_func_native_create_imported_identity(storageRoot: Uint8Array, identity: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_prns_app_fn_func_native_inspect_identity(storageRoot: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_prns_app_fn_func_native_prepare_apple_bluetooth_central_restoration(storageRoot: Uint8Array, centralIdentifier: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_prns_app_fn_func_native_prepare_storage(storageRoot: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_prns_app_fn_func_native_reset(storageRoot: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_prns_app_fn_func_native_start(storageRoot: Uint8Array, input: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_prns_app_fn_func_native_start_with_apple_bluetooth_central_restoration(storageRoot: Uint8Array, input: Uint8Array, centralIdentifier: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_prns_app_fn_func_native_stop(uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_prns_app_fn_func_preview_identity_import(identity: Uint8Array, uniffi_out_err: UniffiRustCallStatus): Uint8Array;
    uniffi_prns_app_fn_func_read_snapshot(): bigint;
    uniffi_prns_app_fn_func_reject_pairing(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_retry_lxmf_message(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_save_observed_destination(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_send_direct_text(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_set_contact_alias(input: Uint8Array): bigint;
    uniffi_prns_app_fn_func_set_contact_pinned(input: Uint8Array): bigint;
    ffi_prns_app_uniffi_contract_version(): number;
    uniffi_prns_app_checksum_func_announce_lxmf(): number;
    uniffi_prns_app_checksum_func_announce_target(): number;
    uniffi_prns_app_checksum_func_approve_pairing(): number;
    uniffi_prns_app_checksum_func_binding_contract(): number;
    uniffi_prns_app_checksum_func_cancel_lxmf_message(): number;
    uniffi_prns_app_checksum_func_create_manual_contact(): number;
    uniffi_prns_app_checksum_func_delete_contact(): number;
    uniffi_prns_app_checksum_func_describe_target(): number;
    uniffi_prns_app_checksum_func_get_contact(): number;
    uniffi_prns_app_checksum_func_initiate_pairing(): number;
    uniffi_prns_app_checksum_func_list_contacts(): number;
    uniffi_prns_app_checksum_func_list_lxmf_messages(): number;
    uniffi_prns_app_checksum_func_list_lxmf_peers(): number;
    uniffi_prns_app_checksum_func_measure_lxmf_text(): number;
    uniffi_prns_app_checksum_func_native_create_generated_identity(): number;
    uniffi_prns_app_checksum_func_native_create_imported_identity(): number;
    uniffi_prns_app_checksum_func_native_inspect_identity(): number;
    uniffi_prns_app_checksum_func_native_prepare_apple_bluetooth_central_restoration(): number;
    uniffi_prns_app_checksum_func_native_prepare_storage(): number;
    uniffi_prns_app_checksum_func_native_reset(): number;
    uniffi_prns_app_checksum_func_native_start(): number;
    uniffi_prns_app_checksum_func_native_start_with_apple_bluetooth_central_restoration(): number;
    uniffi_prns_app_checksum_func_native_stop(): number;
    uniffi_prns_app_checksum_func_preview_identity_import(): number;
    uniffi_prns_app_checksum_func_read_snapshot(): number;
    uniffi_prns_app_checksum_func_reject_pairing(): number;
    uniffi_prns_app_checksum_func_retry_lxmf_message(): number;
    uniffi_prns_app_checksum_func_save_observed_destination(): number;
    uniffi_prns_app_checksum_func_send_direct_text(): number;
    uniffi_prns_app_checksum_func_set_contact_alias(): number;
    uniffi_prns_app_checksum_func_set_contact_pinned(): number;
    // Codegen call sites use these via `nativeModule().rustbuffer_alloc(...)`
    // and `nativeModule().rustbuffer_free(...)`. The runtime's registered
    // module exposes them as method properties.
    rustbuffer_alloc(n: number): Uint8Array;
    rustbuffer_free(view: Uint8Array): void;
}

let _nativeModule: NativeModuleInterface | undefined;
const getter: () => NativeModuleInterface = () => {
  if (!_nativeModule) {
    const libPath = { name: "prns_app" };
    const uniffi = (globalThis as any).uniffi;
    const mod_ = uniffi.open(libPath);
    _nativeModule = mod_.register(DEFINITIONS) as unknown as NativeModuleInterface;
  }
  return _nativeModule;
};
export default getter;

// Structs and function types for calling back into Typescript from Rust.
export type UniffiRustFutureContinuationCallback = (data: bigint, pollResult: number) => void;
export type UniffiForeignFutureDroppedCallback = (handle: bigint) => void;
export type UniffiForeignFutureDroppedCallbackStruct = {
  handle: bigint;
  free: UniffiForeignFutureDroppedCallback;
};
