/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class InterfaceHandle {
  get id(): Buffer
  get kind(): string | null
  teardown(): boolean
}

export declare class PrnsNode {
  get destinationHashes(): Array<Buffer>
  ready(): Promise<void>
  stop(): Promise<void>
  announce(destination: Buffer, options?: AnnounceOptions | undefined | null): Promise<void>
  sendSinglePacket(destination: Buffer, data: Buffer): Promise<PacketReceipt>
  establishLink(destination: Buffer): Promise<Buffer>
  establishLinkWithRtt(destination: Buffer): Promise<LinkInfo>
  closeLink(linkId: Buffer): boolean
  requestPath(destination: Buffer): Promise<PathInfo>
  identify(linkId: Buffer, identity: Buffer): Promise<void>
  request(linkId: Buffer, pathHash: Buffer, data: Buffer, options?: RequestOptions | undefined | null): Promise<RequestResult>
  respond(token: RespondTokenSpec, data: Buffer): Promise<number>
  respondFile(token: RespondTokenSpec, path: string): Promise<number>
  allowRequester(destination: Buffer, pathHash: Buffer, identity: Buffer): Promise<void>
  attachTcpServer(options: TcpServerOptions): Promise<InterfaceHandle>
  attachTcpClient(options: TcpClientOptions): Promise<InterfaceHandle>
  attachUdp(options: UdpOptions): Promise<InterfaceHandle>
  attachSharedInstanceServer(options?: SharedInstanceOptions | undefined | null): Promise<InterfaceHandle>
  attachSharedInstanceClient(options?: SharedInstanceOptions | undefined | null): Promise<InterfaceHandle>
  attachConfig(configText: string): Promise<ConfigAttachResult>
  sendResource(linkId: Buffer, data: Buffer, options?: SendResourceOptions | undefined | null): Promise<void>
  sendResourceFile(linkId: Buffer, path: string, options?: SendResourceOptions | undefined | null): Promise<void>
  receiveResource(linkId: Buffer): Promise<ResourceData>
  receiveResourceFile(linkId: Buffer, path: string): Promise<ResourceFileReceipt>
  setResourceStrategy(destination: Buffer, strategy: ResourceStrategySpec): Promise<boolean>
  setLinkResourceStrategy(linkId: Buffer, strategy: ResourceStrategySpec): Promise<void>
}

export interface AnnounceOptions {
  interfaceId?: Buffer
}

export interface ConfigAttachment {
  name: string
  id: Buffer
}

export interface ConfigAttachResult {
  attached: Array<ConfigAttachment>
  failures: Array<ConfigFailure>
  warnings: Array<string>
}

export interface ConfigFailure {
  name: string
  error: string
}

export interface DestinationSpec {
  appName: string
  aspects: Array<string>
  kind?: string
  identity?: IdentitySpec
  announceAppData?: Buffer
  proof?: string
  linkRequests?: string
  ratchet?: string
  resourceStrategy?: ResourceStrategySpec
  requestPaths?: Array<RequestPathSpec>
}

export declare function generateIdentitySecret(): Buffer

export interface IdentitySpec {
  secret?: Buffer
  path?: string
}

export interface LinkInfo {
  linkId: Buffer
  rttMillis: number
}

export interface NodeOptions {
  identity?: IdentitySpec
  transport?: boolean
  destinations?: Array<DestinationSpec>
}

export interface PacketReceipt {
  rttMillis: number
  evidence: string
  packetHash?: Buffer
}

export interface PathInfo {
  hops: number
}

export interface RequestOptions {
  timeoutMs?: number
}

export declare function requestPathHash(path: string): Buffer

export interface RequestPathSpec {
  path: string
  policy?: string
}

export interface RequestResult {
  data: Buffer
  packed: Buffer
  rttMillis: number
}

export interface ResourceData {
  data: Buffer
  metadata?: Buffer
  originalHash: Buffer
  totalSize: number
}

export interface ResourceFileReceipt {
  metadata?: Buffer
  originalHash: Buffer
  totalSize: number
}

export interface ResourceStrategySpec {
  accept: string
  maxUncompressedLen?: number
  acceptCompressed?: boolean
}

export interface RespondTokenSpec {
  linkId: Buffer
  requestId: Buffer
  rttMillis: number
}

export interface SendResourceOptions {
  metadata?: Buffer
  compression?: string
  progress?: boolean
}

export interface SharedInstanceOptions {
  port?: number
}

export declare function startNode(options: NodeOptions, onEvent: (event: Record<string, any>) => void): PrnsNode

export interface TcpClientOptions {
  target: string
  bitrateBps?: number
}

export interface TcpServerOptions {
  bind: string
  bitrateBps?: number
}

export interface UdpOptions {
  local: string
  peer: string
  bitrateBps?: number
}

export declare function version(): string
